module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le module six de notre préparation au CAPM, consacré à l'examen de mi-parcours et à la consolidation des acquis. Nous avons parcouru cinq modules riches, des fondamentaux jusqu'à la valeur acquise. Il est temps de faire le point. Dans ce module, nous allons réviser les notions essentielles, nous entraîner sur des questions de type CAPM, analyser un scénario, et construire un plan de remédiation. L'objectif est simple, savoir précisément où vous en êtes avant de poursuivre.`,
// 2
`L'examen de mi-parcours est l'occasion de vérifier que vous avez bien compris les concepts des modules un à cinq. Les fondamentaux, les méthodes prédictives, la planification, les risques, les parties prenantes, et le suivi du projet. Mais c'est aussi, et surtout, l'occasion d'identifier vos points faibles, pour ajuster votre plan de révision. Un mauvais résultat à mi-parcours n'est pas un échec. C'est une information précieuse, qui vous permet de corriger le tir, bien avant l'examen final et la certification. Profitez-en.`,
// 3
`Pourquoi ce module est-il utile ? Pour la certification d'abord, car la pratique des questions à choix multiples de type CAPM est essentielle. Leur formulation est particulière, et il faut s'y habituer. Pour l'auto-évaluation ensuite, car identifier vos lacunes maintenant vous laisse le temps de les combler avant l'examen final. Et pour la confiance enfin, car passer un examen blanc vous prépare mentalement. Le jour de la certification, les conditions vous sembleront familières, et le stress sera bien moins fort.`,
// 4
`Voici les points clés à réviser pour les modules un à cinq. Les définitions, projet, programme et portefeuille. Les rôles, sponsor et chef de projet. Les structures organisationnelles, fonctionnelle, matricielle et projet. Les cycles de vie, prédictif, adaptatif et hybride. La charte de projet et la WBS. Les dépendances et le chemin critique. Les estimations. Les risques et leurs réponses. La matrice pouvoir intérêt et la matrice RACI. Et enfin l'EVM, avec PV, EV, AC, CPI et SPI. Cochez chaque notion que vous maîtrisez vraiment.`,
// 5
`Passons à la pratique avec une première question de type CAPM. Quel document donne au chef de projet l'autorité d'utiliser les ressources du projet ? Les propositions sont le plan de management, la charte de projet, la WBS, et le registre des risques. La bonne réponse est b, la charte de projet. C'est elle qui officialise le projet et nomme le chef de projet, en lui donnant l'autorité nécessaire. Le plan de management décrit comment gérer le projet, la WBS décompose le travail, et le registre suit les risques.`,
// 6
`Deuxième question. Une structure organisationnelle matricielle donne au chef de projet quelle autorité ? Une autorité forte, faible, partagée, ou aucune autorité ? La bonne réponse est c, une autorité partagée. Dans une structure matricielle, le chef de projet partage l'autorité avec les responsables fonctionnels, dont dépendent les membres de l'équipe. Rappelez-vous la gradation, autorité faible en structure fonctionnelle, partagée en structure matricielle, et forte en structure projet. Cette gradation est un classique de l'examen. Apprenez-la bien, avec des exemples.`,
// 7
`Troisième question. Si le CPI d'un projet est de zéro virgule quatre-vingt-cinq, que cela signifie-t-il ? Le projet est-il en dessous du budget, au-dessus du budget, en avance ou en retard ? La bonne réponse est b, le projet est au-dessus du budget. Le CPI, égal à EV divisé par AC, est inférieur à un, ce qui veut dire que l'on dépense plus que la valeur du travail réalisé. Attention au piège, le CPI parle des coûts, pas des délais. Pour le retard ou l'avance, il faudrait regarder le SPI.`,
// 8
`Analysons maintenant un scénario. Un projet de système de gestion de stock a son périmètre défini, sa WBS construite et son planning établi. Un risque majeur est identifié, la livraison d'un composant critique par un fournisseur pourrait être retardée. Que faire ? D'abord, inscrire ce risque au registre, l'analyser, et planifier une réponse, par exemple transférer avec des pénalités contractuelles, ou atténuer avec un second fournisseur. Ensuite, dans le planning, vérifier si ce composant est sur le chemin critique, et prévoir une marge ou une réserve adaptée.`,
// 9
`Après l'examen de mi-parcours, construisez votre plan de remédiation en quatre étapes. Un, identifier les domaines où vous avez le plus de difficultés, en analysant vos erreurs. Deux, revoir les modules correspondants, en relisant le cours et les résumés. Trois, faire des exercices supplémentaires sur ces points précis. Et quatre, planifier des révisions ciblées, avec un calendrier réaliste. Le secret est de travailler vos faiblesses, et pas seulement ce que vous maîtrisez déjà. C'est moins agréable, mais bien plus efficace.`,
// 10
`Voici l'application pratique de ce module. Réalisez un examen blanc de cinquante questions, en soixante minutes, couvrant les modules un à cinq. Placez-vous dans les vraies conditions, sans cours, sans téléphone, et avec un chronomètre. Cela représente un peu plus d'une minute par question, ce qui oblige à rester concentré et rythmé. À la fin, corrigez-vous, et surtout analysez chaque erreur. Était-ce un manque de connaissance, une lecture trop rapide, ou un piège dans la question ? Chaque type d'erreur appelle une réponse différente.`,
// 11
`Voici quatre pièges fréquents à l'examen. Premier piège, ne pas gérer son temps, en passant trop de temps sur une question difficile. Marquez-la, et revenez-y plus tard. Deuxième piège, lire trop vite, et rater un mot clé comme sauf, toujours ou jamais, qui change tout le sens de la question. Troisième piège, ne pas relire ses réponses, alors qu'il reste du temps. Et quatrième piège, paniquer face à une question difficile. Respirez, éliminez les réponses clairement fausses, et choisissez la meilleure parmi celles qui restent.`,
// 12
`Voici le résumé de ce module. L'examen de mi-parcours valide les acquis des modules un à cinq. La pratique des questions à choix multiples, et surtout l'analyse de vos erreurs, sont essentielles pour progresser. Enfin, identifiez vos points faibles, et ajustez votre plan de révision en conséquence. Retenez que l'objectif n'est pas seulement d'obtenir une bonne note aujourd'hui, mais d'arriver parfaitement préparé à l'examen final, puis à la certification CAPM. Chaque erreur corrigée maintenant est un point gagné plus tard.`,
// 13
`Voici trois exercices, avec des pistes. Premier exercice, passez un examen blanc de cinquante questions chronométré, dans les conditions réelles. Deuxième exercice, dressez la liste de vos points forts et de vos points faibles, par module et par type de question, calcul, vocabulaire ou scénario. Troisième exercice, si vous bloquez sur une question, ne restez pas figé. Éliminez les réponses clairement fausses, choisissez la meilleure restante, marquez la question, et passez à la suivante. Vous y reviendrez à la fin, l'esprit plus clair.`,
// 14
`Passons au quiz de vérification. Première question, l'examen de mi-parcours couvre quels modules ? Un à trois, un à cinq, un à sept, ou un à dix ? La bonne réponse est b, les modules un à cinq. Ils couvrent les fondamentaux, les méthodes prédictives, la planification, les risques, les parties prenantes et le suivi. Les modules suivants, consacrés à l'agilité, à l'hybride et à la business analysis, seront évalués lors de l'examen final. Organisez donc vos révisions en fonction de ce découpage.`,
// 15
`Deuxième question. Une question de type CAPM est généralement une question de théorie pure, un scénario avec un contexte, une question de calcul uniquement, ou une question de vocabulaire ? La bonne réponse est b, un scénario avec un contexte. La plupart des questions décrivent une situation de projet, puis demandent ce que le chef de projet devrait faire, ou quel outil utiliser. Il ne suffit donc pas de connaître les définitions. Il faut savoir les appliquer à une situation concrète, et choisir la meilleure action possible.`,
// 16
`Troisième question. Si vous ne connaissez pas la réponse à une question, que devez-vous faire ? Deviner au hasard, éliminer les réponses clairement fausses et choisir la meilleure, sauter la question, ou demander à un voisin ? La bonne réponse est b. La méthode d'élimination augmente fortement vos chances. Avec deux réponses éliminées, vous passez d'une chance sur quatre à une chance sur deux. Et comme il n'y a pas de pénalité pour une mauvaise réponse, ne laissez jamais une question sans réponse.`,
// 17
`Quatrième question. La gestion du temps pendant un examen est-elle optionnelle, cruciale, sans importance, ou facultative ? La bonne réponse est b, elle est cruciale. Sur un examen de plusieurs heures, avec de nombreuses questions, une mauvaise gestion du temps peut vous empêcher de terminer, et vous coûter des points faciles. Calculez votre rythme à l'avance, fixez-vous des points de contrôle, par exemple toutes les vingt-cinq questions, et gardez quelques minutes à la fin pour revenir sur les questions marquées.`,
// 18
`Cinquième et dernière question. Un plan de remédiation sert-il à consolider les acquis, à corriger les points faibles, à préparer l'examen final, ou à tout cela à la fois ? La bonne réponse est d, toutes ces réponses. Un bon plan de remédiation consolide ce que vous savez, corrige ce que vous ne maîtrisez pas encore, et vous prépare progressivement à l'examen final. Bravo pour ce travail de mi-parcours. Dans le prochain module, nous découvrirons les fondamentaux de l'agilité, et le choix d'une approche adaptative.`,
];
