module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans la semaine deux du cours MGT cent un. La semaine dernière, nous avons découvert les différents types de phrases. Cette semaine, nous allons nous intéresser à un élément central de toute phrase anglaise, le sujet. Nous verrons comment l'identifier, comment choisir entre un nom et un pronom, et surtout comment accorder correctement le verbe avec son sujet. C'est une compétence essentielle, car les erreurs d'accord sont parmi les plus fréquentes chez les apprenants.`,
// 2
`Voici les objectifs de cette semaine. Vous devrez savoir identifier le sujet d'une phrase, utiliser les noms et les pronoms sujets, et comprendre l'accord entre le sujet et le verbe. Vous apprendrez aussi à gérer les sujets composés, c'est-à-dire formés de plusieurs éléments, et à reconnaître certaines inversions entre le sujet et le verbe. Ces notions correspondent au chapitre deux de notre manuel de référence, qui traite précisément de la nature du sujet, de l'accord sujet verbe et de l'inversion.`,
// 3
`Qu'est-ce que le sujet ? Le sujet indique généralement qui réalise l'action, ou de quoi parle la phrase. Regardons trois exemples. The technician repairs the computer. Ici, c'est le technicien qui réalise l'action de réparer, the technician est donc le sujet. They install the software. Ici, le sujet est le pronom they. The network is unstable. Ici, la phrase parle du réseau, the network est donc le sujet. Pour trouver le sujet, posez-vous la question, qui fait l'action, ou de qui, de quoi parle-t-on ?`,
// 4
`Le sujet peut être un nom ou un pronom. Avec un nom, on dira par exemple, The engineer works in the laboratory. Avec un pronom, on dira, He works in the laboratory. Voici les principaux pronoms sujets. Je se dit I, tu ou vous se dit you. Il se dit he, elle se dit she. Pour une chose, il ou elle se dit it. Nous se dit we, vous au pluriel se dit you, et ils ou elles se dit they. Attention au pronom it, très utilisé en anglais technique pour parler d'un appareil ou d'un système.`,
// 5
`Voyons maintenant l'accord entre le sujet et le verbe. Au présent simple, quand le sujet est au singulier, le verbe prend un s. Par exemple, The engineer works. Quand le sujet est au pluriel, le verbe ne prend pas de s. Par exemple, The engineers work. Comparez encore, The computer works, avec The computers work. Attention, ce s à la troisième personne du singulier est une source très fréquente d'erreurs. Prenez l'habitude de vérifier systématiquement vos verbes lorsque le sujet est he, she, it, ou un nom au singulier.`,
// 6
`Certains noms demandent une attention particulière, les noms dénombrables et indénombrables. Notre manuel leur consacre d'ailleurs une section spécifique. Par exemple, on dit The information is useful, avec un verbe au singulier, car information est indénombrable en anglais. De même, on dit The equipment is expensive. En revanche, on trouve The data are available, car data est traditionnellement considéré comme un pluriel. Soyez donc attentifs, car plusieurs noms très fréquents en anglais technique ne fonctionnent pas comme les noms dénombrables ordinaires.`,
// 7
`Parlons du sujet composé. Il arrive qu'une phrase ait deux sujets, reliés par and. Par exemple, The engineer and the technician work together. Ici, le sujet est composé de deux personnes, l'ingénieur et le technicien. Le sujet est donc au pluriel, et le verbe work ne prend pas de s. C'est un point important. Même si chaque élément pris isolément est au singulier, leur réunion par and forme un sujet pluriel, et le verbe doit s'accorder en conséquence. Retenez bien cette règle simple.`,
// 8
`Terminons avec l'inversion. En anglais, l'ordre habituel est sujet puis verbe. Mais certaines structures particulières provoquent une inversion. Par exemple, Never have I seen such a complex system. Ici, la phrase commence par never, et l'auxiliaire have passe avant le sujet I. Ce type de construction permet d'insister sur une idée. L'objectif n'est pas uniquement de mémoriser ces formes, mais de comprendre que l'ordre habituel, sujet puis verbe, peut être modifié dans certaines constructions. Vous saurez ainsi les reconnaître lorsque vous les rencontrerez.`,
// 9
`Passons à l'application. Corrigez ces cinq phrases. Première phrase, The technician work every day devient The technician works every day, car le sujet est au singulier. Deuxième phrase, The engineers works together devient The engineers work together, car le sujet est au pluriel. Troisième phrase, The information are useful devient The information is useful. Quatrième phrase, The equipment are expensive devient The equipment is expensive. Et cinquième phrase, The computer and the printer is connected devient The computer and the printer are connected, car le sujet est composé.`,
];
