module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans la semaine sept du cours MGT cent un. Nous entrons aujourd'hui dans la deuxième partie du cours, intitulée construire un discours complexe. Cette semaine est consacrée à la phrase complexe. Elle correspond au chapitre six de notre manuel, qui traite des subordonnées conjonctives, infinitives, gérondives, participiales, relatives, interrogatives et exclamatives. Après avoir appris à relier des idées de même niveau, nous allons maintenant apprendre à intégrer une idée à l'intérieur d'une autre.`,
// 2
`Voici les objectifs de cette semaine. Vous devrez apprendre à construire des phrases complexes, et à utiliser les subordonnants, c'est-à-dire les mots qui introduisent une proposition subordonnée. Vous saurez aussi construire des propositions complétives, et exprimer différentes relations logiques, comme la cause, le temps, la condition ou la concession. Enfin, vous apprendrez à intégrer une proposition dans une autre. Ces compétences sont indispensables pour expliquer un fonctionnement technique ou justifier une décision. Ce sont donc des outils essentiels pour tout technicien ou ingénieur.`,
// 3
`Comparons trois types de phrases. La phrase simple ne contient qu'une seule proposition. Par exemple, The system works. La phrase composée relie deux propositions de même niveau, avec une conjonction de coordination. Par exemple, The system works, and the users are satisfied. La phrase complexe, elle, contient une proposition principale et une proposition subordonnée, qui dépend de la première. Par exemple, The users are satisfied because the system works well. Ici, because the system works well explique la satisfaction des utilisateurs.`,
// 4
`Les subordonnants sont les mots qui introduisent une proposition subordonnée. En voici quelques exemples essentiels. Because exprime la cause. Although exprime la concession. When, while, before, after et since expriment le temps. Et if et unless expriment la condition. Unless signifie à moins que. Chaque subordonnant exprime une relation logique précise entre deux idées. Apprendre à les choisir correctement vous permettra de rédiger des explications techniques claires, où les liens entre les faits sont parfaitement explicites. Nous allons maintenant les voir un par un.`,
// 5
`Voyons comment exprimer la cause. On utilise très souvent because. Par exemple, The system stopped because the power failed. Le système s'est arrêté parce que l'alimentation est tombée en panne. La proposition principale, The system stopped, décrit le fait. La proposition subordonnée, because the power failed, en donne la cause. Ce type de phrase est très fréquent dans les rapports d'incident, où il faut expliquer précisément l'origine d'une panne ou d'un dysfonctionnement. Notez aussi que la subordonnée peut se placer en début de phrase, suivie d'une virgule.`,
// 6
`Passons à la condition. On l'exprime le plus souvent avec if. Par exemple, If the temperature increases, the system will stop. Si la température augmente, le système s'arrêtera. Remarquez la construction. Dans la proposition avec if, on utilise le présent, the temperature increases. Et dans la proposition principale, on utilise le futur avec will, the system will stop. Attention à ne pas mettre will après if, comme on serait tenté de le faire en traduisant du français. Cette structure est très utile pour décrire des procédures et des consignes.`,
// 7
`Voyons maintenant la concession. Elle permet d'exprimer une opposition entre deux idées. On utilise souvent although. Par exemple, Although the device is old, it is still reliable. Bien que l'appareil soit ancien, il reste fiable. La proposition introduite par although présente un fait qui pourrait sembler négatif, et la proposition principale le nuance. Cette construction est précieuse pour présenter une évaluation équilibrée d'un équipement, en reconnaissant ses limites tout en soulignant ses qualités. Vous pouvez aussi utiliser even though, qui renforce l'opposition.`,
// 8
`Terminons avec la proposition complétive. Elle complète le sens d'un verbe, souvent un verbe d'opinion ou de déclaration. Par exemple, The engineer believes that the system is reliable. L'ingénieur pense que le système est fiable. Ici, that the system is reliable complète le verbe believes. Retenez une particularité de l'anglais. Le mot that peut être présent, ou omis dans certaines structures. On pourrait aussi dire, The engineer believes the system is reliable. Les deux formes sont correctes, la seconde étant plus courante à l'oral.`,
];
