module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans ce quatrième jour de formation. Nous sommes le jeudi premier octobre deux mille vingt-six, et nous commençons avec le Module dix, consacré à l'animation des communautés numériques, pour une durée de deux heures. Ce module est animé par votre formateur principal, Pawou Batana, pour les Institutions et Fonds membres du RAFPRO, avec l'appui de la FNAFPP. Jusqu'ici, nous avons surtout parlé de produire et de diffuser. Aujourd'hui, nous allons parler de relation, c'est-à-dire de la manière dont une institution écoute ses publics et leur répond.`,
// 2
`Au Module neuf, vous avez appris à organiser la production et la diffusion des contenus. Mais une publication ne marque pas la fin du travail de communication. Après sa diffusion, elle peut susciter des questions, des demandes de précision, des témoignages, des suggestions, des réactions positives, des demandes d'accompagnement, ou des commentaires qui appellent une réponse. Retenez cette distinction. Publier est une action de diffusion, tandis qu'animer une communauté est un travail de relation. Une institution doit donc prévoir non seulement ce qu'elle publie, mais aussi la manière dont elle écoute et répond.`,
// 3
`À l'issue de ce module, vous saurez expliquer les principes du community management institutionnel, et distinguer diffusion, interaction et engagement. Vous saurez proposer des actions qui favorisent une participation utile, et répondre aux questions et sollicitations courantes. Vous saurez aussi adapter le ton et le canal de réponse, orienter les demandes vers les services compétents, organiser le suivi des interactions, et identifier les pratiques qui construisent une relation durable avec vos publics. Le résultat attendu est clair. Gérer une interaction numérique courante sans improvisation, avec professionnalisme et cohérence institutionnelle.`,
// 4
`Qu'est-ce que le community management institutionnel ? C'est l'ensemble des activités qui animent les espaces numériques d'une institution, et entretiennent des échanges professionnels avec ses publics. Il comprend l'écoute des communautés, la publication de contenus utiles, l'encouragement des interactions, la réponse aux questions, l'orientation des sollicitations, le suivi des demandes, et la remontée des informations utiles aux services concernés. Il ne se limite donc ni à publier, ni à rechercher des réactions. Retenez ce message clé. Le community manager représente l'institution dans une relation numérique continue avec ses publics.`,
// 5
`Une institution de formation professionnelle n'interagit pas avec ses publics comme une marque de divertissement. Ses communications portent sur des programmes et dispositifs, des conditions de participation, des procédures, des échéances, des informations administratives, des partenariats et des résultats documentés. La conséquence est importante. Une réponse imprécise peut entraîner une mauvaise compréhension d'une démarche ou d'une échéance, avec des effets concrets pour les bénéficiaires. C'est pourquoi le communicant doit privilégier l'exactitude, la clarté, la traçabilité, et l'orientation vers la source compétente.`,
// 6
`L'animateur de communauté exerce cinq missions. Écouter, pour savoir ce que disent et demandent les publics. Informer, en apportant une information fiable et utile. Dialoguer, en répondant avec clarté et respect. Orienter, en identifiant le service capable de traiter la demande. Et suivre, en vérifiant que la sollicitation a reçu une suite appropriée. Ces missions s'exercent dans le respect de la ligne éditoriale, des responsabilités internes et des règles de confidentialité. Retenez qu'une réponse utile peut parfois consister à bien orienter, plutôt qu'à donner immédiatement une réponse définitive.`,
// 7
`Faisons un exercice d'ouverture. Une institution annonce sur Facebook l'ouverture d'un programme de formation. Dans les deux heures, elle reçoit quinze réactions, quatre commentaires de félicitations, six questions sur les conditions de participation, deux demandes de contact, et une suggestion sur les horaires. Réfléchissez. Quelles interactions appellent une réponse ? Quelles informations doivent être vérifiées ? Quelles demandes nécessitent une orientation ? Et que peut-on apprendre de ces réactions pour les prochaines publications ? Vous le constaterez, toutes les interactions ne se traitent pas de la même manière, mais toutes peuvent être instructives.`,
// 8
`Qu'est-ce que l'engagement ? Ce sont les interactions des publics avec les contenus et les espaces numériques de l'institution. Il peut prendre la forme de commentaires, de réponses à une question, de partages, de messages privés, de participations à une discussion, de demandes d'information, ou de contributions utiles. Mais attention. Une réaction ne signifie pas forcément que le public a compris l'information, ni qu'il a accompli la démarche attendue. Pour une institution, la qualité et l'utilité des interactions comptent donc autant que leur volume.`,
// 9
`On peut distinguer trois niveaux de participation. La réaction, par exemple lorsqu'un internaute aime une publication. Elle indique que le contenu a suscité une réaction. L'interaction, lorsqu'un internaute pose une question. Elle indique que le contenu ouvre un échange. Et la contribution, lorsqu'un bénéficiaire formule une suggestion précise. Le public apporte alors une information ou une expérience exploitable. Attention, ce n'est pas une échelle de valeur universelle. Une simple demande d'information peut être très importante si elle révèle une difficulté récurrente. Quels types d'interactions sont les plus utiles pour votre institution ?`,
// 10
`Pourquoi les publics interagissent-ils ? Ils peuvent chercher à obtenir une information, vérifier qu'ils ont bien compris, demander une précision, partager une expérience, exprimer une satisfaction, proposer une amélioration, entrer en contact avec un service, ou signaler une difficulté. Le principe est donc le suivant. Avant de répondre, identifiez le besoin réel derrière le message. Par exemple, un internaute écrit qu'il n'arrive pas à s'inscrire. Cela peut être une difficulté technique, une incompréhension de la procédure, ou une condition d'accès non remplie. Il faut clarifier avant de conclure.`,
// 11
`Quels sont les leviers d'un engagement institutionnel utile ? La pertinence, en publiant des informations qui répondent aux préoccupations des publics. La clarté, en rendant les messages compréhensibles et les démarches faciles à identifier. La régularité, en maintenant une présence cohérente avec vos moyens. La réactivité organisée, en accusant réception des demandes et en assurant leur suivi. L'écoute, en tenant compte des questions récurrentes et des retours d'expérience. Et la continuité, en n'abandonnant jamais une conversation qui attend une réponse. L'engagement durable repose sur l'utilité et la confiance.`,
// 12
`Une publication peut être conçue pour ouvrir un dialogue. Elle peut inviter le public à poser une question sur un programme, à indiquer un sujet qu'il souhaite voir expliqué, à consulter une ressource, à participer à une séance d'information, ou à partager une expérience lorsque c'est approprié. Par exemple, vous souhaitez mieux comprendre les étapes de candidature ? Consultez la notice officielle, et posez vos questions générales en commentaire, notre équipe vous orientera. Une précaution essentielle. Ne demandez jamais aux internautes de publier des données personnelles ou des dossiers en commentaire.`,
// 13
`Évitez l'engagement artificiel. Certaines pratiques génèrent des réactions sans apporter de valeur, comme les questions sans rapport avec la mission, les sollicitations répétitives, les promesses exagérées, les concours sans objectif pertinent, les publications conçues uniquement pour provoquer, ou les réponses automatiques inadaptées. Comparez deux formulations. Commentez oui cent fois si vous aimez notre institution, cela n'apporte rien au public. En revanche, quel aspect de la procédure souhaitez-vous voir expliqué dans notre prochaine publication, voilà une question qui aide à identifier un besoin réel.`,
// 14
`L'animation ne doit pas dépendre uniquement des campagnes ponctuelles. Une institution peut entretenir la relation grâce à des réponses régulières aux questions, des informations pratiques actualisées, des contenus explicatifs, des comptes rendus d'activités validés, des rendez-vous éditoriaux, une prise en compte des suggestions, et un suivi des demandes restées sans réponse. Par exemple, vous pouvez publier chaque semaine une réponse à une question fréquente, à condition que l'information soit vérifiée et toujours valable. Retenez qu'une communauté durable se construit par la fiabilité des échanges successifs.`,
// 15
`Passons maintenant à la réponse. Une réponse institutionnelle professionnelle doit être exacte, c'est-à-dire fondée sur une information vérifiée. Claire, donc compréhensible par le destinataire. Respectueuse, sans condescendance ni agressivité. Adaptée à la question et au canal. Utile, car elle répond, oriente ou précise la prochaine étape. Et traçable, car les demandes nécessitant un suivi sont enregistrées selon les procédures internes. Retenez bien ceci. La courtoisie ne suffit pas si la réponse ne permet pas au public d'avancer dans sa démarche.`,
// 16
`Voici une méthode pédagogique pour structurer vos réponses, la méthode RÉPONDRE. R, reconnaître, en accusant réception de la demande. É, éclaircir, en identifiant précisément le besoin. P, puiser dans la source, en vérifiant l'information officielle. O, orienter, en donnant la réponse ou en dirigeant vers le bon service. N, ne pas exposer les données personnelles. D, définir la suite, en indiquant la prochaine étape. R, réexaminer si un suivi est nécessaire. Et E, enregistrer une trace selon les règles internes. Précisons que c'est un outil de formation, et non une procédure officielle du FNAFPP.`,
// 17
`Le ton doit s'adapter à chaque interaction. Face à des félicitations, soyez chaleureux et sobre. Face à une question pratique, clair et précis. Face à une demande de clarification, pédagogique. Face à une suggestion, ouvert et reconnaissant. Face à une difficulté signalée, attentif et orienté vers une solution. Et face à une demande hors compétence, respectueux et explicite sur l'orientation. Par exemple, à un internaute qui remercie pour une formation, on peut répondre, merci pour votre retour, nous sommes heureux que cette formation vous ait été utile. Sans transformer la réponse en message publicitaire.`,
// 18
`Voyons comment répondre à une question simple. Un internaute demande où trouver les informations sur le programme. Une réponse insuffisante serait, regardez notre site. Une réponse plus utile serait plutôt celle-ci. Bonjour, merci pour votre intérêt. Les informations détaillées figurent dans la notice officielle, accessible depuis notre site. Si vous ne la retrouvez pas, indiquez-nous le nom du programme afin que nous puissions vous orienter. Pourquoi est-ce mieux ? Parce que cette réponse reconnaît la demande, identifie une source de référence, propose une aide complémentaire, et n'invente aucune condition.`,
// 19
`Que faire lorsque vous ne connaissez pas la réponse ? La mauvaise pratique serait de deviner une condition, une date ou une décision pour répondre vite. Répondez plutôt ainsi. Bonjour, merci pour votre question. Nous vérifions ce point auprès du service compétent, et nous reviendrons vers vous dès que la réponse aura été confirmée. En interne, identifiez le service compétent, transmettez la question, enregistrez la demande, suivez la réponse, puis répondez à l'internaute après vérification. Retenez ce principe. Une réponse différée et exacte vaut mieux qu'une réponse immédiate et incertaine.`,
// 20
`Faut-il répondre publiquement ou en message privé ? La réponse publique convient lorsque la question et la réponse sont générales, et peuvent être utiles à d'autres internautes. Par exemple, pour une question sur la date limite, répondez publiquement si la date est officiellement confirmée. Le message privé convient lorsque le traitement exige des éléments individuels. Si quelqu'un publie son numéro de dossier et sa pièce d'identité, ne reprenez jamais ces données, orientez-le vers un canal officiel sécurisé, et appliquez la procédure de protection prévue. Et le passage en privé ne dispense jamais des exigences de confidentialité.`,
// 21
`Orienter ne signifie pas abandonner la demande. Une orientation efficace comprend trois éléments. Le bon interlocuteur, c'est-à-dire le service ou le canal officiel compétent. La prochaine étape, c'est-à-dire ce que l'usager doit faire. Et le suivi, ce que l'équipe de communication doit vérifier lorsque cela relève de sa responsabilité. Par exemple, cette demande nécessite l'examen de votre dossier par le service des candidatures, merci de le contacter par le canal officiel, et évitez de transmettre votre dossier en public. Attention, ne promettez jamais une décision ou un délai que vous ne maîtrisez pas.`,
// 22
`Les questions fréquentes sont une mine d'informations. Elles peuvent révéler une information difficile à trouver, une procédure mal expliquée, un message ambigu, un besoin de contenu complémentaire, ou un problème d'orientation. La méthode est simple. Repérez la question, vérifiez la réponse, faites-la valider, créez une fiche de questions fréquentes, puis publiez. Par exemple, si beaucoup de personnes demandent les pièces à fournir, préparez une publication qui renvoie vers la liste officielle à jour. Et vous faites ainsi le lien avec le Module neuf, car ces besoins observés doivent alimenter votre calendrier éditorial.`,
// 23
`Place maintenant à l'atelier. Votre mission est de formuler des réponses institutionnelles appropriées. En groupes, vous travaillerez sur des situations inspirées d'interactions courantes. Pour chaque situation, identifiez le besoin de l'internaute, déterminez les informations à vérifier, choisissez le canal de réponse, rédigez la réponse, précisez l'éventuelle orientation interne, et définissez l'action de suivi. Votre livrable est une fiche de traitement et une réponse rédigée pour chaque cas. Et si un cas présente un risque sensible, signalez-le, car il sera approfondi au Module onze.`,
// 24
`Premier cas, une demande d'information générale. Sous l'annonce d'un programme destiné aux responsables de PME, un internaute demande si la formation concerne aussi les petites entreprises qui viennent de démarrer. Votre travail est d'identifier l'information manquante, d'éviter de supposer une condition d'éligibilité, de rédiger une réponse utile, et de proposer une source de vérification. Voici une réponse possible. Merci pour votre intérêt. Les conditions de participation figurent dans la notice officielle, que nous vous invitons à consulter. Si un point reste peu clair, nous pouvons vous orienter vers le service des candidatures.`,
// 25
`Deuxième cas, une question récurrente. Plusieurs internautes demandent où télécharger le formulaire de candidature, et l'un d'eux écrit qu'il ne le trouve pas. Votre travail comporte deux volets. D'abord, rédiger une réponse individuelle, par exemple en remerciant la personne, en donnant le lien vérifié vers la page officielle, et en l'invitant à préciser où elle est bloquée, sans publier de données personnelles. Ensuite, identifier une action collective pour éviter que la difficulté se répète. Ici, il s'agit de vérifier la visibilité du formulaire et, si nécessaire, de préparer une publication explicative.`,
// 26
`Troisième cas, une suggestion d'un bénéficiaire. Un internaute trouve les séances d'information intéressantes, mais explique que certaines personnes ne peuvent pas se libérer en journée, et propose un créneau en fin d'après-midi. Votre réponse doit reconnaître la suggestion, éviter de promettre un changement non décidé, et prévoir une remontée au service compétent. Par exemple, merci pour cette suggestion, nous la transmettons à l'équipe chargée de l'organisation, et d'éventuelles modifications seront annoncées sur nos canaux officiels après confirmation. Retenez qu'écouter une suggestion ne veut pas dire annoncer son adoption.`,
// 27
`Quatrième cas, un message positif. Un participant écrit qu'il a assisté à la dernière séance d'information, que les explications étaient très claires, et il remercie l'équipe. Rédigez une réponse courtoise, brève, personnalisée, sans exagération. Par exemple, merci pour votre retour, nous sommes heureux que les explications vous aient été utiles, et votre message sera partagé avec l'équipe concernée. Une précaution importante. N'utilisez pas ce témoignage à d'autres fins sans autorisation appropriée. Un message positif mérite une réponse authentique, et pas une formule promotionnelle.`,
// 28
`Cinquième cas, une demande individuelle publiée en commentaire. Un internaute publie son numéro de dossier, son téléphone et sa pièce d'identité, et demande qu'on vérifie sa candidature. Votre travail est d'identifier le risque de confidentialité, d'éviter de reprendre ces données, d'orienter vers le canal approprié, et de signaler le commentaire selon la procédure interne. Par exemple, pour protéger vos informations, nous vous invitons à ne pas publier de documents en commentaire. Le suivi individuel s'effectue par le canal officiel prévu. L'animation professionnelle inclut aussi la protection des informations confiées.`,
// 29
`Sixième cas, une question sans réponse immédiate. Un internaute demande si la date de clôture sera prolongée, alors qu'aucune décision officielle n'a été communiquée à l'équipe. Votre réponse doit distinguer clairement ce qui est confirmé, ce qui ne l'est pas, et la source à suivre. Par exemple, à ce jour, aucune prolongation ne nous a été officiellement confirmée. Nous vous invitons à vous référer à la date indiquée dans l'avis en vigueur, et toute modification sera annoncée sur nos canaux officiels. Retenez le point essentiel. Ne présentez jamais une simple possibilité comme une décision.`,
// 30
`Pour documenter vos réponses, utilisez la fiche de traitement des interactions. Elle comprend la référence du cas, le type d'interaction, le besoin principal, les informations à vérifier, le canal retenu, la réponse proposée, le service à solliciter, l'action de suivi, et le risque éventuel. Remplir cette fiche vous oblige à réfléchir avant de répondre, et laisse une trace utile à toute l'équipe. Une consigne importante. Lorsque la situation dépasse une interaction courante, précisez pourquoi elle doit être transmise à une personne habilitée.`,
// 31
`Passons à la restitution. Chaque groupe présente une ou deux situations, et je poserai sept questions. La réponse traite-t-elle réellement la question ? L'information est-elle vérifiée ? Le ton est-il professionnel ? Le canal est-il approprié ? La confidentialité est-elle respectée ? Une orientation est-elle nécessaire ? Et le suivi est-il clairement prévu ? Vous verrez que plusieurs formulations peuvent être acceptables, si elles respectent les mêmes exigences de fond. Vos réponses corrigées et vos fiches formeront une première base de réponses types, à adapter et à faire valider dans votre institution.`,
// 32
`Voici la grille d'évaluation de vos réponses, qui traduit les exigences du R A sept. Elle porte sur dix critères. La compréhension du besoin réel, et l'exactitude, sans aucune information inventée. La pertinence face à la situation, et un ton professionnel et respectueux. La clarté de la prochaine étape, et le bon choix entre public et privé. L'orientation vers le service compétent si nécessaire, et la confidentialité des données. Le suivi lorsque la demande l'exige. Et enfin la maîtrise du risque, en signalant les situations qui dépassent le périmètre du communicant.`,
// 33
`Vérifions notre compréhension avec cinq questions. Un, quelle différence entre publier et animer ? Publier, c'est diffuser. Animer, c'est aussi écouter, dialoguer, orienter et suivre. Deux, beaucoup de réactions prouvent-elles un engagement utile ? Non, il faut examiner leur nature et leur contribution aux objectifs. Trois, que faire si l'on ignore la réponse ? Reconnaître la demande, vérifier auprès du service compétent, et assurer un suivi. Quatre, quand privilégier un canal individuel ? Quand la demande exige des informations personnelles. Et cinq, comment les interactions améliorent-elles le calendrier ? Les questions récurrentes inspirent de nouveaux contenus.`,
// 34
`Pour conclure, voici les dix principes à retenir. Une publication ouvre une conversation, et le community management repose sur l'écoute et le service. L'engagement utile ne se résume pas au nombre de réactions. Chaque interaction doit être comprise avant d'être traitée, et chaque réponse doit être exacte, claire et respectueuse. On n'invente jamais une information non confirmée, et on n'expose jamais les données personnelles. Une orientation indique une étape concrète, les questions récurrentes nourrissent les contenus, et les situations sensibles sont transmises. Écouter, comprendre, vérifier, répondre, suivre, améliorer. Merci à toutes et à tous.`,
];
