module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le chapitre six du cours DSC trois cent quarante-cinq. Ce chapitre est consacré à la synthèse et à la révision, en vue de l'examen de mi-parcours. Nous ne verrons pas de nouvel algorithme aujourd'hui. Nous allons plutôt relier entre eux les cinq premiers chapitres, revoir les notions essentielles, et identifier les compétences que l'examen attendra de vous. L'objectif est que vous abordiez cette évaluation avec une vision claire, structurée et transversale du cours.`,
// 2
`Voici les objectifs de ce chapitre. Premièrement, consolider les acquis des cinq premiers chapitres du cours. Deuxièmement, structurer une stratégie de révision efficace, plutôt que de relire passivement vos notes. Et troisièmement, vous entraîner à mobiliser les concepts de façon transversale, plutôt que chapitre par chapitre. C'est exactement ce qu'on attend d'un data scientist. Face à un problème réel, personne ne vous dira dans quel chapitre chercher la solution. C'est à vous de relier les notions entre elles. Allons-y. Commençons.`,
// 3
`Voici le périmètre de l'examen de mi-parcours, sous forme de carte mentale. Il porte sur l'ensemble des contenus suivants. L'introduction au Machine Learning et le cycle de vie d'un projet. Les rappels statistiques et la préparation des données. La régression linéaire et la régularisation. La classification par arbres de décision et par k plus proches voisins. Et enfin les notions transversales d'évaluation et de validation des modèles, que l'on retrouve dans tous les chapitres. Reprenons maintenant chaque semaine en quelques mots.`,
// 4
`Semaine un, les fondements. Retenez d'abord les trois familles d'apprentissage. L'apprentissage supervisé, avec des données étiquetées, pour la régression et la classification. L'apprentissage non supervisé, sans étiquette, pour découvrir des structures. Et l'apprentissage par renforcement, où un agent apprend par essais, récompenses et pénalités. Retenez ensuite le cycle de vie d'un projet en huit étapes, du cadrage du problème métier jusqu'au suivi du modèle en production, en passant par la collecte, la préparation, l'exploration, la modélisation, l'évaluation et le déploiement.`,
// 5
`Semaine deux, les données. Retenez les distributions clés, la loi normale, pour les phénomènes continus autour d'une moyenne, et la loi de Bernoulli, pour les résultats binaires. Retenez ensuite les étapes du prétraitement. Le traitement des valeurs manquantes, par suppression ou imputation. L'encodage des variables catégorielles, one-hot ou ordinal. La standardisation et la normalisation des variables. Et l'analyse exploratoire des données, qui guide tous les choix ultérieurs. Ces étapes conditionnent directement la qualité de vos modèles. Révisez-les bien. Ne les négligez pas.`,
// 6
`Semaine trois, la régression. Retenez la régression linéaire multivariée, qui prédit une cible continue par une combinaison linéaire pondérée des variables, avec des coefficients estimés par les moindres carrés. Retenez les métriques, le MSE, le RMSE, qui s'exprime dans l'unité de la cible, et le R deux, qui mesure la part de variance expliquée. Et retenez la distinction entre sous-apprentissage, avec une erreur élevée partout, et surapprentissage, avec une erreur faible à l'entraînement mais élevée sur de nouvelles données. Allons-y.`,
// 7
`Semaine quatre, la régularisation. Retenez les trois méthodes. Ridge, ou L deux, rétrécit les coefficients sans jamais les annuler. Lasso, ou L un, peut annuler certains coefficients, et réalise ainsi une sélection automatique des variables. Elastic Net combine les deux, et convient particulièrement aux groupes de variables corrélées. Enfin, retenez que le paramètre alpha, qui règle la force de la régularisation, se choisit toujours par validation croisée. Trop faible, il est inutile, trop fort, il provoque du sous-apprentissage. Retenez-le. Gardez-le en tête.`,
// 8
`Semaine cinq, la classification. Pour les arbres de décision, retenez les critères de pureté, Gini et entropie, et l'élagage, qui limite le surapprentissage. Pour le k-NN, retenez la notion de distance, le choix de k par validation croisée, et la malédiction de la dimensionnalité. Enfin, pour l'évaluation, retenez la matrice de confusion, la précision, le rappel et le F un score. Sachez les calculer à partir d'une matrice chiffrée, et surtout savoir laquelle privilégier selon le coût des erreurs. Entraînez-vous.`,
// 9
`Voici une notion transversale à maîtriser absolument, le compromis biais variance. Un modèle trop simple a un biais élevé, c'est le sous-apprentissage. Un modèle trop complexe a une variance élevée, c'est le surapprentissage. Or, toutes les techniques que nous avons vues visent à trouver le meilleur compromis. La régularisation de Ridge et de Lasso, l'élagage des arbres, le choix de k dans le k-NN. Si vous comprenez ce compromis, vous comprenez la logique profonde de tout le cours. C'est essentiel.`,
// 10
`Deuxième notion transversale, la validation croisée. Un simple découpage entre entraînement et test donne une estimation fragile, qui dépend beaucoup du hasard du découpage. La validation croisée à k blocs, ou k-fold, découpe les données en k parties. On entraîne le modèle k fois, en utilisant à chaque fois une partie différente comme jeu de test, puis on fait la moyenne des performances. On obtient ainsi une estimation bien plus fiable de la capacité de généralisation. C'est aussi l'outil de réglage des hyperparamètres.`,
// 11
`Retenons les points clés pour l'examen. Toujours relier une technique à son objectif, réduire le biais, réduire la variance, ou sélectionner des variables. Savoir passer d'un problème métier à la bonne famille d'algorithmes, régression ou classification, supervisé ou non supervisé. Savoir calculer et interpréter le MSE, le RMSE, le R deux, la précision, le rappel et le F un score à partir de données chiffrées. Et savoir justifier un choix de régularisation ou d'algorithme selon le contexte des données. Bonne révision.`,
// 12
`Premier exercice, réalisez votre propre carte mentale des cinq premiers chapitres. Faites apparaître au moins une flèche entre deux chapitres différents. Par exemple, une flèche de la régularisation, au chapitre quatre, vers le surapprentissage, vu au chapitre trois, car la régularisation sert justement à le réduire. Autre exemple, une flèche de la standardisation, au chapitre deux, vers le k-NN, au chapitre cinq, car les distances exigent des variables à la même échelle. Plus votre carte contient de liens, mieux vous êtes préparés.`,
// 13
`Deuxième exercice, choisissez un jeu de données que vous connaissez, personnel, professionnel ou académique, et déterminez quel algorithme du cours vous semble le plus adapté. Voici la démarche. Identifiez d'abord la cible. Est-elle numérique, c'est une régression, ou catégorielle, c'est une classification ? Regardez ensuite le nombre de variables, leurs corrélations, et le besoin d'interprétation. Par exemple, pour prédire des ventes avec de nombreuses variables corrélées, une régression Ridge ou Elastic Net serait un bon choix, que vous justifierez. Justifiez toujours.`,
// 14
`Troisième exercice, rédigez en cinq lignes une réponse type à la question, expliquez le compromis biais variance. Voici une piste. Le biais est l'erreur due à un modèle trop simple, la variance la sensibilité d'un modèle trop complexe aux données d'entraînement. Réduire l'un augmente souvent l'autre. Exemple du cours, dans le k-NN, un k égal à un a une variance élevée et surapprend, tandis qu'un k très grand a un biais élevé et sous-apprend. Le bon k, choisi par validation croisée, équilibre les deux.`,
// 15
`Dernier exercice, et appel à l'action. Refaites, sans regarder vos notes, les points clés des chapitres un à cinq. Écrivez-les sur une feuille, puis vérifiez vos réponses avec les résumés de chaque chapitre. Ce que vous ne retrouvez pas seul, c'est ce qu'il faut réviser en priorité. Cette méthode, appelée rappel actif, est l'une des plus efficaces pour mémoriser durablement. Bonne révision à toutes et à tous, et bon courage pour l'examen de mi-parcours. Vous êtes prêts. Courage. À bientôt.`,
];
