module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans la séance dix, la dernière séance du cours CMNS deux cent un. Elle est consacrée à l'éthique, à la gestion de crise et à la responsabilité. Ces trois thèmes sont au coeur de la confiance qu'une organisation inspire. Une communication habile mais malhonnête finit toujours par se retourner contre son auteur. À l'inverse, une communication éthique, responsable et bien préparée face aux crises protège durablement la réputation. Terminons ce cours en beauté.`,
// 2
`Cette séance poursuit quatre objectifs. D'abord, comprendre les enjeux éthiques de la communication professionnelle. Ensuite, savoir gérer une crise, et communiquer efficacement lorsque tout va mal. Puis, intégrer la responsabilité sociale dans la communication de l'organisation. Et enfin, analyser le cycle de vie d'un projet de communication, de sa conception jusqu'à son évaluation. Ce dernier chapitre fera la synthèse de nombreuses notions vues tout au long du cours. Commençons par l'éthique de la communication. Ce sera notre dernière étape ensemble, alors restez bien attentifs.`,
// 3
`Le premier chapitre porte sur l'éthique de la communication. L'éthique de la communication est l'ensemble des principes et des valeurs qui guident nos comportements lorsque nous communiquons. Elle répond à une question simple, mais exigeante. Est-ce que ce que je dis, et la façon dont je le dis, est juste et honnête ? L'éthique est essentielle pour la crédibilité et la confiance. Sans elle, même le message le mieux construit perd sa valeur dès que la vérité éclate. Voyons comment la définir.`,
// 4
`Définissons-la. L'éthique de la communication est l'application des principes moraux à la communication professionnelle. Elle vise à assurer quatre choses. L'honnêteté des messages. La transparence envers les interlocuteurs. Le respect des personnes. Et la responsabilité de celui qui communique. Concrètement, cela signifie par exemple ne pas embellir les résultats d'un projet dans un rapport, ne pas cacher un problème à un partenaire, et ne pas utiliser un ton humiliant envers un collaborateur. Ce sont des exigences simples, mais exigeantes au quotidien.`,
// 5
`L'éthique de la communication repose sur cinq principes. L'honnêteté, ne pas mentir. La transparence, ne pas cacher les informations importantes. Le respect, ne pas blesser, ni humilier. La responsabilité, assumer ses actes et ses paroles, y compris ses erreurs. Et l'équité, ne pas discriminer, et traiter chacun avec justice. Ces cinq principes sont simples à énoncer. Mais les appliquer au quotidien, notamment sous la pression des résultats, demande du courage et de la constance. Ils devraient guider chacun de vos messages.`,
// 6
`Plusieurs enjeux éthiques se posent dans la communication professionnelle. La confidentialité, c'est-à-dire protéger les informations sensibles. La protection des données, notamment personnelles. La propriété intellectuelle, en respectant le travail et les créations des autres, et en citant ses sources. Les conflits d'intérêts, lorsque l'intérêt personnel risque de l'emporter sur celui de l'organisation. Et la corruption, qui détruit la confiance et la crédibilité. Chacun de ces enjeux peut se présenter dans votre vie professionnelle. Voyons maintenant les situations plus délicates. Soyez vigilants.`,
// 7
`Parfois, l'éthique n'est pas simple, car deux valeurs entrent en conflit. On parle alors de dilemme éthique. Par exemple, la transparence peut entrer en conflit avec la confidentialité. Faut-il informer tout le personnel d'une restructuration en préparation, au risque de créer de l'inquiétude, ou garder le secret jusqu'à la décision finale ? Il n'existe pas toujours de réponse parfaite. Mais il faut prendre le temps de réfléchir, de peser les conséquences, et de pouvoir justifier son choix. La réflexion vaut mieux que le réflexe.`,
// 8
`Voici quatre bonnes pratiques éthiques. La réflexion éthique, qui consiste à se demander, avant de communiquer, si le message est honnête et respectueux. La consultation des parties prenantes, pour comprendre les conséquences d'une décision sur chacune d'elles. La transparence, en expliquant ses choix. Et la responsabilité, en assumant ses erreurs. Un test simple, demandez-vous si vous seriez à l'aise que votre message soit publié dans la presse. Si la réponse est non, réfléchissez encore. Ce test simple est très efficace.`,
// 9
`Voyons des exemples togolais. Le ProMAT applique l'éthique par la transparence dans ses rapports, le respect de ses engagements, et la protection des données des bénéficiaires. Le programme CIZO communique honnêtement avec les communautés, applique des critères de sélection transparents pour choisir les bénéficiaires, et respecte ses engagements. Enfin, les entreprises togolaises intègrent de plus en plus l'éthique, grâce à des chartes éthiques, à la formation de leurs employés, et à des mécanismes de signalement des abus. Ce sont de belles pratiques à suivre.`,
// 10
`Faisons la synthèse du chapitre. L'éthique de la communication repose sur cinq principes, l'honnêteté, la transparence, le respect, la responsabilité et l'équité. Ses enjeux incluent la confidentialité, la protection des données, la propriété intellectuelle, les conflits d'intérêts et la corruption. Et ses bonnes pratiques incluent la réflexion éthique, la consultation, la transparence et la responsabilité. Retenez que l'éthique n'est pas un frein à la communication. C'est au contraire la condition de sa crédibilité. Passons à la gestion de crise. Allons-y.`,
// 11
`Voici les réponses au quiz. Qu'est-ce que l'éthique de la communication ? C'est l'application des principes moraux à la communication professionnelle, pour garantir l'honnêteté, la transparence, le respect et la responsabilité. Quels sont les principes éthiques ? L'honnêteté, la transparence, le respect, la responsabilité et l'équité. Et quels sont les enjeux éthiques ? La confidentialité, la protection des données, la propriété intellectuelle, les conflits d'intérêts et la corruption. Bravo si vous aviez tout juste. Retenez bien ces listes. Merci à vous.`,
// 12
`Passons au deuxième chapitre, consacré à la gestion de crise. La gestion de crise est l'ensemble des actions mises en oeuvre pour faire face à une crise, et en limiter les conséquences. Toute organisation, un jour ou l'autre, traverse une crise. La différence se fait dans la préparation et dans la réaction. Et au coeur de cette réaction se trouve la communication de crise. Une crise bien gérée peut même renforcer la confiance, tandis qu'une crise mal communiquée peut ruiner une réputation.`,
// 13
`Définissons la crise. Une crise est un événement soudain et imprévu, qui menace l'organisation, sa réputation ou ses parties prenantes. Elle se caractérise par l'urgence, l'incertitude, et une forte pression, notamment médiatique. Elle exige une réponse rapide et coordonnée. Dans une crise, chaque heure compte. Une organisation qui tarde à réagir laisse les rumeurs et les critiques occuper l'espace, et il devient alors beaucoup plus difficile de rétablir les faits et la confiance. La rapidité est donc capitale. Retenez-le bien.`,
// 14
`On distingue cinq types de crises. Les crises naturelles, comme les inondations, les sécheresses ou les tempêtes. Les crises technologiques, comme une panne majeure ou un accident industriel. Les crises sanitaires, comme les épidémies ou les pandémies. Les crises financières, comme une perte importante ou une faillite. Et les crises de réputation, comme un scandale ou une polémique sur les réseaux sociaux. Chaque type a ses spécificités, mais les principes de gestion restent largement les mêmes. Aucune organisation n'est totalement à l'abri.`,
// 15
`La gestion de crise suit cinq phases. La prévention, qui consiste à anticiper les risques. La préparation, qui consiste à planifier la réponse, avec une cellule de crise, des porte-parole désignés et des messages préparés. La réponse, qui consiste à agir rapidement lorsque la crise survient. Le rétablissement, qui consiste à reconstruire, et à revenir à une situation normale. Et l'apprentissage, qui consiste à tirer les leçons de la crise. Retenez ces cinq verbes, anticiper, planifier, agir, reconstruire et apprendre.`,
// 16
`La communication de crise est l'ensemble des actions de communication menées pendant une crise. Elle poursuit quatre objectifs. Informer, en donnant des informations exactes sur la situation. Rassurer, en montrant que la situation est prise en main. Maintenir la confiance des parties prenantes, des employés, des clients et des partenaires. Et protéger la réputation de l'organisation. Elle s'adresse à tous les publics à la fois, en interne comme en externe, avec des messages cohérents entre eux. Elle se prépare bien avant la crise.`,
// 17
`La communication de crise repose sur cinq principes. La rapidité, communiquer vite, même si toutes les informations ne sont pas encore connues. La transparence, dire la vérité, y compris sur ce que l'on ignore. La cohérence, avec des messages alignés entre tous les porte-parole. L'empathie, en montrant de la compassion envers les personnes touchées. Et l'action, en montrant concrètement ce qui est fait pour résoudre la crise. L'empathie passe toujours avant la défense de l'organisation. Ces principes sont votre boussole dans la tempête.`,
// 18
`Voici cinq erreurs à éviter absolument. Le silence, qui laisse la place aux rumeurs, et donne l'impression que l'on cache quelque chose. Le déni, qui consiste à nier un problème évident. La minimisation, qui consiste à sous-estimer la gravité de la situation, et qui choque souvent les victimes. La confusion, avec des messages contradictoires ou peu clairs. Et l'incohérence, entre ce qui est dit et ce qui est fait. Petit quiz. Face à une crise, faut-il attendre d'avoir toutes les informations ? Non, il faut communiquer vite.`,
// 19
`Voyons des exemples togolais. Le ProMAT doit gérer des crises comme les sécheresses, les inondations, ou des problèmes d'adoption des nouvelles pratiques. Sa communication de crise informe les agriculteurs et les partenaires. Le programme CIZO gère des pannes d'équipements, des vols de kits, ou des problèmes de maintenance, en informant les communautés et les autorités. Et les entreprises togolaises font face à des pannes, des cyberattaques ou des scandales, où la communication de crise protège leur réputation. Chaque organisation a ses propres risques.`,
// 20
`Synthèse du chapitre. La gestion de crise comprend cinq phases, la prévention, la préparation, la réponse, le rétablissement et l'apprentissage. La communication de crise vise à informer, rassurer, maintenir la confiance et protéger la réputation. Ses principes sont la rapidité, la transparence, la cohérence, l'empathie et l'action. Et il faut éviter le silence, le déni, la minimisation, la confusion et l'incohérence. Retenez surtout qu'une crise se prépare avant qu'elle n'arrive. Préparez-vous dès aujourd'hui. Une cellule de crise, des porte-parole et des messages types font toute la différence.`,
// 21
`Voici les réponses au quiz. Qu'est-ce qu'une crise ? C'est un événement soudain et imprévu, qui menace l'organisation, sa réputation ou ses parties prenantes, et qui exige une réponse rapide et coordonnée. Quelles sont les phases de la gestion de crise ? La prévention, la préparation, la réponse, le rétablissement et l'apprentissage. Et quels sont les principes de la communication de crise ? La rapidité, la transparence, la cohérence, l'empathie et l'action. Bravo pour votre attention. Passons au chapitre suivant.`,
// 22
`Abordons le troisième chapitre, consacré à la responsabilité sociale. La responsabilité sociale est l'intégration des préoccupations sociales et environnementales dans les activités de l'organisation. Elle est devenue une exigence pour les organisations modernes. Les clients, les employés, les investisseurs et les bailleurs de fonds attendent des organisations qu'elles ne se contentent pas de faire des profits, mais qu'elles contribuent aussi positivement à la société et à la protection de l'environnement. Voyons de quoi il s'agit précisément. Elle concerne toutes les organisations.`,
// 23
`Définissons la responsabilité sociale, que l'on appelle aussi RSE, pour responsabilité sociétale des entreprises. C'est l'intégration volontaire, par les organisations, de préoccupations sociales et environnementales, dans leurs activités et dans leurs relations avec leurs parties prenantes. Le mot volontaire est important. La RSE va au-delà de ce que la loi impose. Elle traduit un engagement de l'organisation à agir de manière responsable envers ses employés, ses clients, les communautés et l'environnement. Elle engage toute l'organisation. C'est un choix stratégique.`,
// 24
`La responsabilité sociale comprend trois dimensions. La dimension sociale, qui concerne les droits humains, les conditions de travail, et l'impact sur les communautés. La dimension environnementale, qui concerne la protection de l'environnement et la réduction de l'empreinte écologique, comme les émissions et les déchets. Et la dimension économique, qui concerne la création de valeur durable, pour l'organisation comme pour la société. Ces trois dimensions doivent être équilibrées, aucune ne doit être sacrifiée aux autres. Elles forment un ensemble cohérent. Voyons leurs avantages.`,
// 25
`La responsabilité sociale présente quatre avantages. L'amélioration de la réputation, car le public apprécie les organisations engagées. La fidélisation des clients, de plus en plus sensibles aux pratiques des entreprises. La motivation des employés, fiers de travailler pour une organisation responsable. Et la réduction des risques, notamment sociaux, environnementaux et juridiques. La RSE n'est donc pas seulement une question de valeurs. C'est aussi un véritable levier de performance à long terme. Tout le monde y gagne. Voyons comment en parler.`,
// 26
`Comment intégrer la responsabilité sociale dans la communication ? En communiquant de manière transparente sur ses engagements et sur ses réalisations, y compris sur ce qui reste à améliorer. En impliquant les parties prenantes, en les consultant et en les associant aux actions. Et surtout, en évitant le greenwashing, c'est-à-dire l'écoblanchiment, qui consiste à afficher un engagement environnemental de façade, sans actions réelles. Le greenwashing, une fois découvert, détruit la crédibilité de l'organisation. Les actes doivent précéder les mots. Soyez exemplaires.`,
// 27
`Voici quatre bonnes pratiques de RSE. Définir une politique de responsabilité sociale claire, avec des engagements précis. Mettre en place des indicateurs, pour mesurer les progrès, par exemple le nombre d'emplois locaux créés ou la réduction des déchets. Communiquer de manière transparente sur ces résultats. Et impliquer les parties prenantes à chaque étape. Petit quiz. Une entreprise qui se dit verte sans aucune action concrète, comment appelle-t-on cela ? Du greenwashing, ou écoblanchiment. Bravo si vous aviez trouvé. Méfiez-vous-en.`,
// 28
`Voyons des exemples togolais. Le ProMAT intègre la responsabilité sociale à travers la création d'emplois, la formation des agriculteurs et la protection de l'environnement. Le programme CIZO l'intègre par l'accès à l'énergie pour les populations rurales, la création d'emplois locaux, et l'utilisation d'une énergie renouvelable, le solaire. Et les entreprises togolaises développent des programmes de développement communautaire, protègent l'environnement, et s'efforcent d'offrir des conditions de travail équitables. Ces exemples montrent que la RSE est déjà une réalité au Togo, et pas seulement un concept importé.`,
// 29
`Synthèse du chapitre. La responsabilité sociale est l'intégration volontaire des préoccupations sociales et environnementales dans les activités de l'organisation. Ses dimensions sont sociale, environnementale et économique. Ses avantages sont la réputation, la fidélisation des clients, la motivation des employés et la réduction des risques. Et son intégration dans la communication repose sur la transparence, l'implication des parties prenantes, et le refus du greenwashing. Agir d'abord, communiquer ensuite, voilà la règle d'or. Gardez-la toujours en tête. Et communiquer honnêtement.`,
// 30
`Voici les réponses au quiz. Qu'est-ce que la responsabilité sociale ? C'est l'intégration volontaire, par les organisations, de préoccupations sociales et environnementales dans leurs activités et leurs relations avec les parties prenantes. Quelles sont ses dimensions ? La dimension sociale, la dimension environnementale et la dimension économique. Et comment l'intègre-t-on dans la communication ? En communiquant de façon transparente sur ses engagements et ses réalisations, en impliquant les parties prenantes, et en évitant le greenwashing. Bravo pour votre attention. Merci.`,
// 31
`Passons au quatrième et dernier chapitre, consacré au cycle de vie d'un projet de communication. Le cycle de vie, c'est l'ensemble des étapes par lesquelles passe un projet de communication, depuis sa conception jusqu'à son évaluation. Qu'il s'agisse d'une campagne de sensibilisation, du lancement d'un produit, ou de la communication interne d'un projet, la démarche reste la même. Ce chapitre fait le lien avec la communication stratégique vue en séance un, et clôt ainsi le cours. Voyons ces étapes. Allons-y.`,
// 32
`Le cycle de vie comprend cinq étapes. La conception, avec la définition des objectifs, l'analyse du contexte et l'identification des publics. La planification, avec les stratégies, les messages, les canaux, le budget et le calendrier. La mise en oeuvre, avec la production des supports, leur diffusion et la coordination des acteurs. Le suivi, avec la mesure des résultats et les ajustements. Et l'évaluation, avec le bilan et les leçons apprises. Voyons chaque étape en détail. Commençons par la conception. Allons-y.`,
// 33
`Première étape, la conception. Elle comprend quatre actions. Définir les objectifs de communication, idéalement précis et mesurables, par exemple faire connaître le projet à soixante pour cent des agriculteurs d'une région en six mois. Analyser le contexte, interne et externe. Identifier les publics cibles. Et formuler les messages clés. Cette étape est fondamentale, car toutes les suivantes en découlent. Une conception bâclée compromet tout le projet. Prenez le temps nécessaire. Un objectif précis permet de mesurer ensuite les résultats obtenus.`,
// 34
`Deuxième étape, la planification. Elle comprend le choix des stratégies, la définition précise des messages, la sélection des canaux les plus adaptés à chaque public, l'élaboration du budget, et l'établissement du calendrier. C'est en quelque sorte le plan de bataille du projet de communication. Il précise qui fait quoi, quand, avec quels moyens, et pour quel coût. Un bon plan de communication est assez précis pour guider l'action, et assez souple pour s'adapter aux imprévus. Il sert de référence à toute l'équipe.`,
// 35
`Troisième étape, la mise en oeuvre. Elle comprend la production des supports, qu'il s'agisse de textes, d'images ou de vidéos. Elle comprend aussi la diffusion, à travers les médias, les réseaux sociaux, les réunions ou les radios locales. Et elle comprend la coordination des acteurs, internes et externes, comme les équipes de communication, les prestataires et les partenaires. C'est l'étape la plus visible du projet, mais elle ne réussit que si les étapes précédentes ont été bien menées. La qualité d'exécution compte beaucoup.`,
// 36
`Quatrième étape, le suivi. Il comprend la mesure des résultats, grâce à des indicateurs, comme le nombre de personnes touchées, le taux de participation ou le nombre de réactions. Il comprend aussi l'analyse des écarts entre les résultats obtenus et les objectifs fixés. Et enfin les ajustements, pour corriger le tir pendant le projet, sans attendre sa fin. Le suivi permet ainsi de réagir à temps, par exemple en changeant de canal si un message ne touche pas son public.`,
// 37
`Cinquième étape, l'évaluation. Elle comprend le bilan, qui mesure l'atteinte des objectifs. Elle comprend l'analyse des leçons apprises, ce qui a bien fonctionné, et ce qui pourrait être amélioré. Et elle comprend les recommandations pour les projets futurs. L'évaluation est souvent négligée, faute de temps ou de moyens. Pourtant, c'est elle qui permet à l'organisation de progresser d'un projet à l'autre, et de justifier ses investissements en communication auprès de la direction ou des bailleurs. Ne la négligez jamais. Elle est précieuse.`,
// 38
`Un projet de communication comporte aussi des risques. Les messages inadaptés, qui ne correspondent pas aux attentes du public. Les canaux inefficaces, qui ne touchent pas les bonnes personnes. Les budgets insuffisants, qui empêchent de mener les actions prévues. Les délais non respectés, qui font rater le bon moment. Et les crises imprévues, qui peuvent bouleverser le projet. Identifier ces risques dès la planification permet de prévoir des solutions de repli, comme nous l'avons vu pour la gestion de crise.`,
// 39
`Voyons des exemples togolais. Le ProMAT a conçu un projet de communication pour la vulgarisation agricole. Il a défini ses objectifs et ses publics, planifié ses messages et ses canaux, mis en oeuvre des formations et des supports, assuré le suivi par des enquêtes, et évalué son impact. Le programme CIZO a suivi les mêmes étapes pour sensibiliser les communautés. Et les entreprises togolaises conçoivent ainsi leurs campagnes marketing, leur communication interne et leurs relations publiques. La méthode est universelle.`,
// 40
`Synthèse du chapitre. Le cycle de vie d'un projet de communication comprend cinq étapes, la conception, la planification, la mise en oeuvre, le suivi et l'évaluation. Chaque étape a ses enjeux et ses risques. Une gestion stratégique et planifiée est donc essentielle, pour que la communication serve réellement les objectifs de l'organisation. Retenez cet enchaînement en cinq étapes, il vous servira pour tous les projets de communication que vous aurez à concevoir dans votre carrière. Elle structure toute démarche de communication.`,
// 41
`Voici les réponses au quiz. Quelles sont les étapes du cycle de vie d'un projet de communication ? La conception, la planification, la mise en oeuvre, le suivi et l'évaluation. Quels sont ses risques ? Les messages inadaptés, les canaux inefficaces, les budgets insuffisants, les délais non respectés et les crises imprévues. Et pourquoi une gestion stratégique est-elle importante ? Parce qu'elle aligne la communication sur les objectifs, utilise au mieux les ressources, et permet de mesurer et d'améliorer les résultats.`,
// 42
`Concluons cette dixième et dernière séance. Vous avez découvert les enjeux éthiques de la communication, appris à gérer une crise, à intégrer la responsabilité sociale, et à analyser le cycle de vie d'un projet de communication. Au terme de ce cours, vous disposez d'une vision complète de la communication professionnelle. Vous savez communiquer à l'écrit et à l'oral, adapter votre message aux publics, utiliser les outils numériques, gérer les enjeux interculturels, et concevoir un projet de communication complet. Bravo pour tout ce chemin parcouru.`,
// 43
`Voici la conclusion générale du cours CMNS deux cent un. Vous avez découvert que la communication est un pilier de la performance des organisations. Elle permet de coordonner, de motiver, de convaincre, de gérer les relations et de protéger la réputation. Vous avez parcouru les modèles de communication, l'écrit, l'oral, l'interculturel, le numérique, l'éthique et la gestion de crise. Les exemples togolais, ProMAT, CIZO et PASH-MUT, ont montré l'importance d'une bonne communication. Je vous souhaite une pleine réussite dans vos communications professionnelles.`,
];
