module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans la semaine onze du cours MGT cent un. Nous entrons dans la troisième partie du cours, intitulée écrire correctement en anglais technique. Cette semaine porte sur la ponctuation, les majuscules et la rédaction technique. Le chapitre huit de notre manuel traite des principes généraux de ponctuation, du point, des deux points, de la virgule, du point-virgule et des autres signes, puis des règles relatives aux majuscules. Une bonne ponctuation est essentielle pour qu'un document technique soit clair et sans ambiguïté.`,
// 2
`Voici les objectifs de cette semaine. Vous devrez être capables de ponctuer correctement une phrase, et d'utiliser les majuscules selon les règles de l'anglais. Vous apprendrez aussi à structurer un paragraphe, à rédiger une courte description technique, et à présenter une consigne technique de manière claire. Ces compétences sont directement utiles dans votre vie professionnelle, car la moindre erreur de ponctuation ou de formulation peut rendre une consigne difficile à comprendre, voire dangereuse. Commençons tout de suite par le signe de ponctuation le plus simple, le point.`,
// 3
`Commençons par le point. Il marque la fin d'une phrase déclarative, c'est-à-dire d'une phrase qui donne une information complète. Par exemple, The system is operational. Le point indique au lecteur que l'idée est terminée. En anglais technique, on privilégie souvent des phrases courtes, chacune terminée par un point, pour faciliter la lecture et éviter toute confusion. Une phrase trop longue, sans point, devient rapidement difficile à suivre, surtout dans une notice ou un rapport. Pensez-y chaque fois que vous rédigez une consigne ou une procédure.`,
// 4
`Les deux points servent à introduire une explication, une précision ou une liste. Par exemple, The problem has one main cause: the server is offline. Le problème a une cause principale, le serveur est hors ligne. Ici, les deux points annoncent la cause. Remarquez qu'en anglais, contrairement au français, on ne met pas d'espace avant les deux points. C'est une différence typographique importante, qu'il faut respecter dans tous vos documents rédigés en anglais. Les deux points peuvent aussi annoncer une liste, par exemple, a router, a switch and a server.`,
// 5
`La virgule permet notamment d'organiser certaines informations dans la phrase. Elle sépare par exemple un mot de liaison du reste de la phrase. Par exemple, First, check the power supply. Ici, la virgule après first marque une pause, et met en valeur l'ordre des étapes. On l'utilise aussi pour séparer les éléments d'une liste, ou pour isoler une information complémentaire. Bien placée, la virgule rend la phrase plus lisible. Mal placée, elle peut au contraire en modifier le sens. Relisez donc toujours vos phrases.`,
// 6
`Le point-virgule peut relier deux propositions étroitement liées. Par exemple, The server is offline; the technician is checking it. Le serveur est hors ligne, et le technicien le vérifie. Le point-virgule marque une pause plus forte que la virgule, mais plus faible que le point. Il permet de montrer que deux idées sont liées, sans utiliser de conjonction. Comme pour les deux points, on ne met pas d'espace avant le point-virgule en anglais. Utilisez-le avec modération, car un texte technique doit rester simple et direct.`,
// 7
`Passons aux majuscules, dont les règles diffèrent parfois du français. Notre manuel prévoit leur étude pour les noms et prénoms, les titres et fonctions, les marques, les nationalités, les lieux géographiques, les périodes historiques, les mois et les jours de la semaine. Par exemple, on écrit Monday et January avec une majuscule, alors qu'en français, lundi et janvier s'écrivent en minuscules. De même, on écrit English et France avec une majuscule. Attention à ces différences, qui sont une source fréquente d'erreurs.`,
// 8
`Voyons maintenant la rédaction technique. Elle doit privilégier la précision, la clarté, la logique, la concision et un vocabulaire approprié. Voici un exemple. Connect the router to the power supply. Wait for the power indicator to turn green. Then connect the Ethernet cable to port one. Chaque phrase est courte, commence par un verbe à l'impératif, et décrit une seule action. Cette forme est bien préférable à une formulation longue et ambiguë, car l'utilisateur peut suivre les étapes sans risque d'erreur.`,
// 9
`Terminons avec les consignes de sécurité. Dans un contexte technique, vous devez être capables de les comprendre et de les produire. Voici quelques exemples. Do not open the device while it is connected to the power supply. Wear protective equipment. Disconnect the power before maintenance. Ces consignes utilisent l'impératif, sont courtes, et ne laissent aucune place à l'interprétation. Cela répond directement à un objectif du syllabus, lire, comprendre et rédiger des documents techniques, comme des rapports, des notices, des modes d'emploi et des consignes de sécurité.`,
];
