module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le chapitre quatre du cours DSC trois cent vingt-quatre, consacré à l'analyse en composantes principales, sa mise en oeuvre et son interprétation. Au chapitre précédent, nous avons découvert le principe de la PCA. Nous allons maintenant passer à la pratique. Comment réaliser une PCA étape par étape ? Combien de composantes retenir ? Comment lire le cercle des corrélations, le graphique des individus et le biplot ? Et comment utiliser les composantes dans d'autres analyses ? C'est parti.`,
// 2
`Voici les objectifs pédagogiques de ce chapitre. Premièrement, appliquer une PCA à un jeu de données réel. Deuxièmement, sélectionner le nombre pertinent de composantes principales, à l'aide de critères reconnus. Troisièmement, interpréter la contribution des variables aux composantes. Et quatrièmement, analyser et interpréter la variance expliquée, ainsi que les représentations graphiques associées, comme le cercle des corrélations et le graphique des individus. À la fin de ce chapitre, vous serez capables de mener une PCA complète, de bout en bout.`,
// 3
`La mise en oeuvre d'une PCA suit sept étapes. Un, sélectionner les variables quantitatives pertinentes pour l'analyse. Deux, standardiser ces variables, avec une moyenne nulle et un écart-type égal à un. Trois, calculer la matrice de corrélation. Quatre, décomposer cette matrice en valeurs propres et vecteurs propres. Cinq, ordonner les composantes principales par valeur propre décroissante. Six, sélectionner le nombre de composantes à retenir. Et sept, interpréter les composantes retenues, à l'aide des loadings et des représentations graphiques. Suivez toujours cet ordre.`,
// 4
`Chaque composante principale est associée à une valeur propre, notée lambda k, qui mesure la quantité de variance qu'elle capture. La proportion de variance expliquée par la composante k se calcule en divisant sa valeur propre par la somme de toutes les valeurs propres. Sur données standardisées, cette somme est égale au nombre de variables p. Par exemple, avec dix variables, une composante de valeur propre quatre explique quarante pour cent de la variance totale. On additionne ensuite ces proportions pour obtenir la variance cumulée.`,
// 5
`Trois critères permettent de choisir le nombre de composantes. Le critère de Kaiser ne conserve que les composantes dont la valeur propre dépasse un, sur données standardisées. L'idée est qu'une telle composante résume plus d'information qu'une variable d'origine seule. Le graphique des éboulis, ou scree plot, représente les valeurs propres selon leur rang. On repère le coude, à partir duquel la variance supplémentaire devient négligeable. Enfin, le seuil de variance cumulée retient assez de composantes pour couvrir, par exemple, quatre-vingts ou quatre-vingt-dix pour cent de la variance totale.`,
// 6
`Voici une bonne pratique importante. Ces trois critères doivent être utilisés de façon complémentaire, et non isolément. Chacun a ses faiblesses. Le critère de Kaiser retient parfois trop de composantes quand les variables sont nombreuses. Le coude du scree plot n'est pas toujours net. Et le seuil de variance cumulée reste arbitraire. En revanche, un scree plot ambigu, combiné au critère de Kaiser et à la variance cumulée, offre une décision bien plus robuste. Pensez aussi à l'interprétabilité, une composante qu'on ne sait pas interpréter est peu utile.`,
// 7
`Comment évaluer la contribution d'une variable à une composante ? D'abord grâce à son coefficient, son loading, que nous avons déjà rencontré. Mais aussi grâce à sa corrélation avec la composante. Plus cette corrélation est forte en valeur absolue, plus la variable contribue à définir la composante. Ces corrélations sont très souvent représentées graphiquement, sur ce que l'on appelle le cercle des corrélations. C'est l'un des graphiques les plus utiles de la PCA, et nous allons apprendre à le lire dès maintenant.`,
// 8
`Sur le cercle des corrélations, chaque variable est représentée par une flèche partant de l'origine, sur le plan formé par deux composantes. La longueur de la flèche indique la qualité de représentation de la variable. Une flèche proche du bord du cercle est bien représentée sur ce plan. L'angle entre deux flèches renseigne sur leur corrélation. Un angle proche de zéro degré indique une forte corrélation positive. Un angle proche de cent quatre-vingts degrés, une forte corrélation négative. Et un angle proche de quatre-vingt-dix degrés, une quasi-absence de corrélation.`,
// 9
`Une fois les composantes calculées, chaque observation peut être projetée sur le plan formé par les deux ou trois premières composantes. C'est le graphique des individus, ou score plot. Cette projection permet de repérer visuellement des regroupements naturels d'observations, des individus atypiques, isolés du reste, ou encore des gradients continus le long d'une composante. C'est une étape exploratoire précieuse avant d'entreprendre un clustering formel, que nous étudierons aux chapitres sept et huit. Souvent, les groupes y sont déjà visibles. Regardez-le attentivement.`,
// 10
`Le biplot superpose, sur un même graphique, le score plot des individus et le cercle des corrélations des variables. Il offre ainsi une lecture combinée très riche. On peut observer directement quelles variables caractérisent quels groupes d'individus. Par exemple, si un groupe de clients se situe dans la direction de la flèche du revenu, ces clients ont des revenus élevés. Le biplot est très apprécié pour communiquer les résultats d'une PCA, mais attention à ne pas le surcharger, avec trop de points ou trop de flèches.`,
// 11
`Au-delà de la visualisation, les composantes principales retenues peuvent servir de nouvelles variables d'entrée pour d'autres analyses, comme le clustering, la classification ou la régression. L'avantage est double. On résume l'information de nombreuses variables corrélées en quelques variables non corrélées. Et l'on améliore souvent la stabilité et la performance des méthodes appliquées ensuite, en éliminant la multicolinéarité et une partie du bruit. La contrepartie est une interprétation un peu moins directe, puisque chaque composante mélange plusieurs variables d'origine. Il faut donc bien peser le pour et le contre.`,
// 12
`Retenons les points clés. La mise en oeuvre d'une PCA suit une séquence précise, standardisation, décomposition en valeurs propres, sélection puis interprétation des composantes. La proportion de variance expliquée se calcule à partir de la valeur propre relative, et le scree plot et le critère de Kaiser aident à choisir le nombre de composantes. Le cercle des corrélations interprète les variables. Le score plot projette les individus, et le biplot combine les deux. Enfin, les composantes retenues peuvent alimenter d'autres analyses, comme le clustering ou la classification.`,
// 13
`Voici les corrigés des exercices. Un, avec une chute nette entre la deuxième et la troisième composante, puis un plateau, le coude se situe au rang deux. On retient donc deux composantes, à confirmer par le critère de Kaiser et la variance cumulée. Deux, un angle proche de cent quatre-vingts degrés indique une forte corrélation négative entre les deux variables. Proche de quatre-vingt-dix degrés, elles sont quasiment non corrélées. Trois, deux nuages séparés sur la première composante suggèrent deux groupes. La prochaine étape serait un clustering, pour les formaliser et les caractériser.`,
];
