module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le chapitre quatre du cours DSC quatre cent vingt-trois, consacré à la construction et à la validation de modèles de régression. Nous ouvrons ici la deuxième partie du cours, qui correspond aux semaines quatre et cinq. Jusqu'à présent, nous savions estimer un modèle. Maintenant, nous allons apprendre à choisir les bonnes variables, à comparer plusieurs modèles entre eux, et à vérifier qu'un modèle prédit bien sur des données qu'il n'a jamais vues.`,
// 2
`Voici les objectifs de ce chapitre. Vous comprendrez les enjeux de la sélection de variables en régression. Vous saurez mettre en oeuvre les méthodes de sélection pas à pas, appelées forward, backward et stepwise. Vous utiliserez les critères d'information AIC et BIC pour comparer des modèles. Vous maîtriserez les principes de la validation croisée. Vous comprendrez le compromis entre biais et variance, un concept central. Et enfin, vous appliquerez toutes ces techniques sur des données réelles, avec votre logiciel. Commençons.`,
// 3
`Pourquoi sélectionner des variables ? On dispose souvent de nombreuses variables explicatives potentielles, mais toutes ne sont pas utiles. En inclure trop peut provoquer un sur-ajustement, qui détériore la performance prédictive. Cela augmente aussi la variance des estimations, par exemple à cause de la multicolinéarité. Le modèle devient difficile à interpréter. Et les coûts de collecte et de traitement des données augmentent. L'objectif est donc de trouver un modèle parcimonieux, qui explique bien Y avec un nombre réduit de variables pertinentes.`,
// 4
`Voici un concept fondamental, le compromis biais-variance. Le biais est l'erreur due à la simplification du modèle, par exemple l'oubli d'une variable importante. Un modèle trop simple a un biais élevé. La variance est la sensibilité du modèle aux fluctuations de l'échantillon. Un modèle trop complexe a une variance élevée. En ajoutant des variables, on réduit le biais mais on augmente la variance. Un modèle sous-ajusté ne capture pas la structure des données. Un modèle sur-ajusté capture le bruit. Le modèle optimal équilibre les deux.`,
// 5
`Plusieurs approches permettent de sélectionner les variables. Les approches pas à pas ajoutent ou retirent les variables de manière itérative. Les approches par critère d'information comparent tous les modèles possibles, ou un sous-ensemble, et retiennent celui qui minimise l'AIC ou le BIC. Enfin, les approches de régularisation, comme ridge, lasso ou elastic net, pénalisent les coefficients. Elles seront abordées dans un cours plus avancé. Ce chapitre se concentre donc sur les méthodes pas à pas et sur les critères d'information.`,
// 6
`Commençons par la méthode forward, ou sélection ascendante. On part d'un modèle vide, qui ne contient que l'ordonnée à l'origine. Pour chaque variable non incluse, on calcule la p-value de son ajout. On ajoute la variable qui a la plus petite p-value, si elle est inférieure à un seuil fixé. Et l'on répète jusqu'à ce qu'aucune variable ne satisfasse plus ce critère d'entrée. Son avantage, elle est simple et rapide. Son inconvénient, une variable ajoutée ne peut plus être retirée, et l'on peut manquer la meilleure combinaison.`,
// 7
`La méthode backward, ou sélection descendante, fait l'inverse. On part du modèle complet, avec toutes les variables. Pour chaque variable incluse, on calcule la p-value de son retrait. On retire la variable qui a la plus grande p-value, si elle dépasse le seuil fixé. Et l'on répète jusqu'à ce que toutes les variables restantes soient significatives. Son avantage, elle tient compte des relations entre variables, puisque toutes sont présentes au départ. Ses inconvénients, le calcul peut être coûteux, et une variable retirée ne revient jamais.`,
// 8
`La méthode stepwise, ou mixte, combine les deux approches. On démarre avec un modèle vide, ou un modèle initial choisi. À chaque étape, on examine à la fois les variables absentes, pour un éventuel ajout, et les variables présentes, pour un éventuel retrait. On ajoute la plus significative, ou l'on retire la moins significative, selon ce qui est le plus favorable. On s'arrête quand aucun ajout ni retrait ne se justifie. Elle est plus flexible que les deux précédentes, mais peut rester instable et dépendre de l'ordre des variables.`,
// 9
`Les méthodes pas à pas ont des limites importantes. Elles sont instables, un petit changement dans les données peut donner un modèle complètement différent. La sélection est biaisée, car les p-values ne tiennent pas compte du grand nombre de tests effectués. Rien ne garantit que le modèle retenu soit le meilleur possible. Et elles encouragent le sur-ajustement, surtout si les seuils sont mal choisis. Retenez donc que ce sont des outils d'exploration, pas de sélection définitive. Leurs résultats doivent être validés, par exemple par validation croisée.`,
// 10
`Les critères d'information mesurent la qualité d'un modèle, en pénalisant sa complexité. Ils permettent de comparer des modèles, même non emboîtés. L'AIC, critère d'Akaike, vaut moins deux fois la log-vraisemblance, plus deux fois le nombre de paramètres. Le BIC, critère bayésien, remplace ce deux k par k fois le logarithme de n. Dans les deux cas, plus la valeur est faible, meilleur est le modèle. Le BIC pénalise plus lourdement la complexité dès que n dépasse sept, et choisit donc des modèles plus parcimonieux.`,
// 11
`Comparons les deux critères. L'AIC a une pénalité de deux k, et vise la prédiction. Il est asymptotiquement efficace, il minimise l'erreur de prédiction. Le BIC a une pénalité de k fois logarithme de n, et vise la sélection du bon modèle. Il est asymptotiquement cohérent, il retrouve le vrai modèle quand n est grand. Règle pratique, utilisez l'AIC pour prédire, et le BIC pour un modèle interprétable et parcimonieux. Une différence de deux points d'AIC est faiblement significative, au-delà de dix, elle est très significative.`,
// 12
`La mise en oeuvre est très simple. Avec R, après avoir estimé plusieurs régressions, il suffit d'appeler la fonction AIC, avec les modèles un, deux et trois en arguments, pour obtenir leurs valeurs côte à côte. La fonction BIC fonctionne exactement de la même manière. Avec Python et statsmodels, chaque modèle estimé possède directement les attributs aic et bic. Il suffit de les afficher. Petit quiz, entre deux modèles d'AIC cent vingt et cent quarante, lequel choisir ? Celui à cent vingt, car l'AIC le plus faible est le meilleur.`,
// 13
`Passons à la validation croisée. C'est une technique qui évalue la performance d'un modèle sur des données non vues. Elle suit cinq étapes. On divise d'abord les données en k sous-ensembles, appelés folds. On entraîne le modèle sur k moins un sous-ensembles, l'ensemble d'apprentissage. On le teste sur le sous-ensemble restant, l'ensemble de validation. On répète cette procédure k fois, pour que chaque sous-ensemble serve une fois de test. Et enfin, on calcule l'erreur moyenne sur les k tests. Chaque observation sert donc à la fois à apprendre et à tester.`,
// 14
`Il existe plusieurs types de validation croisée. La validation croisée à dix folds est le standard en pratique, car elle offre un bon compromis entre biais et variance. La validation croisée à cinq folds est moins coûteuse en calcul, mais présente un peu plus de biais. Enfin, la méthode leave one out, où k est égal à n, utilise chaque observation tour à tour comme ensemble de test. Elle est très coûteuse en calcul, mais peut être utile pour les petits échantillons, où chaque observation compte.`,
// 15
`Pourquoi utiliser la validation croisée ? Pour trois raisons. D'abord, elle évite le sur-ajustement, car le modèle n'est jamais évalué sur les données qui ont servi à l'entraîner. Ensuite, elle fournit une estimation robuste, la performance moyenne sur plusieurs découpages est bien plus fiable qu'une seule division entre apprentissage et test. Enfin, elle permet de comparer objectivement différents modèles, y compris des modèles de complexité différente. C'est aujourd'hui la méthode de référence pour évaluer la capacité prédictive d'un modèle. Utilisez-la systématiquement.`,
// 16
`Voyons le logiciel. Avec R, on utilise le package caret. On fixe d'abord une graine aléatoire avec set seed, pour des résultats reproductibles. On définit le contrôle avec trainControl, méthode cv et dix folds. Puis la fonction train estime le modèle linéaire avec validation croisée. Avec Python et scikit-learn, on crée un modèle LinearRegression, puis cross val score calcule les scores sur dix folds, avec l'erreur quadratique moyenne négative. On prend l'opposé de leur moyenne pour obtenir l'erreur quadratique moyenne.`,
// 17
`Illustrons le compromis biais-variance. Imaginez que l'on tire plusieurs échantillons et que l'on ajuste un modèle à chaque fois. Une simple droite donne des estimations proches les unes des autres, faible variance, mais parfois loin de la vraie relation, biais élevé. Un polynôme de degré élevé donne des estimations très variables, mais proches en moyenne de la vérité. L'erreur de prédiction est la somme du biais au carré, de la variance et d'une erreur irréductible. On la contrôle par la validation croisée, la régularisation et la sélection de variables.`,
// 18
`Passons à une étude de cas, le jeu de données Boston Housing, disponible dans R et Python. Il décrit des logements de Boston, avec le prix médian, le taux de criminalité, le nombre de pièces, l'âge, et d'autres variables. La démarche suit quatre étapes. L'exploration, en visualisant les relations et en calculant les corrélations. La sélection de variables, avec forward, backward ou stepwise, et la comparaison par AIC ou BIC. La validation croisée pour évaluer la performance. Et enfin la sélection du modèle le plus prédictif et le plus parcimonieux.`,
// 19
`Voici la mise en oeuvre avec R. On charge le package MASS et le jeu de données Boston. On estime d'abord le modèle complet, qui explique le prix médian par toutes les variables disponibles. On applique ensuite la fonction step, avec la direction both, pour une sélection stepwise fondée sur l'AIC. On compare les deux modèles avec les fonctions AIC et BIC. Enfin, avec caret, on réalise une validation croisée à dix folds. Ce code est un excellent modèle à réutiliser pour votre propre projet d'analyse.`,
// 20
`Interprétons les résultats. La sélection stepwise a retenu un sous-ensemble de variables, par exemple le taux de criminalité, le nombre de pièces, l'âge, le statut socio-économique et le ratio élèves par enseignant. L'AIC du modèle stepwise est plus faible que celui du modèle complet, ce qui indique un meilleur compromis entre ajustement et complexité. Enfin, la validation croisée confirme la bonne performance prédictive du modèle sélectionné. Les trois outils convergent, ce qui renforce notre confiance dans le modèle final. C'est une démarche exemplaire.`,
// 21
`Résumons ce chapitre. La sélection de variables est essentielle pour construire des modèles parcimonieux, interprétables et prédictifs. Le compromis biais-variance est fondamental, plus de complexité réduit le biais mais augmente la variance. Les méthodes forward, backward et stepwise sont des outils d'exploration. L'AIC et le BIC comparent des modèles en pénalisant la complexité. La validation croisée est la méthode de référence pour évaluer la prédiction. Et c'est la combinaison de ces techniques qui donne des modèles robustes. Au prochain chapitre, nous analyserons les résidus.`,
];
