module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le cours CSC trois cent quarante-sept, consacré aux concepts des langages de programmation. Nous ouvrons aujourd'hui la première partie du cours, intitulée fondements des langages de programmation. Vous avez sans doute déjà programmé dans un ou plusieurs langages. Dans ce cours, nous allons prendre de la hauteur, pour comprendre comment les langages sont conçus, ce qui les distingue, et pourquoi on choisit l'un plutôt que l'autre selon le problème. Allons-y.`,
// 2
`Cette première séance est une introduction aux concepts des langages de programmation. Elle poursuit quatre objectifs. Comprendre ce qu'est un langage de programmation, et quelles sont ses composantes. Identifier les principaux paradigmes de programmation. Distinguer la syntaxe, la sémantique et la pragmatique d'un langage. Et enfin, prendre en main l'environnement de travail, ainsi que Scala trois, le langage principal du cours. Ces quatre objectifs correspondent aux quatre chapitres de la séance, que nous allons parcourir dans l'ordre. Commençons.`,
// 3
`Le premier chapitre répond à une question simple en apparence. Qu'est-ce qu'un langage de programmation ? C'est un langage formel, utilisé pour décrire des algorithmes et des structures de données. Il permet de communiquer des instructions à une machine, de façon précise et sans ambiguïté. Contrairement au français, qui tolère les sous-entendus, un langage de programmation exige une rigueur totale. Ce chapitre pose les bases du cours, en définissant précisément ce qu'est un langage, et quelles sont ses composantes. Allons-y.`,
// 4
`Voici la définition. Un langage de programmation est un ensemble de règles syntaxiques et sémantiques, qui permettent d'écrire des programmes. Et un programme est une suite d'instructions qui, une fois exécutées par une machine, produisent un résultat. Par exemple, un programme peut calculer la moyenne des notes d'une classe, ou afficher la liste des clients d'une entreprise. Retenez bien ces deux mots, syntaxique et sémantique. Nous allons les approfondir tout au long de cette séance, et du cours. Ils sont fondamentaux.`,
// 5
`Un langage de programmation comprend trois dimensions essentielles. La syntaxe, c'est-à-dire les règles de formation des programmes. La sémantique, c'est-à-dire leur signification. Et la pragmatique, c'est-à-dire leur utilisation concrète. Mais un langage comprend aussi d'autres éléments. Un système de types, qui précise la nature des données, entiers, textes ou booléens. Un modèle d'exécution, qui décrit comment le programme s'exécute. Et des bibliothèques, c'est-à-dire du code prêt à l'emploi, qui évite de tout réécrire. Voyons maintenant les niveaux de langage, du plus proche au plus éloigné de la machine.`,
// 6
`Les langages se situent à différents niveaux. Tout en bas, le langage machine, fait de zéros et de uns, directement compris par le processeur, mais illisible pour un humain. Au-dessus, le langage d'assemblage, qui remplace ces suites binaires par des mnémoniques, de courts mots comme ADD ou MOV. Et tout en haut, les langages de haut niveau, comme C, Java ou Scala. Ces derniers sont plus expressifs, car une ligne exprime beaucoup, et plus portables, car ils fonctionnent sur différentes machines.`,
// 7
`Comment évaluer un langage ? Selon six critères. La lisibilité, la facilité à lire et comprendre un programme. L'expressivité, la capacité à exprimer des idées complexes simplement. La sécurité, la capacité à éviter les erreurs, par exemple grâce aux types. La performance, la rapidité d'exécution et l'économie de mémoire. La portabilité, la capacité à fonctionner sur différentes machines. Et la maintenabilité, la facilité à corriger et faire évoluer le programme dans le temps. Aucun langage n'excelle sur tous ces critères à la fois.`,
// 8
`Voyons des exemples dans le contexte togolais. Le choix du langage dépend du type d'application. Pour les applications de gestion, comme la comptabilité ou la gestion des stocks, on utilise souvent Java, Python ou Scala. Pour les applications mobiles, très répandues au Togo, on utilise Kotlin pour Android, Swift pour l'iPhone, ou JavaScript pour les applications multiplateformes. Et pour les systèmes embarqués, comme les compteurs électriques ou les capteurs agricoles, on utilise C ou C plus plus, pour leur performance.`,
// 9
`Voici une application à la gestion. Une entreprise togolaise peut combiner plusieurs langages, chacun pour ce qu'il fait de mieux. Java pour ses applications de gestion, robustes et éprouvées. Scala pour le traitement de grandes quantités de données. Et Python pour l'analyse et la visualisation. Cette combinaison est très courante dans les entreprises modernes. Elle montre qu'un bon informaticien ne se limite pas à un seul langage, mais sait choisir l'outil adapté à chaque besoin. La polyvalence est un atout majeur.`,
// 10
`Faisons la synthèse du chapitre. Un langage de programmation est un langage formel, qui possède une syntaxe, une sémantique et une pragmatique. Il comprend aussi un système de types, un modèle d'exécution et des bibliothèques. Les langages se situent à différents niveaux, du langage machine aux langages de haut niveau. Et on les évalue selon plusieurs critères, notamment la lisibilité, l'expressivité, la sécurité, la performance, la portabilité et la maintenabilité. Ces critères guideront vos choix tout au long du cours.`,
// 11
`Voici les réponses au quiz. Qu'est-ce qu'un langage de programmation ? C'est un langage formel, fait de règles syntaxiques et sémantiques, qui permet d'écrire des programmes exécutés par une machine. Quelles sont ses composantes ? La syntaxe, la sémantique et la pragmatique, ainsi qu'un système de types, un modèle d'exécution et des bibliothèques. Et quels sont les critères d'évaluation ? La lisibilité, l'expressivité, la sécurité, la performance, la portabilité et la maintenabilité. Bravo si vous aviez tout juste. Passons au chapitre suivant.`,
// 12
`Passons au deuxième chapitre, consacré aux paradigmes de programmation. Un paradigme est un style, ou une approche, de la programmation. C'est une manière de penser et d'organiser un programme. Il en existe trois principaux, que nous allons étudier. Le paradigme impératif, le paradigme fonctionnel, et le paradigme orienté objet. Comprendre ces paradigmes est essentiel, car ils influencent profondément la façon dont on aborde un problème, bien plus encore que le choix d'un langage particulier. Voyons-les tour à tour, en commençant par le plus ancien.`,
// 13
`Commençons par le paradigme impératif. Il décrit un programme comme une suite d'instructions, qui modifient l'état de la machine, c'est-à-dire le contenu de sa mémoire. On dit à la machine, fais ceci, puis cela, étape par étape, comme une recette de cuisine. Les langages impératifs classiques sont C, Pascal et Fortran. Ses concepts clés sont les variables, qui stockent des valeurs, les affectations, qui modifient ces valeurs, et les boucles, qui répètent des instructions. C'est souvent le premier paradigme que l'on apprend.`,
// 14
`Le paradigme fonctionnel décrit un programme comme une composition de fonctions, au sens mathématique. Les fonctions y sont pures, elles n'ont pas d'effets de bord, c'est-à-dire qu'elles ne modifient rien en dehors d'elles-mêmes. Et les données sont immuables, on ne les modifie pas, on en crée de nouvelles. Les langages fonctionnels incluent Scheme, Haskell et Scala. Ses concepts clés sont les fonctions d'ordre supérieur, qui prennent d'autres fonctions en paramètre, la récursivité, et les types algébriques. Il est au coeur de ce cours.`,
// 15
`Le paradigme orienté objet décrit un programme comme une collection d'objets qui interagissent. Chaque objet encapsule des données, ses attributs, et des comportements, ses méthodes. Par exemple, un objet compte bancaire contient un solde, et propose des méthodes pour déposer ou retirer de l'argent. Les langages orientés objet incluent Java, C plus plus et Scala. Ses concepts clés sont les classes, qui servent de modèles aux objets, l'héritage, qui permet de réutiliser du code, et le polymorphisme. Il est très répandu en entreprise.`,
// 16
`Certains langages combinent plusieurs paradigmes. On les appelle des langages multi-paradigmes. C'est le cas de Scala, le langage de ce cours, qui combine la programmation fonctionnelle et la programmation orientée objet. On peut ainsi définir des classes et des objets, comme en Java, tout en utilisant des fonctions pures et des données immuables, comme en Haskell. Ce choix offre une grande souplesse au programmeur, et fait de Scala un excellent langage pour étudier les concepts de programmation. Petit quiz, Scala est-il fonctionnel ou objet ? Les deux.`,
// 17
`Comment choisir un paradigme ? Le choix dépend du problème à résoudre, des contraintes, et parfois des préférences de l'équipe. La programmation fonctionnelle est bien adaptée aux traitements de données, car les fonctions pures et les données immuables limitent les erreurs, et facilitent le calcul en parallèle. La programmation orientée objet convient aux systèmes complexes, avec de nombreuses entités qui interagissent. Et la programmation impérative convient aux systèmes de bas niveau, proches du matériel, où la performance est cruciale. Tout dépend du contexte.`,
// 18
`Voyons des exemples togolais. Les paradigmes sont utilisés selon les besoins. Pour le traitement de données, comme l'analyse de statistiques agricoles ou commerciales, on privilégie le fonctionnel, avec Scala ou Python. Pour les applications de gestion, comme la gestion des ressources humaines ou de la facturation, on privilégie l'orienté objet, avec Java. Et pour les systèmes embarqués, comme les équipements de mesure ou les automates, on privilégie l'impératif, avec le langage C, proche du matériel. Chaque paradigme a sa place.`,
// 19
`Voici une application au traitement de données. Une entreprise togolaise peut utiliser Scala, et son style fonctionnel, pour traiter de grandes quantités de données, par exemple des millions de transactions de paiement mobile. Elle peut parallèlement utiliser Java, et son style orienté objet, pour ses applications de gestion courante. Les deux langages fonctionnent d'ailleurs sur la même plateforme, la machine virtuelle Java, ce qui facilite leur collaboration au sein d'un même système d'information. Une belle complémentarité, et un vrai atout pour l'entreprise.`,
// 20
`Synthèse du chapitre. Les trois principaux paradigmes sont l'impératif, qui décrit une suite d'instructions modifiant l'état, le fonctionnel, qui compose des fonctions pures sur des données immuables, et l'orienté objet, qui fait interagir des objets encapsulant données et comportements. Scala est un langage multi-paradigme, qui combine fonctionnel et orienté objet. Enfin, le choix d'un paradigme dépend du problème à résoudre et des contraintes du projet. Aucun paradigme n'est supérieur dans l'absolu, chacun a son terrain de prédilection. Retenez bien ces trois styles.`,
// 21
`Voici les réponses au quiz. Quels sont les principaux paradigmes de programmation ? L'impératif, le fonctionnel et l'orienté objet. Qu'est-ce que le paradigme fonctionnel ? C'est un style qui décrit un programme comme une composition de fonctions pures, sans effets de bord, sur des données immuables. Et qu'est-ce qu'un langage multi-paradigme ? C'est un langage qui combine plusieurs paradigmes, comme Scala, qui réunit le fonctionnel et l'orienté objet. Bravo si vous aviez tout juste, passons au chapitre suivant. Allons-y.`,
// 22
`Abordons le troisième chapitre, consacré à la syntaxe, à la sémantique et à la pragmatique. Ce sont les trois dimensions de tout langage de programmation. On peut les comparer à une langue humaine. La syntaxe, c'est la grammaire, qui dit si une phrase est bien construite. La sémantique, c'est le sens de la phrase. Et la pragmatique, c'est l'usage que l'on en fait dans une situation concrète. Voyons chacune d'elles en détail, puis les erreurs qui leur correspondent. Commençons.`,
// 23
`La syntaxe définit les règles de formation des programmes. Elle précise comment les symboles, mots clés, opérateurs, parenthèses ou points-virgules, peuvent être combinés pour former des expressions et des instructions valides. Par exemple, en Scala, une parenthèse ouverte doit toujours être refermée. La syntaxe est généralement décrite par une grammaire formelle, que nous verrons dans un instant. Un programme syntaxiquement correct n'est pas forcément juste, mais au moins, il est bien formé, et le compilateur peut l'analyser. Elle est la première étape.`,
// 24
`La sémantique définit la signification des programmes, c'est-à-dire ce que fait un programme lorsqu'il est exécuté. Il existe trois grandes approches. La sémantique opérationnelle décrit comment le programme s'exécute, étape par étape. La sémantique dénotationnelle décrit quelle est la valeur mathématique du programme. Et la sémantique axiomatique décrit quelles propriétés le programme garantit, par exemple qu'un tri produit bien une liste ordonnée. Ces trois approches sont complémentaires, et nous y reviendrons lors des prochaines séances. Retenez ces trois mots.`,
// 25
`La pragmatique concerne l'utilisation concrète des programmes. Comment sont-ils compilés, exécutés, optimisés et débogués ? Elle inclut tous les aspects pratiques de la programmation, comme le choix des outils, la lisibilité du code, les conventions de nommage, ou la gestion de la mémoire. Deux programmes peuvent avoir la même sémantique, produire exactement le même résultat, mais différer fortement sur le plan pragmatique, par exemple l'un étant dix fois plus rapide, ou bien plus facile à maintenir que l'autre. Elle compte beaucoup.`,
// 26
`La syntaxe d'un langage est décrite par des grammaires formelles. Les plus connues sont la BNF, pour Backus-Naur Form, et sa version étendue, l'EBNF. Une grammaire définit des règles de production, qui génèrent tous les programmes valides du langage. Par exemple, une règle peut dire qu'une expression est soit un nombre, soit deux expressions reliées par un opérateur. Ces grammaires sont utilisées pour construire les compilateurs, qui vérifient automatiquement si un programme respecte la syntaxe du langage. Ce sont des outils puissants.`,
// 27
`Distinguons deux types d'erreurs. Les erreurs de syntaxe sont détectées à la compilation, avant même l'exécution, par exemple une parenthèse oubliée. Le compilateur refuse alors de produire le programme. Les erreurs de sémantique, elles, sont souvent détectées à l'exécution, par exemple une division par zéro. Mais attention, dans un langage fortement typé comme Scala, beaucoup d'erreurs de sémantique sont détectées dès la compilation, grâce au système de types. Par exemple, additionner un nombre et un booléen sera refusé immédiatement. C'est un grand avantage.`,
// 28
`Voyons pourquoi ces notions comptent au Togo, comme partout. Comprendre la syntaxe et la sémantique est important dans deux situations quotidiennes du développeur. Le débogage, d'abord, car il faut savoir distinguer une erreur de syntaxe d'une erreur de sémantique, pour la corriger efficacement. Et la compilation, ensuite, car il faut comprendre les messages d'erreur du compilateur, parfois cryptiques. Un développeur qui maîtrise ces notions gagne énormément de temps, et produit un code plus fiable pour ses clients. C'est un vrai savoir-faire.`,
// 29
`Voici une application au débogage. Un développeur togolais rencontre deux problèmes dans son programme. Le premier est un oubli de parenthèse. C'est une erreur de syntaxe, que le compilateur signale immédiatement, avec la ligne concernée. Le second est une division par zéro, lorsque le nombre d'élèves d'une classe vaut zéro. C'est une erreur de sémantique, qui n'apparaît qu'à l'exécution. Pour la prévenir, il doit vérifier cette valeur avant le calcul. Savoir les distinguer permet de choisir la bonne stratégie de correction.`,
// 30
`Synthèse du chapitre. La syntaxe définit les règles de formation des programmes, la sémantique leur signification, et la pragmatique leur utilisation concrète. Les grammaires formelles, comme la BNF et l'EBNF, décrivent la syntaxe. Les erreurs de syntaxe sont détectées à la compilation, et les erreurs de sémantique le plus souvent à l'exécution, sauf lorsque le système de types permet de les repérer plus tôt. Petit quiz, une variable utilisée avant d'être définie, c'est quelle erreur ? Une erreur sémantique, souvent détectée par le compilateur.`,
// 31
`Voici les réponses au quiz. Qu'est-ce que la syntaxe ? Ce sont les règles de formation des programmes, qui précisent comment combiner les symboles pour former des instructions valides. Qu'est-ce que la sémantique ? C'est la signification d'un programme, c'est-à-dire ce qu'il fait lorsqu'il est exécuté. Et quelle est la différence entre erreur de syntaxe et erreur de sémantique ? La première concerne la forme du programme, et se détecte à la compilation. La seconde concerne son sens, et se détecte souvent à l'exécution.`,
// 32
`Passons au quatrième et dernier chapitre, consacré à l'environnement de travail et à la prise en main de Scala. Ce cours utilise Scala trois comme langage principal. Scala est un langage moderne, qui fonctionne sur la machine virtuelle Java. Il est utilisé par de nombreuses entreprises, notamment pour le traitement de données à grande échelle. Ce chapitre présente l'installation, les bases du langage, les outils que vous utiliserez, et les règles à respecter pour les devoirs. Commençons par l'installation de votre environnement.`,
// 33
`Comment installer Scala trois ? Plusieurs options existent. Vous pouvez utiliser le gestionnaire de paquets de votre système, apt sous Linux, brew sous macOS, ou choco sous Windows. Vous pouvez aussi utiliser Coursier, l'outil d'installation officiel de Scala, qui installe tout le nécessaire en une seule commande. Pour l'environnement de développement, on recommande IntelliJ IDEA avec son extension Scala, ou VS Code avec l'extension Metals. Installez ces outils dès cette semaine, pour être prêts pour les exercices. Ne tardez pas.`,
// 34
`Voyons les bases de Scala. Comme nous l'avons vu, Scala combine la programmation fonctionnelle et la programmation orientée objet. On définit les valeurs avec deux mots clés. Val définit une valeur immuable, que l'on ne peut plus modifier une fois définie. Var définit une variable mutable, que l'on peut modifier. En Scala, on privilégie val, conformément à l'esprit fonctionnel. Enfin, on définit les fonctions avec le mot clé def, suivi du nom de la fonction, de ses paramètres et de son type de retour.`,
// 35
`Scala propose plusieurs types de base. Int, pour les nombres entiers, comme quarante-deux. Double, pour les nombres à virgule, comme trois virgule quatorze. Boolean, pour les valeurs vrai ou faux. String, pour les chaînes de caractères, comme un nom ou une phrase. Char, pour un caractère unique, comme une lettre. Et Unit, un type particulier, qui signifie qu'une fonction ne renvoie aucune valeur utile, un peu comme void en Java ou en C. Grâce à l'inférence de types, Scala devine souvent le type tout seul.`,
// 36
`Voici une idée fondamentale de Scala. En Scala, tout est expression. Une expression est une construction qui retourne une valeur. Même une condition if retourne une valeur, ce qui permet d'écrire, par exemple, que la mention vaut admis si la note est supérieure à dix, et ajourné sinon, en une seule ligne. Les blocs de code, entre accolades, sont aussi des expressions. Leur valeur est celle de la dernière expression du bloc. Cette approche rend le code plus concis, et plus proche des mathématiques.`,
// 37
`Le REPL est un outil précieux pour apprendre Scala. REPL signifie Read Eval Print Loop, c'est-à-dire lire, évaluer, afficher, et recommencer. Concrètement, vous tapez une expression, le REPL l'évalue immédiatement, et affiche son résultat et son type. Vous pouvez ainsi tester une idée en quelques secondes, sans écrire un programme complet. C'est l'outil idéal pour expérimenter, vérifier votre compréhension, et explorer le comportement du langage. Utilisez-le sans modération pendant vos révisions et vos exercices. Il est idéal pour débuter, et très pratique au quotidien.`,
// 38
`Parlons des fiches de travail, aussi appelées worksheets. Ce sont des exercices guidés, à compléter avant les devoirs. Elles vous permettent de pratiquer progressivement les notions vues en séance, avec des indications pour vous aider. Considérez-les comme un entraînement. Elles ne sont pas là pour vous piéger, mais pour vous préparer aux devoirs notés. Un conseil, faites-les régulièrement, au fil des séances, plutôt que toutes la veille d'un devoir. La programmation s'apprend par la pratique, pas par la lecture. Pratiquez chaque semaine.`,
// 39
`Voici une règle importante concernant les devoirs. Ils doivent être programmés en Scala trois. Attention, les soumissions écrites en Scala deux reçoivent zéro point. Scala trois a en effet introduit des changements de syntaxe importants, et le cours s'appuie sur ses nouveautés. Vérifiez donc soigneusement la version installée sur votre machine, et celle utilisée par votre environnement de développement, avant de commencer vos devoirs. Ce serait vraiment dommage de perdre tous ses points pour une simple question de version. Soyez vigilants.`,
// 40
`Voyons des exemples togolais. Au Togo, Scala peut être utilisé dans plusieurs domaines. Pour le traitement de données, par exemple l'analyse des données agricoles d'un projet comme le ProMAT, qui suit les rendements de nombreuses exploitations. Et pour les applications web, grâce au framework Play, qui permet de construire des sites et des services en ligne performants. Maîtriser Scala ouvre donc des perspectives professionnelles concrètes, notamment dans les métiers de la donnée, de plus en plus recherchés. Ce sont de belles opportunités.`,
// 41
`Voici une application concrète. Un développeur togolais peut utiliser Scala pour analyser les données de rendement agricole du ProMAT. Par exemple, à partir d'une liste de parcelles, il peut calculer en quelques lignes le rendement moyen par région, ou repérer les exploitations dont la production a le plus progressé. Grâce aux fonctions d'ordre supérieur, comme filter ou map, ces traitements s'écrivent de façon concise et lisible. C'est exactement le type de code que vous apprendrez à écrire dans ce cours.`,
// 42
`Synthèse du chapitre. Scala trois est le langage principal du cours. Il combine programmation fonctionnelle et orientée objet. Les valeurs sont soit immuables, définies avec val, soit mutables, définies avec var. Les fonctions sont définies avec def. Ses types de base sont Int, Double, Boolean, String, Char et Unit. En Scala, tout est expression. Et le REPL permet de tester des expressions de manière interactive. N'oubliez pas, les devoirs doivent impérativement être rendus en Scala trois. Retenez ces bases.`,
// 43
`Voici les réponses au quiz. Qu'est-ce que Scala ? C'est un langage de programmation multi-paradigme, qui combine fonctionnel et orienté objet, et qui fonctionne sur la machine virtuelle Java. Quelle est la différence entre val et var ? Val définit une valeur immuable, qui ne peut plus être modifiée, tandis que var définit une variable mutable. Et qu'est-ce que le REPL ? C'est un outil interactif, qui lit une expression, l'évalue, affiche son résultat, puis recommence. Bravo si vous aviez tout juste.`,
// 44
`Concluons cette première séance. Vous savez désormais ce qu'est un langage de programmation, et quelles sont ses composantes. Vous connaissez les trois grands paradigmes, impératif, fonctionnel et orienté objet. Vous savez distinguer la syntaxe, la sémantique et la pragmatique. Et vous avez pris en main Scala trois. Ces fondations sont essentielles pour la suite du cours, qui abordera les expressions et la sémantique. Installez votre environnement, testez le REPL, et à très bientôt. Bon travail à toutes et à tous, et bon courage.`,
];
