module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le chapitre trois du cours DSC trois cent quarante-cinq, consacré aux fondements de la régression supervisée. La régression est la première grande famille de problèmes supervisés. Elle consiste à prédire une valeur numérique continue, comme un prix, une température ou une consommation. Dans ce chapitre, nous étudierons le modèle le plus simple et le plus utilisé, la régression linéaire, ses hypothèses, son estimation, ses métriques d'évaluation, et deux pièges essentiels, le sous-apprentissage et le surapprentissage.`,
// 2
`Voici les objectifs pédagogiques de ce chapitre. Premièrement, comprendre le principe de la régression linéaire, simple et multivariée. Deuxièmement, savoir interpréter les coefficients d'un modèle de régression, c'est-à-dire l'effet de chaque variable sur la cible. Troisièmement, évaluer la performance d'un modèle de régression à l'aide des métriques appropriées, comme le RMSE et le R deux. Et quatrièmement, identifier les situations de surapprentissage et de sous-apprentissage, qui sont au coeur de toute démarche de Machine Learning. Commençons par le modèle lui-même.`,
// 3
`La régression linéaire suppose une relation linéaire entre une cible continue y et une ou plusieurs variables explicatives x. Dans le cas multivarié, la prédiction y chapeau est égale à bêta zéro, plus bêta un fois x un, plus bêta deux fois x deux, et ainsi de suite. Bêta zéro, l'ordonnée à l'origine, est la valeur prédite quand toutes les variables valent zéro. Chaque coefficient bêta i mesure l'effet marginal de la variable x i sur la cible, toutes choses égales par ailleurs. Par exemple, combien un mètre carré de plus ajoute au prix d'un appartement.`,
// 4
`La régression linéaire repose sur cinq hypothèses. La linéarité, la relation entre les variables et la cible est bien linéaire. L'indépendance des erreurs, les résidus ne sont pas corrélés entre eux. L'homoscédasticité, la variance des erreurs est constante. La normalité des résidus, importante pour l'inférence statistique. Et l'absence de forte multicolinéarité entre les variables explicatives, que nous approfondirons au chapitre quatre. Attention, si ces hypothèses ne sont pas respectées, le modèle peut rester prédictif, mais l'interprétation statistique des coefficients devient fragile.`,
// 5
`Comment estimer les coefficients ? Par la méthode des moindres carrés ordinaires. Elle choisit les coefficients qui minimisent la somme des carrés des écarts entre les valeurs observées et les valeurs prédites. Cette fonction de coût, notée J de bêta, est convexe. Cela garantit l'existence d'un minimum global unique. On peut l'atteindre de deux façons. Analytiquement, grâce à une formule appelée l'équation normale. Ou itérativement, par descente de gradient, comme nous l'avons vu au chapitre deux, ce qui est préférable lorsque le nombre de variables est très important.`,
// 6
`Comment évaluer un modèle de régression ? D'abord avec l'erreur quadratique moyenne, le MSE, qui est la moyenne des carrés des écarts entre valeurs réelles et prédites. Ensuite avec sa racine carrée, le RMSE. Son grand avantage est de s'exprimer dans la même unité que la cible, ce qui facilite l'interprétation. Un RMSE de quinze mille euros signifie que l'on se trompe en moyenne d'environ quinze mille euros. Notez que ces deux métriques pénalisent fortement les grandes erreurs, à cause de l'élévation au carré.`,
// 7
`Deuxième métrique, le coefficient de détermination, le R deux. Il est égal à un, moins le rapport entre la somme des carrés des erreurs du modèle et la somme des carrés des écarts à la moyenne. Il mesure la proportion de la variance de la cible expliquée par le modèle. Il vaut zéro si le modèle ne fait pas mieux que prédire la moyenne, et un pour un ajustement parfait. Attention, il peut même devenir négatif, si le modèle fait pire qu'une simple prédiction par la moyenne. Ce cas signale un modèle vraiment inadapté.`,
// 8
`Voici deux pièges fondamentaux. Le sous-apprentissage, ou underfitting, concerne un modèle trop simple pour capturer la structure des données. Son erreur est élevée, à la fois sur l'entraînement et sur le test. Le surapprentissage, ou overfitting, concerne un modèle qui mémorise le bruit des données d'entraînement. Son erreur est faible à l'entraînement, mais élevée sur des données nouvelles. L'objectif est de trouver le juste équilibre, souvent grâce à des courbes d'apprentissage. Retenez ce signal, une erreur faible à l'entraînement et élevée en validation indique un surapprentissage.`,
// 9
`Retenons les points clés. La régression linéaire multivariée modélise la cible comme une combinaison linéaire pondérée des variables explicatives. Les coefficients sont estimés en minimisant la somme des carrés des résidus, c'est la méthode des moindres carrés. Le MSE et le RMSE mesurent l'erreur moyenne, et le R deux mesure la proportion de variance expliquée. Enfin, le sous-apprentissage traduit un modèle trop simple, et le surapprentissage un modèle trop complexe, qui mémorise le bruit. Ces notions reviendront dans tous les chapitres suivants.`,
// 10
`Voici les corrigés. Premier exercice, un RMSE de quinze mille signifie que le modèle se trompe en moyenne d'environ quinze mille unités sur le prix, et un R deux de zéro virgule quatre-vingt-deux qu'il explique quatre-vingt-deux pour cent des variations de prix. Deuxième exercice, un RMSE de deux cents à l'entraînement contre huit cent cinquante au test révèle un surapprentissage. On peut simplifier le modèle, ou le régulariser, et ajouter des données. Troisième exercice, le R deux augmente toujours avec le nombre de variables. On utilise alors le R deux ajusté.`,
];
