module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le chapitre neuf du cours DSC quatre cent vingt-trois, consacré à l'utilisation avancée des logiciels statistiques pour l'analyse de données. Nous entrons dans la cinquième partie du cours, dédiée à l'outillage logiciel et au projet intégrateur. Jusqu'ici, nous avons surtout utilisé des commandes isolées. Nous allons maintenant apprendre à travailler comme un analyste professionnel, en automatisant nos analyses, en gérant les données manquantes, et en produisant des rapports reproductibles et bien documentés.`,
// 2
`Voici les objectifs de ce chapitre. Vous approfondirez vos compétences en programmation statistique, avec R ou Python. Vous apprendrez à automatiser des analyses, et à créer vos propres fonctions. Vous saurez gérer efficacement les données manquantes, grâce à l'imputation simple et multiple. Vous créerez des rapports reproductibles, avec R Markdown ou les notebooks Jupyter. Vous produirez des visualisations avancées de vos résultats. Et enfin, vous appliquerez les bonnes pratiques de codage et de documentation, pour garantir la reproductibilité de vos analyses.`,
// 3
`Pourquoi aller au-delà des commandes de base ? Parce que R et Python offrent bien plus que de simples commandes de régression. Maîtriser leurs fonctionnalités avancées vous permet d'automatiser les tâches répétitives, par exemple appliquer la même analyse à plusieurs variables. Vous pourrez personnaliser vos analyses et vos sorties selon vos besoins. Vous traiterez des données plus complexes et plus volumineuses. Vous produirez des rapports professionnels et reproductibles. Et surtout, vous gagnerez en efficacité et en fiabilité, en limitant les manipulations manuelles.`,
// 4
`Voyons la programmation avec R. Premier outil, la boucle. On définit un vecteur de noms de variables, puis, pour chaque variable, on construit une formule avec as formula et paste, on estime le modèle avec lm, et l'on range son résumé dans une liste. La fonction sapply extrait ensuite le R deux de chaque modèle. Deuxième outil, la fonction personnalisée. Ici, analyse regression prend un jeu de données, une variable dépendante et des variables explicatives, et renvoie les coefficients, le résumé et les résidus. On l'appelle ensuite en une seule ligne.`,
// 5
`Voici l'équivalent en Python. On importe pandas, statsmodels et numpy. Dans la boucle, pour chaque variable de la liste, on construit la matrice X avec une constante, on estime le modèle avec OLS, et l'on range le résultat dans un dictionnaire. On affiche ensuite le R deux de chaque modèle, avec trois décimales. On définit enfin la fonction analyse regression, documentée par une chaîne de description, qui renvoie les paramètres, le résumé et les résidus. Retenez l'idée, écrire une fois, puis réutiliser partout.`,
// 6
`Allons plus loin avec les fonctions et les packages. Les fonctions permettent de réutiliser du code, et de le rendre plus lisible. En R, pour créer un package, on utilise devtools, et roxygen deux pour la documentation. On voit ici une fonction documentée, avec son titre, la description de chaque paramètre, la valeur renvoyée, et une balise export. La fonction regression auto estime le modèle, produit les graphiques de diagnostic et les distances de Cook. En Python, on crée des modules réutilisables, et l'on distribue un package avec setuptools.`,
// 7
`Voici la même fonction en Python, dans un module nommé regression utils. Sa documentation décrit chaque paramètre, le jeu de données, la variable dépendante et les variables explicatives, ainsi que ce que la fonction renvoie. Le corps de la fonction estime le modèle avec OLS, récupère les résidus et les valeurs ajustées, puis crée une figure à deux panneaux. À gauche, les résidus contre les valeurs ajustées, avec une ligne rouge à zéro. À droite, le Q-Q plot. La fonction renvoie enfin le modèle, les résidus, le résumé et la figure.`,
// 8
`Abordons la gestion des données manquantes, très fréquentes en pratique. On distingue trois mécanismes. MCAR, manquant complètement au hasard, la probabilité de manquer est indépendante de toutes les variables, comme un capteur qui tombe en panne aléatoirement. MAR, manquant au hasard, elle dépend de variables observées, mais pas de la valeur manquante, par exemple les personnes âgées répondent moins souvent à la question du revenu. Et MNAR, elle dépend de la valeur elle-même, par exemple les très hauts revenus refusent de déclarer leur revenu.`,
// 9
`Quelles stratégies adopter ? La suppression par liste retire toute observation incomplète. Simple et sans biais si MCAR, elle perd de l'information et crée un biais sinon. La suppression par paires utilise toutes les données disponibles pour chaque calcul, mais peut être incohérente. L'imputation par la moyenne est simple, mais réduit la variance. L'imputation par régression exploite les relations entre variables, mais sous-estime la variance. Enfin, l'imputation multiple crée plusieurs jeux imputés, les analyse, puis combine les résultats. Elle tient compte de l'incertitude, c'est la méthode de référence.`,
// 10
`En R, la référence pour l'imputation multiple est le package mice. La fonction md pattern affiche la structure des données manquantes. La fonction mice réalise ici cinq imputations, avec la méthode pmm, l'appariement sur la moyenne prédite, et une graine fixée pour la reproductibilité. On vérifie les imputations avec plot. Puis la fonction with estime le modèle de régression sur chacun des cinq jeux imputés, et pool combine les résultats selon les règles de Rubin. Enfin, complete permet d'extraire un jeu de données complet.`,
// 11
`En Python, une approche simple utilise IterativeImputer, de scikit-learn. Comme elle est encore expérimentale, il faut d'abord importer enable iterative imputer. On crée ensuite l'imputateur, avec dix itérations au maximum et un état aléatoire fixé. Chaque variable incomplète est alors prédite à partir des autres, de manière itérative. La méthode fit transform impute les données, et l'on remet le résultat dans un tableau pandas, avec les noms de colonnes d'origine. Pour une vraie imputation multiple, on répète l'opération avec plusieurs graines.`,
// 12
`Passons à la reproductibilité, un pilier de la science des données. Un rapport reproductible présente quatre avantages. Il permet à d'autres chercheurs de vérifier et valider vos résultats. Il permet de réutiliser l'analyse sur de nouvelles données, sans effort supplémentaire. Il élimine les erreurs dues aux copier-coller et aux manipulations manuelles répétées. Et il fait gagner beaucoup de temps pour les rapports récurrents, grâce à l'automatisation. Imaginez un rapport mensuel, il suffit de relancer le document avec les nouvelles données.`,
// 13
`R Markdown est un format qui combine du texte, du code et ses résultats, tableaux et graphiques, dans un seul document. Il peut produire des rapports en HTML, en PDF ou en Word. Le document commence par un en-tête, avec le titre, l'auteur, la date et le format de sortie. Viennent ensuite des sections de texte, comme l'introduction, entrecoupées de blocs de code R. Ici, on charge les données Boston, on les décrit, on estime un modèle, et l'on affiche les graphiques de diagnostic. Le rapport se met à jour automatiquement.`,
// 14
`Les notebooks Jupyter sont l'équivalent Python de R Markdown. Ils combinent du texte, du code et des sorties interactives. Leurs fonctionnalités clés sont les cellules de code, en Python, en R ou en Julia, les cellules de texte en Markdown, les visualisations intégrées, et l'export en HTML ou en PDF. Dans cet exemple, une première cellule de texte donne le titre, une cellule de code charge les données, puis une autre estime le modèle et affiche son résumé. Le récit et le calcul avancent ensemble.`,
// 15
`Passons aux visualisations avancées, avec les graphiques interactifs. En R, le package plotly permet de créer un graphique interactif des résidus contre les valeurs ajustées. On précise le type de graphique, un nuage de points, la taille des marqueurs, puis le titre et les noms des axes. En Python, plotly express offre la même chose avec la fonction scatter, et l'on ajoute une ligne horizontale rouge en pointillés à zéro. L'intérêt, en survolant un point avec la souris, on identifie immédiatement l'observation concernée.`,
// 16
`Les tableaux synthétiques sont tout aussi importants pour communiquer. En R, le package stargazer produit un tableau comparatif de plusieurs modèles côte à côte, avec un titre, prêt à être intégré dans un rapport en HTML. La fonction kable, du package knitr, produit un tableau simple, par exemple les coefficients arrondis à trois décimales. En Python, on construit un tableau pandas avec les coefficients, les erreurs standards, les statistiques t et les p-values, on l'arrondit à quatre décimales, puis on l'exporte en HTML avec to html.`,
// 17
`Voici six principes de bonnes pratiques de codage. Un, écrire un code qui se lit comme un texte, avec des noms de variables clairs et explicites. Deux, commenter, en expliquant le pourquoi, et non le quoi, que le code dit déjà. Trois, structurer le code en sections logiques. Quatre, éviter la répétition, en utilisant des fonctions pour les tâches répétitives. Cinq, tester, en vérifiant que le code fonctionne sur des cas simples. Et six, versionner, en utilisant Git pour suivre toutes les modifications.`,
// 18
`Voici un exemple de script R bien documenté. Il commence par un en-tête, avec le titre, l'auteur, la date et une description de l'objectif. Il est ensuite découpé en sections numérotées. Un, le chargement des packages. Deux, le chargement des données. Trois, l'exploration initiale, statistiques descriptives et matrice de corrélation. Quatre, la construction du modèle, avec un commentaire qui justifie le choix des variables. Cinq, le diagnostic, résidus et points influents. Et six, la sauvegarde du modèle avec saveRDS. N'importe qui peut le relire et le comprendre.`,
// 19
`Et voici le même script en Python, avec la même structure. Un en-tête décrit l'analyse, son auteur, sa date et son objectif. On importe les bibliothèques, on charge les données, puis on explore avec describe et la matrice de corrélation. On construit ensuite le modèle avec OLS, et l'on affiche son résumé. Le diagnostic crée une grille de graphiques, avec les résidus contre les valeurs ajustées et le Q-Q plot. Enfin, on sauvegarde le modèle. Adoptez cette structure pour votre projet, vos correcteurs vous en remercieront.`,
// 20
`Résumons ce chapitre. La programmation avancée, avec les fonctions, les boucles et l'automatisation, fait gagner en efficacité et en fiabilité. La gestion des données manquantes est cruciale, et l'imputation multiple est la méthode de référence. Les rapports reproductibles, avec R Markdown ou Jupyter, garantissent la transparence et la réutilisabilité des analyses. Les visualisations avancées, interactives, et les tableaux synthétiques améliorent la communication des résultats. Et les bonnes pratiques de codage sont essentielles pour un travail professionnel. Au prochain chapitre, place au projet pratique.`,
];
