module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le Module neuf, consacré au calendrier éditorial et à l'organisation de la diffusion. Nous sommes le mercredi trente septembre deux mille vingt-six, et ce module dure trois heures. Il est animé par votre formateur principal, Pawou Batana, pour les Institutions et Fonds membres du RAFPRO. Vous savez désormais produire des contenus de qualité. Il s'agit maintenant d'organiser leur diffusion dans le temps, avec méthode.`,
// 2
`Voici comment nous répartirons nos cent quatre-vingts minutes. Vingt-cinq minutes pour comprendre la fonction du calendrier éditorial. Trente-cinq minutes pour définir les composantes d'un calendrier opérationnel. Trente minutes pour organiser le workflow, les responsabilités et la programmation. Puis un atelier principal de soixante-quinze minutes, où vous construirez votre propre calendrier. Et enfin quinze minutes de restitution, d'évaluation et de synthèse.`,
// 3
`Nous alternerons exposé interactif, analyse de tableaux, démonstration, travail en groupes et simulation de validation. Munissez-vous d'un ordinateur, d'un tableur ou d'un outil de planification, de vos chartes éditoriale et graphique, du calendrier de votre institution, et des contenus produits aux Modules cinq à huit. Le livrable principal est un calendrier opérationnel sur quatre semaines. Il vise le résultat d'apprentissage R A huit, organiser la production et la diffusion des contenus de façon cohérente avec vos objectifs et vos ressources.`,
// 4
`Commençons par la séquence un. Les Modules quatre à huit vous ont permis de définir une ligne éditoriale, de rédiger des contenus, de produire des visuels et des vidéos, d'adapter un message à plusieurs plateformes, et d'utiliser l'IA sous contrôle humain. Le Module neuf répond à une nouvelle question. Comment organiser ces productions dans le temps, et coordonner leur diffusion ? Une équipe peut produire d'excellents contenus, et échouer malgré tout si tout est improvisé. Produire un bon contenu ne suffit pas, il faut aussi organiser sa diffusion.`,
// 5
`À l'issue de ce module, vous saurez expliquer la fonction d'un calendrier éditorial, relier les publications aux objectifs, et définir des thématiques et des publics prioritaires. Vous saurez choisir les formats et les plateformes, déterminer une fréquence réaliste, et planifier les dates et les horaires. Vous saurez aussi répartir les responsabilités, organiser un workflow éditorial, utiliser un outil de planification, et élaborer un calendrier opérationnel. La compétence attendue est de transformer une stratégie en programme de publications organisé, attribué et contrôlable.`,
// 6
`Qu'est-ce qu'un calendrier éditorial ? C'est un outil de planification qui organise les contenus à produire et à diffuser sur une période donnée. Il précise les objectifs, les thématiques, les publics, les messages, les formats, les plateformes, les dates et horaires, les responsables, les échéances de production, les étapes de validation, et les statuts de publication. Il permet de passer d'une communication réactive à une communication préparée et coordonnée. Retenez qu'un bon calendrier est assez précis pour guider le travail quotidien de l'équipe.`,
// 7
`Le calendrier éditorial remplit cinq fonctions. Anticiper, en préparant les contenus avant les échéances importantes. Coordonner, en organisant les contributions des différents services. Assurer la cohérence, en reliant les publications aux objectifs et à la ligne éditoriale. Sécuriser la diffusion, en prévoyant les vérifications et les validations. Et suivre l'exécution, en identifiant les contenus prévus, produits, validés, publiés ou reportés. Par exemple, une campagne d'appel à candidatures peut être préparée plusieurs semaines à l'avance, plutôt que produite à la dernière minute.`,
// 8
`Distinguons trois outils complémentaires. Le calendrier institutionnel recense les événements, échéances et activités de l'institution. Le calendrier éditorial détermine les contenus à diffuser en lien avec ces activités. Et le planning de production organise les tâches, les responsables et les délais. Par exemple, une journée portes ouvertes le vingt novembre figure au calendrier institutionnel. Le calendrier éditorial prévoit une annonce, une présentation, un rappel et un bilan. Et le planning de production organise la rédaction, le visuel, la validation et la programmation.`,
// 9
`Faisons un exercice de cinq minutes. Identifiez les difficultés rencontrées dans votre institution. Les publications sont-elles décidées à la dernière minute ? Les informations arrivent-elles trop tard ? Manque-t-il un responsable clairement désigné ? Les validations prennent-elles du retard ? Les publications sont-elles irrégulières, ou contradictoires entre plateformes ? Et y a-t-il un suivi des publications ? Ensuite, demandez-vous quelles difficultés un calendrier bien conçu pourrait réduire. Je recueillerai quelques réponses, et nous les relierons à la séquence suivante.`,
// 10
`Voici la séquence deux, consacrée aux composantes du calendrier, pour trente-cinq minutes. Chaque publication doit contribuer à un objectif identifiable, comme faire connaître un programme, expliquer une procédure, informer sur une échéance, valoriser une réalisation, ou mobiliser les bénéficiaires. Par exemple, l'objectif est d'informer les responsables de PME de l'ouverture d'un programme, avec le message que les candidatures sont ouvertes. Le principe est clair. Ne commencez pas par remplir les cases, mais par définir ce que la communication doit accomplir.`,
// 11
`Les thématiques organisent les contenus autour de sujets récurrents. Pour un Fonds de formation, elles peuvent porter sur les programmes et dispositifs, les appels à candidatures, les modalités et procédures, les activités de formation, les réalisations documentées, les partenariats, les informations pratiques, et les témoignages autorisés. Par exemple, une semaine peut comporter une publication sur un programme, une publication pédagogique et une information pratique. Mais la répartition découle des priorités réelles, et non de l'obligation de couvrir toutes les thématiques chaque semaine.`,
// 12
`Chaque contenu doit être associé à un public. Un même programme peut concerner plusieurs publics, avec des informations différentes. Les bénéficiaires cherchent les conditions, les démarches et les échéances. Les entreprises veulent connaître les objectifs et les modalités de participation. Les partenaires s'intéressent aux activités et aux résultats. Le personnel interne a besoin d'informations de coordination. Et le grand public attend une présentation claire de la mission. Une règle importante. N'utilisez pas un public générique comme tout le monde, quand un contenu s'adresse en réalité à des destinataires précis.`,
// 13
`Chaque publication doit porter un message principal. Prenons le thème de l'ouverture d'un programme de formation. Le message principal est que les candidatures sont ouvertes pour les responsables de PME. Les informations complémentaires précisent le domaine, l'objectif du programme, la date limite, la source officielle et les modalités d'information. Ce message doit être formulé avant de choisir le visuel ou le format. Test simple, si le public ne retient qu'une seule information, laquelle doit-il retenir ?`,
// 14
`Le format se choisit selon l'objectif, le message et le canal. Pour une annonce officielle détaillée, un article ou une page web. Pour signaler une échéance, un visuel de rappel. Pour expliquer une procédure, une infographie ou un carrousel. Pour présenter une activité, une photographie légendée ou une vidéo. Pour développer un sujet, un article ou une vidéo explicative. Et pour une information pratique, un message bref. Un contenu complexe peut demander plusieurs formats complémentaires.`,
// 15
`Le choix des plateformes dépend des publics, des usages observés, des objectifs, des formats disponibles, des ressources de l'équipe et des règles institutionnelles. Par exemple, un appel à candidatures peut donner lieu à une page détaillée sur le site, une publication LinkedIn pour les professionnels, une publication Facebook pour la communauté de la page, et un message WhatsApp pour les destinataires concernés. Les faits restent identiques, mais la présentation s'adapte à chaque canal.`,
// 16
`La fréquence correspond au nombre de publications prévues sur une période. Elle doit tenir compte des objectifs, du volume d'informations utiles, des habitudes des publics, des capacités de production, des délais de validation et des résultats observés. Par exemple, une équipe peut commencer avec trois publications principales par semaine, puis ajuster selon ses capacités et ses résultats. La règle est de privilégier une fréquence soutenable et des contenus utiles, plutôt qu'un grand volume de publications peu pertinentes.`,
// 17
`Planifions maintenant les dates et les horaires. Une publication peut dépendre d'une date officielle, d'un événement, d'une échéance, d'une période de mobilisation, ou d'une information nouvellement validée. Par exemple, avec une date limite au quinze octobre, une campagne peut prévoir une annonce, une explication, un rappel avant l'échéance, et une dernière information pratique. Les horaires se fixent selon les contraintes institutionnelles et, si possible, les habitudes réelles des publics. Aucun horaire n'est optimal par principe.`,
// 18
`Une publication peut mobiliser plusieurs intervenants, et leurs rôles doivent être clairs. Le responsable de l'information fournit les données officielles. Le rédacteur prépare le texte. Le créateur visuel ou audiovisuel produit les éléments graphiques ou vidéo. Le relecteur vérifie la qualité et les informations. Le validateur habilité autorise la diffusion. Et le responsable de publication programme ou diffuse le contenu approuvé. Une même personne peut cumuler plusieurs fonctions, mais le calendrier doit toujours nommer des personnes ou des fonctions, et pas seulement un service.`,
// 19
`Voici les champs indispensables d'un calendrier éditorial, chacun répondant à une question. La référence, pour identifier le contenu. L'objectif, pourquoi publier. La thématique, de quoi parle-t-on. Le public, à qui s'adresse-t-on. Le message principal, ce que le public doit retenir. Le format, sous quelle forme. La plateforme, où publier. La date et l'heure, quand. Le responsable et le validateur, qui prépare et qui autorise. Le statut, où en est le contenu. Et le lien ou fichier, où trouver la version de référence.`,
// 20
`Passons à la séquence trois, consacrée au workflow, pour trente minutes. Un workflow éditorial est l'enchaînement organisé des tâches pour produire, vérifier, approuver et diffuser un contenu. Il répond à des questions précises. Qui déclenche la production ? Qui fournit les informations ? Qui rédige, et qui réalise le visuel ? Qui vérifie les faits ? Qui valide, qui publie, et qui archive la version finale ? Le calendrier indique quoi faire et quand, tandis que le workflow précise comment et par qui.`,
// 21
`Un workflow éditorial compte huit étapes. Un, l'expression du besoin, quand un service signale une information à communiquer. Deux, la collecte des informations et des sources officielles. Trois, la préparation éditoriale, avec l'objectif, le public, le message et les formats. Quatre, la production des textes, visuels et vidéos. Cinq, le contrôle des faits, des droits et de la conformité. Six, la validation par la personne habilitée. Sept, la programmation ou la publication. Et huit, l'archivage et le suivi. Une publication ne passe jamais directement de la production à la diffusion.`,
// 22
`Visualisons ce circuit de production. Tout commence au service source, qui détient l'information. L'équipe communication prend ensuite le relais pour produire le contenu. Vient le contrôle éditorial, puis le validateur habilité, qui autorise la diffusion. Et enfin la publication et le suivi. Un point important. En cas de correction demandée, le contenu ne saute pas d'étape. Il revient à l'étape appropriée, puis repasse par une nouvelle validation avant d'être publié.`,
// 23
`La date de publication n'est pas la seule échéance à inscrire au calendrier. Prévoyez aussi la date de réception des informations, la remise du texte, la livraison du visuel ou de la vidéo, la relecture, la validation et la programmation. Par exemple, pour une publication prévue le vendredi, on reçoit les informations le lundi, on rédige le mardi, on produit le visuel le mercredi, on contrôle et valide le jeudi, et on diffuse le vendredi. Un calendrier sans délai de validation devient vite irréalisable.`,
// 24
`Les statuts permettent de suivre l'avancement de chaque contenu. À préparer signifie que le travail n'a pas commencé. En production, que la rédaction ou la création est en cours. En relecture, que la vérification est en cours. En validation, que l'on attend la décision. Corrections demandées, que des modifications sont nécessaires. Validé, que la diffusion est autorisée. Programmé, que la publication est planifiée. Publié, qu'elle est en ligne. Et reporté ou annulé. Attention, programmé ne veut pas dire publié, car une programmation peut échouer.`,
// 25
`La programmation consiste à préparer la diffusion d'un contenu à une date et une heure déterminées. Elle peut se faire avec les fonctions natives d'une plateforme, avec un outil de gestion des réseaux sociaux, ou par une procédure interne de publication manuelle planifiée. Avant toute programmation, vérifiez que la version est validée, contrôlez les liens et le format des fichiers, confirmez la date, l'heure et le compte de destination, et assurez-vous que le contenu restera exact. Et après l'heure prévue, confirmez toujours que la publication est bien en ligne.`,
// 26
`Plusieurs catégories d'outils peuvent vous aider. Un tableur, pour construire un calendrier partagé et filtrable. Un calendrier partagé, pour visualiser les échéances. Un outil de gestion de tâches, pour attribuer et suivre les étapes. Un espace documentaire, pour centraliser les versions validées. Un outil de gestion des réseaux sociaux, pour programmer certaines publications. Et les fonctions natives des plateformes. Par exemple Excel, Google Sheets, Planner, Trello ou Meta Business Suite. Un tableur bien organisé reste un excellent point de départ.`,
// 27
`Comment gérer les imprévus sans désorganiser le calendrier ? Une institution peut devoir communiquer sur une modification de programme, un report, une décision officielle, une information urgente ou un événement imprévu. Voici la procédure recommandée. Identifiez la nouvelle priorité, vérifiez les informations, déterminez les publications affectées, et décidez des reports ou annulations. Préparez et validez le nouveau contenu, mettez à jour le calendrier, et informez les personnes concernées. Mais l'urgence ne dispense jamais du contrôle des faits ni des autorisations.`,
// 28
`Place maintenant à la séquence quatre, l'atelier principal, pour soixante-quinze minutes. Votre mission est de construire un calendrier éditorial applicable à une institution. Chaque groupe joue le rôle d'une équipe de communication, et prépare un calendrier de quatre semaines. Il comprendra au minimum trois objectifs, trois thématiques, deux publics, trois formats, deux plateformes, et douze publications planifiées, avec les responsables, les validateurs, les dates, les horaires et les statuts. Vous remettrez un tableau opérationnel, accompagné d'une courte justification de vos choix.`,
// 29
`Voici le cas pédagogique. Un Fonds national de formation veut organiser sa communication sur quatre semaines, avec trois priorités. Informer, en faisant connaître un programme en gestion financière et numérique destiné aux responsables de PME. Expliquer, en aidant les bénéficiaires à comprendre les démarches. Et valoriser, en présentant des activités à partir d'éléments documentés. La date limite fictive est le quinze octobre deux mille vingt-six, et les modalités sont dans la notice officielle. N'inventez ni résultats, ni chiffres, ni témoignages, ni conditions.`,
// 30
`Première étape, définir les objectifs et les publics. Chaque groupe remplit un tableau. Par exemple, faire connaître le programme auprès des responsables de PME, pour qu'ils identifient son existence. Expliquer les démarches aux candidats potentiels, pour qu'ils sachent où consulter les modalités. Et valoriser une activité documentée auprès des partenaires et de la communauté, pour qu'ils comprennent l'activité présentée. Vous pouvez adapter ces objectifs à votre institution. Votre livrable est une liste d'objectifs assez précis pour orienter vos publications.`,
// 31
`Deuxième étape, choisir les thématiques. Chaque groupe en définit au moins trois. Par exemple, les programmes et opportunités, les informations pratiques et procédures, et les activités et réalisations institutionnelles. Pour chacune, précisez son objectif, le public concerné, les informations réellement disponibles, et les formats envisageables. Puis posez-vous une question de contrôle. Chaque thématique contribue-t-elle bien à un objectif identifié ?`,
// 32
`Troisième étape, définir les formats et les plateformes. Voici un exemple. L'annonce d'ouverture prend la forme d'un article sur le site web. La présentation du programme devient une publication illustrée sur LinkedIn. Le rappel d'échéance est un visuel sur Facebook. Les informations pratiques passent par un message bref sur WhatsApp. Et l'explication d'une démarche peut prendre la forme d'un carrousel, sur la plateforme de votre choix. Justifiez vos choix par les publics, les usages et les ressources. Vous n'êtes pas obligés d'utiliser toutes les plateformes.`,
// 33
`Quatrième étape, définir la fréquence et répartir les publications. Votre calendrier couvre quatre semaines, avec au moins douze publications. Par exemple, trois publications par semaine. La première semaine est consacrée à l'annonce et à la présentation. La deuxième, à l'explication et aux informations pratiques. La troisième, à la valorisation et à l'approfondissement. Et la quatrième, aux rappels et au bilan. Demandez-vous si votre équipe pourra réellement produire et valider ces douze contenus.`,
// 34
`Cinquième étape, renseigner le calendrier éditorial. Pour chaque publication, complétez les champs suivants. La référence, par exemple P U B zéro zéro un. La semaine, l'objectif, la thématique, le public et le message, par exemple l'ouverture des candidatures. Puis le format, la plateforme, la date et l'heure de publication. Enfin, le responsable, le validateur, désignés par leur nom ou leur fonction, et le statut, à préparer. Votre livrable pour cette étape est une première version complète de votre calendrier sur quatre semaines.`,
// 35
`Voici un exemple de calendrier pour la première semaine. Le lundi, l'annonce d'ouverture du programme, sous forme d'article sur le site web, préparée par le rédacteur. Le mercredi, la présentation de l'intérêt du programme, en publication illustrée sur LinkedIn. Le vendredi, une information pratique sur la candidature, en visuel sur Facebook. Tous ces contenus sont au statut à préparer. Figurer au tableau ne rend pas un contenu prêt à publier.`,
// 36
`Sixième étape, répartir les responsabilités. Pour chaque tâche, désignez un responsable et une échéance. Qui fournit les informations ? Qui rédige ? Qui produit le visuel ou la vidéo ? Qui assure le contrôle factuel ? Qui valide ? Qui programme ? Et qui vérifie après publication ? Et retenez cette règle. Une responsabilité non attribuée constitue toujours un risque de retard.`,
// 37
`Septième étape, construire le workflow éditorial. Décrivez le parcours d'une publication, de la collecte à la rédaction, puis au contrôle et à la publication. Précisez qui intervient à chaque étape, comment les fichiers sont transmis, où se trouve la version de référence, qui demande les corrections, qui donne l'autorisation finale, et qui confirme la publication. Votre schéma doit être cohérent avec les responsabilités que vous avez inscrites dans votre calendrier.`,
// 38
`Huitième étape, prévoir la programmation et les contrôles. Avant programmation, vérifiez que le contenu est validé, que le fichier final est identifié, que le lien et le format sont corrects, que le compte de diffusion est le bon, et que la date et l'heure sont justes. Après publication, vérifiez que le contenu est bien en ligne, enregistrez le lien, mettez à jour le statut, signalez toute anomalie, et conservez la version finale. Et qui sera responsable du contrôle après diffusion ?`,
// 39
`Neuvième étape, vérifier la faisabilité de votre calendrier. Les publications contribuent-elles aux objectifs ? Les publics sont-ils clairement définis, et les thématiques cohérentes ? Les formats conviennent-ils aux plateformes ? Les dates tiennent-elles compte des échéances réelles ? Les responsables sont-ils désignés, et les délais de production réalistes ? Le circuit de validation est-il prévu ? Les ressources sont-elles disponibles ? Et le suivi après publication est-il organisé ? Corrigez tout élément irréaliste avant la restitution.`,
// 40
`Il est temps de présenter vos calendriers. Chaque groupe présente ses objectifs, ses publics prioritaires, ses thématiques, la répartition des douze publications, les plateformes et les formats, les responsabilités, le workflow de validation, et les principaux risques identifiés. Je vous poserai quelques questions. Le calendrier répond-il aux priorités de l'institution ? La fréquence est-elle soutenable ? Les délais de validation sont-ils réalistes ? Qui intervient en cas de correction ou de report ? Et pourrez-vous utiliser ce calendrier dès votre retour dans votre institution ?`,
// 41
`Voici la séquence cinq, pour quinze minutes, avec la grille d'évaluation de votre calendrier. Elle porte sur dix critères. L'alignement stratégique avec les objectifs, la pertinence des thématiques, l'identification des publics, le choix des formats et celui des plateformes. Puis la planification des dates et des fréquences, la répartition des responsabilités, l'organisation de la validation, la faisabilité, et le suivi opérationnel. Le standard attendu est un calendrier exploitable par une équipe, pour préparer, valider, programmer et suivre les contenus.`,
// 42
`Voyons les erreurs fréquentes en planification éditoriale, avec leur correction. Remplir le calendrier sans objectifs, il faut relier chaque publication à une finalité. Prévoir trop de contenus, il faut adapter la fréquence aux ressources. Oublier les délais de validation, il faut intégrer les échéances internes. Ne pas désigner de responsable, il faut attribuer chaque tâche. Copier le même contenu partout, il faut prévoir les adaptations. Confondre programmation et publication réussie, il faut vérifier la mise en ligne. Et ne jamais actualiser le calendrier, il faut le revoir régulièrement.`,
// 43
`Vérifions notre compréhension avec cinq questions. Un, quelle différence entre calendrier éditorial et institutionnel ? Le second recense les activités, le premier organise les contenus. Deux, pourquoi une date de validation distincte ? Pour permettre le contrôle et les corrections avant l'échéance. Trois, une publication programmée est-elle forcément publiée ? Non, il faut vérifier sa mise en ligne. Quatre, comment fixer une fréquence ? Selon les objectifs, les publics, les ressources et les résultats. Et cinq, qu'est-ce qui rend un calendrier opérationnel ? Des dates, des responsables, des validations, des statuts et un suivi.`,
// 44
`Résumons ce module en dix principes. Partir des objectifs, identifier les publics prioritaires, organiser les contenus par thématiques, et définir un message principal par publication. Choisir les formats et les plateformes avec pertinence, et adopter une fréquence réaliste. Planifier les dates de production, de validation et de diffusion. Attribuer clairement les responsabilités, suivre les statuts, et actualiser régulièrement le calendrier. Un calendrier éditorial opérationnel transforme vos intentions de communication en actions planifiées, coordonnées et vérifiables.`,
// 45
`Voici le modèle de calendrier à utiliser en atelier, que vous pouvez reproduire dans Excel, Google Sheets ou un autre outil autorisé. Il comprend l'identifiant, la date, l'heure, l'objectif, la thématique, le public, le message principal, le format, la plateforme, le responsable, le validateur et le statut. Trois lignes d'exemple sont proposées, pour le site web, LinkedIn et Facebook. Vous pouvez ajouter des champs, comme les dates de validation ou les liens, sur d'autres onglets.`,
// 46
`Pour finir, voici un exemple fictif de répartition sur quatre semaines, avec douze publications. La première semaine annonce le programme, présente ses objectifs, et renvoie à la notice. La deuxième explique la candidature, présente le public, et répond à une question fréquente. La troisième présente une activité documentée, un service du Fonds, et rappelle les informations. La quatrième propose un rappel d'échéance, une réalisation, et un bilan. Construisez toujours vos rappels autour de la véritable date limite. Merci à toutes et à tous pour votre engagement.`,
];
