module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le Module quinze, le dernier de notre formation, consacré à une mise en situation professionnelle intégratrice. Nous sommes le vendredi deux octobre deux mille vingt-six, et ce module dure trois heures. Il est animé par votre formateur principal, Pawou Batana, pour les Institutions et Fonds membres du RAFPRO. C'est le moment de mobiliser ensemble tout ce que vous avez appris depuis cinq jours.`,
// 2
`Voici votre mission. Vous êtes l'équipe de communication d'une institution fictive de formation professionnelle. La direction vous demande de faire connaître un nouveau programme, d'aider les publics à comprendre les modalités de candidature, et de les orienter vers la page d'information officielle. Votre responsabilité est de proposer un dispositif cohérent, publiable après validation, mesurable et améliorable.`,
// 3
`À l'issue de cette épreuve, vous devrez démontrer votre capacité à analyser les objectifs et les publics, élaborer une stratégie de contenu, et définir une ligne éditoriale. Vous produirez un contenu professionnel, l'adapterez à plusieurs plateformes, et organiserez sa diffusion dans un calendrier. Vous modérerez, utiliserez l'IA de manière responsable, analyserez des KPI, et formulerez des recommandations. L'enjeu est de relier toutes ces compétences, plutôt que de produire dix réponses indépendantes.`,
// 4
`Voici le dossier professionnel à remettre, qui comprend dix pièces. Un diagnostic des objectifs, des publics, des besoins et des canaux. Une mini-stratégie de contenu. Une ligne éditoriale opérationnelle. Une publication rédactionnelle, avec une proposition de visuel ou de vidéo courte. Une déclinaison du message sur deux plateformes. Un calendrier éditorial. Une réponse de modération. Une note de contrôle qualité, un tableau de bord analysé, et des recommandations priorisées. Vos livrables doivent pouvoir être examinés par une direction de la communication.`,
// 5
`Voici les règles de l'épreuve. Utilisez exclusivement les faits fournis pour décrire le programme fictif. N'inventez aucune condition d'admission, aucun financement, aucune date ni aucun résultat. Distinguez les informations confirmées de celles à vérifier. Justifiez vos choix de publics, de canaux et de formats. Déclarez l'usage éventuel d'un outil d'IA, et vérifiez humainement toute production assistée. Retenez que la qualité professionnelle repose autant sur la fiabilité que sur la créativité.`,
// 6
`Voici une répartition des rôles, que vous pouvez adapter. Le coordinateur veille à la cohérence du dossier et à la gestion du temps. L'analyste stratégie travaille sur les objectifs, les publics et le choix des canaux. Le responsable éditorial prend en charge la ligne éditoriale et les contenus. Le responsable diffusion gère calendrier et modération, et l'analyste performance les KPI et les recommandations. Point important, chacun doit pouvoir expliquer l'ensemble du dispositif, et pas seulement sa propre partie.`,
// 7
`Voici la feuille de route de nos trois heures. Quinze minutes pour comprendre la mission. Trente minutes pour diagnostiquer et concevoir. Quarante-cinq minutes pour produire et planifier. Trente-cinq minutes pour modérer, mesurer et améliorer. Trente-cinq minutes pour présenter et défendre vos choix. Et vingt minutes pour vérifier les acquis individuels. Une consigne importante. Ne consacrez pas tout votre temps à la création graphique. L'évaluation porte sur l'ensemble du cycle.`,
// 8
`Présentons l'institution fictive, l'Institut Horizon Compétences, ou IHC. Sa mission, dans cet exercice, est de faciliter l'accès à la formation professionnelle. Elle prépare la communication d'un nouveau programme intitulé Compétences numériques pour l'emploi, Les informations confirmées sont les suivantes. Une page officielle existe, les candidatures sont ouvertes, les modalités figurent sur cette page, et le service du programme répond aux questions. En revanche, le nombre de places, le coût, l'éligibilité, les aides et la date de clôture ne sont pas fournis. Ne les inventez pas.`,
// 9
`Voici la demande de la direction. Elle souhaite que les publics concernés connaissent l'existence du programme, comprennent où consulter les modalités officielles, et puissent poser leurs questions. Votre travail est de transformer cette demande en objectifs de communication, d'identifier les publics, de sélectionner les canaux, de définir les messages, et de proposer des indicateurs de suivi. Attention, publier trois fois par semaine serait une modalité d'action, et non un objectif de communication.`,
// 10
`Le cas comprend trois publics. Le public A, ce sont les candidats potentiels, des personnes qui veulent acquérir ou renforcer des compétences numériques. Ils ont besoin de comprendre le programme, d'accéder aux modalités, et de savoir où poser leurs questions. Le public B, ce sont les entreprises et partenaires, qui peuvent relayer l'information et ont besoin d'un lien officiel fiable. Et le public C, ce sont les relais institutionnels, qui ont besoin d'un message clair et réutilisable. Priorisez-les de façon argumentée, sans inventer de données démographiques.`,
// 11
`Premier travail, formuler les objectifs, en sept minutes environ. Chaque équipe formule un objectif d'exposition de l'information, un objectif d'orientation vers la page officielle, et un objectif de relation avec les publics. Par exemple, faire connaître l'existence du programme auprès des publics prioritaires. Générer des visites vers la page officielle d'information. Et faciliter la réception et le traitement des questions des publics. Pour chaque objectif, précisez ensuite le public visé, le canal envisagé, et le KPI correspondant.`,
// 12
`Deuxième travail, élaborer la mini-stratégie, en dix minutes. Répondez à huit questions. Quel est l'objectif prioritaire ? Quel est le public prioritaire ? Quel est son besoin informationnel ? Quel message doit être retenu ? Quelle catégorie de contenu, annonce, explication, foire aux questions ou témoignage ? Sur quelle plateforme ? Quel appel à l'action ? Et quel KPI pour suivre le résultat ? Message central possible. Le programme Compétences numériques pour l'emploi est ouvert aux candidatures, consultez la page officielle pour connaître les modalités.`,
// 13
`Troisième travail, définir la ligne éditoriale, en huit minutes. Elle doit préciser les thématiques prioritaires, le ton et le style, les formats, les règles de vérification et de publication, et les principes de cohérence entre plateformes. Voici une proposition à discuter. Les thématiques, la présentation du programme, les modalités officielles et les réponses aux questions fréquentes. Le ton, institutionnel, clair, accessible et respectueux. Et une règle essentielle, les informations sur l'admission et le financement doivent être confirmées avant toute publication.`,
// 14
`Avant de produire les contenus, vérifiez la cohérence stratégique de votre dispositif. L'objectif est-il distinct de l'activité, avec un résultat clairement formulé ? Le public est-il caractérisé, avec ses besoins précisés ? Le message répond-il à ces besoins, en orientant vers une information utile ? Le canal est-il justifié par le public et l'objectif ? Et les faits sont-ils vérifiés, avec les inconnues clairement signalées ? La règle est simple. Corrigez toute incohérence avant de passer à la production.`,
// 15
`Premier point de contrôle du formateur, sur les résultats d'apprentissage un, deux et trois. Pour le R A un, analyser les enjeux, les objectifs et les publics, j'attends des objectifs identifiés, des publics caractérisés, des besoins analysés et des canaux justifiés. Pour le R A deux, élaborer une stratégie de contenu, j'attends une articulation claire de tous les éléments. Et pour le R A trois, élaborer une ligne éditoriale, j'attends des thématiques, un ton, un style, des formats et des règles de publication réellement applicables.`,
// 16
`Passons maintenant à la production. Chaque équipe doit préparer quatre éléments. Premièrement, une publication rédactionnelle principale, qui annonce le programme et oriente vers la page officielle. Deuxièmement, une proposition de visuel ou de vidéo courte, avec un message, une structure et un appel à l'action. Troisièmement, deux déclinaisons adaptées à des plateformes différentes, en conservant le message essentiel. Et quatrièmement, un calendrier éditorial, avec les publications, les responsabilités et les validations. Un storyboard peut suffire pour la vidéo.`,
// 17
`Quatrième travail, rédiger la publication principale, en dix minutes. Elle comprend une accroche claire, l'annonce du programme, une information confirmée, un appel à l'action, un renvoi vers la page officielle, et une formulation respectueuse. Voici un exemple. Vous souhaitez renforcer vos compétences numériques professionnelles ? L'Institut Horizon Compétences ouvre les candidatures à son programme Compétences numériques pour l'emploi. Retrouvez les modalités sur la page officielle du programme. Surtout, n'ajoutez aucune promesse d'emploi, de gratuité ou de date limite non confirmée.`,
// 18
`Cinquième travail, concevoir un visuel ou une vidéo courte, en dix minutes. Pour l'option visuel, définissez un titre, un message principal, une hiérarchie visuelle, l'identité institutionnelle, un appel à l'action et la source officielle. Pour l'option vidéo, préparez le message central, une accroche, trois à cinq séquences, un texte de voix off ou des sous-titres, et un appel à l'action final. Votre proposition doit pouvoir être produite sans inventer de faits, et sans utiliser d'images ni de témoignages sans autorisation appropriée.`,
// 19
`Voici un exemple de storyboard en cinq séquences. La première pose une accroche, vous souhaitez développer vos compétences numériques ? La deuxième présente le nom du programme. La troisième donne une information confirmée, les candidatures sont ouvertes. La quatrième oriente, consultez les modalités sur la page officielle. Et la cinquième affiche le lien officiel vérifié et l'identité de l'institution, comme appel à l'action. N'ajoutez pas d'images de bénéficiaires réels ou de témoignages nominatifs sans vérifier les autorisations et les règles applicables.`,
// 20
`Sixième travail, adapter le message à deux plateformes, en dix minutes. Choisissez deux plateformes pertinentes et justifiez votre choix. Par exemple, sur LinkedIn, l'angle est une présentation institutionnelle, avec une publication structurée et un lien vers les modalités. Sur Facebook, l'angle est une information pratique, avec un visuel, un texte concis et un lien. Ce qui ne change pas, ce sont le nom du programme et les faits confirmés. Adaptez la présentation, jamais les informations essentielles.`,
// 21
`Avant toute diffusion, contrôlez la qualité de vos contenus. Vérifiez l'exactitude du nom du programme, la cohérence des informations, le fonctionnement du lien, et l'absence de promesse non confirmée. Vérifiez aussi la lisibilité, l'identité institutionnelle, les droits sur les images, l'absence de données confidentielles, et la validation par les personnes compétentes. Retenez ce message clé. Prêt à publier signifie prêt à être soumis au circuit de validation, et non autorisation automatique de diffusion.`,
// 22
`Septième travail, construire un calendrier éditorial pour une semaine de campagne, en dix minutes. Par exemple, le premier jour, annoncer l'ouverture des candidatures avec un visuel et un texte, suivi par la portée. Le troisième jour, expliquer où trouver les modalités, avec un carrousel ou une vidéo, suivi par les clics. Le cinquième jour, répondre aux questions fréquentes vérifiées, suivi par les interactions pertinentes. Et le septième jour, rappeler l'accès à la page officielle, suivi par les clics. Adaptez-le aux capacités de votre équipe.`,
// 23
`Organisez ensuite le circuit de production et de validation. Il part du brief, qui définit les objectifs et les livrables, passe par la rédaction du contenu principal, puis par la vérification des faits et des liens, et enfin par le contrôle des visuels et du style. Posez-vous plusieurs questions. Qui confirme les modalités du programme ? Qui vérifie les liens ? Qui contrôle les visuels ? Qui valide le message final ? Et qui surveille les interactions ? Un calendrier doit préciser les responsabilités, et pas seulement les dates.`,
// 24
`Deuxième point de contrôle du formateur, sur les R A quatre, cinq, six et huit. Pour le R A quatre, produire des contenus professionnels, j'observerai la clarté, l'adaptation au public, et la qualité. Pour le R A cinq, adapter les contenus, le maintien du message essentiel et l'adaptation du format et du ton. Pour le R A six, planifier la diffusion, un calendrier réaliste avec responsabilités et échéances. Et pour le R A huit, utiliser les outils et l'IA de manière responsable, le contrôle humain, l'exactitude, les droits et la confidentialité.`,
// 25
`Une situation sensible apparaît maintenant. Sous votre annonce, un internaute écrit que vous annoncez ce programme sans dire s'il est gratuit, et qu'on leur fait encore perdre leur temps. Or votre dossier ne précise pas le coût du programme. Qualifiez la situation, proposez une réponse publique, identifiez l'information à vérifier et les conditions d'escalade. La règle est claire. Ne répondez ni que le programme est gratuit, ni qu'il est payant, sans confirmation.`,
// 26
`Huitième travail, rédiger la réponse de modération, en sept minutes. Voici un exemple. Bonjour, merci pour votre message. Nous comprenons que les modalités du programme soient importantes pour votre décision. Nous faisons vérifier ce point auprès du service concerné, afin de vous orienter vers une information officielle et à jour. En interne, transmettez la question au service compétent, obtenez une réponse validée, répondez publiquement avec l'information confirmée, et vérifiez si d'autres personnes posent la même question. Et si la page officielle ne contient pas encore l'information, ne prétendez pas qu'elle la fournit.`,
// 27
`Vérifiez la qualité de votre modération. Une réponse adaptée reconnaît la question sans dénigrer son auteur, garde un ton respectueux, n'invente aucun fait, et indique une démarche de vérification. Elle prévoit aussi l'escalade, la protection des données et le suivi. À l'inverse, évitez de supprimer une critique simplement parce qu'elle est négative, de répondre de manière défensive, de communiquer des informations non validées, ou de demander des données personnelles sensibles dans un commentaire public.`,
// 28
`Passons à la mesure, avec les données fictives de la campagne. L'annonce A a une portée de douze mille, quatre cent cinquante interactions et quatre-vingt-dix clics. La vidéo B a huit mille de portée, quatre cents interactions et cent soixante clics. Le carrousel C a six mille de portée, deux cent quarante interactions et deux cent quarante clics. Et le témoignage D a dix mille de portée, cinq cents interactions et cent clics. Les cibles fictives sont de sept cents clics et de mille cinq cents interactions.`,
// 29
`Neuvième travail, sélectionner et calculer les KPI, en huit minutes. Choisissez un KPI principal pour l'objectif d'orientation vers la page. Calculez le total des clics et le total des interactions. Comparez ces deux totaux aux cibles. Identifiez le contenu qui génère le plus de clics. Et signalez deux limites de votre analyse. Utilisez les formules d'écart et de taux de réalisation vues au Module quatorze.`,
// 30
`Voici la correction. Pour les clics, le total est de cinq cent quatre-vingt-dix. L'écart est de moins cent dix par rapport à la cible de sept cents, et le taux de réalisation est d'environ quatre-vingt-quatre virgule vingt-neuf pour cent. Pour les interactions, le total est de mille cinq cent quatre-vingt-dix, soit un écart de plus quatre-vingt-dix, et un taux de réalisation de cent six pour cent. Le carrousel C génère le plus de clics. Mais attention, les visites réelles et les candidatures ne peuvent pas être établies à partir de ce tableau.`,
// 31
`Dixième travail, formuler trois recommandations, en dix minutes. Au moins une doit porter sur le contenu ou son adaptation, une sur le parcours d'information ou la qualité des données, et une sur l'organisation ou le suivi de la campagne. Chaque recommandation suit la structure, constat, justification, action, priorité, responsable, et KPI de suivi. Justifiez-les par vos constats, sans présenter vos hypothèses comme des causes établies.`,
// 32
`Voici un exemple de note d'amélioration. Le carrousel C génère deux cent quarante clics, on recommande donc de tester un second contenu pratique, suivi par les clics et le taux de clics. Les visites du site ne sont pas disponibles, on recommande donc de vérifier le dispositif de suivi du trafic. Et une question importante sur le coût reste sans réponse confirmée, on recommande donc de faire valider une information officielle et d'actualiser la foire aux questions.`,
// 33
`Troisième point de contrôle du formateur, sur les R A sept, neuf et dix. Pour le R A sept, animation et modération, j'attends une réponse appropriée, un ton professionnel, un traitement proportionné et une escalade si nécessaire. Pour le R A neuf, mesure et analyse, des KPI pertinents, des calculs corrects, des comparaisons cohérentes et des conclusions étayées. Et pour le R A dix, recommandations, un diagnostic des forces et insuffisances, un lien clair entre données et actions, et des recommandations faisables et priorisées.`,
// 34
`Préparons maintenant la restitution. Chaque équipe dispose de cinq minutes de présentation et de cinq minutes de questions, puis je ferai une synthèse. Voici le plan recommandé. D'abord les objectifs et les publics. Puis la stratégie et la ligne éditoriale. Ensuite les contenus et leurs adaptations. Puis le calendrier et la modération. Et enfin les KPI, les constats et les recommandations. Présentez vos choix les plus importants et leurs justifications, sans lire intégralement votre dossier.`,
// 35
`Préparez-vous à défendre vos choix professionnels. Je pourrai vous demander pourquoi vous avez retenu ce public comme prioritaire, quel besoin votre contenu traite, et pourquoi vous avez choisi ces plateformes. Je pourrai aussi interroger vos adaptations, vos validations et votre réponse de modération. Enfin, quel KPI correspond à l'objectif principal, et quelle recommandation découle directement des données ? Justifier ses choix fait partie de la compétence professionnelle.`,
// 36
`Voici la grille d'observation de la restitution, en huit dimensions. La cohérence, les éléments du dispositif se répondent-ils ? La fiabilité, les faits sont-ils vérifiés ou signalés comme inconnus ? La pertinence, les choix correspondent-ils aux objectifs et aux publics ? L'opérationnalité, contenus et calendrier sont-ils exploitables ? La mesure, les calculs sont-ils corrects ? L'amélioration, les recommandations sont-elles argumentées ? Et la maîtrise individuelle, chacun peut-il expliquer ses choix ?`,
// 37
`Pour chaque équipe, mon retour professionnel distinguera quatre éléments. Les acquis démontrés, c'est-à-dire les compétences pour lesquelles des preuves suffisantes ont été observées. Les points à consolider, c'est-à-dire les compétences partiellement démontrées ou insuffisamment justifiées. Les corrections prioritaires, comme des erreurs factuelles ou de calcul. Et les bonnes pratiques transférables, que vous pourrez réutiliser dans votre environnement professionnel. Ce retour sera précis, et toujours relié à des productions ou des comportements observables.`,
// 38
`Passons à la vérification individuelle des acquis, pendant douze minutes. Question un, expliquez la différence entre un objectif de communication et une activité de publication. Question deux, indiquez deux règles qui garantissent la cohérence d'un message entre plateformes. Question trois, que faites-vous si l'IA propose une date de clôture absente du dossier ? Question quatre, comment répondre sur le coût quand l'information n'est pas confirmée ? Question cinq, pourquoi cinq cent quatre-vingt-dix clics ne prouvent pas cinq cent quatre-vingt-dix visites ? Et question six, quelle recommandation tirer des deux cent quarante clics du carrousel ?`,
// 39
`Parlons de l'évaluation intégratrice, qui couvre les R A un à dix. Le syllabus définit une évaluation critériée. Un résultat d'apprentissage est atteint lorsque vous avez démontré, par des preuves suffisantes, que vous satisfaites aux critères essentiels. Chaque R A correspond à une preuve dans votre dossier, du diagnostic pour le R A un, jusqu'à la note de recommandations pour le R A dix. La décision d'évaluation sera établie individuellement, sur la base des preuves recueillies.`,
// 40
`Faisons maintenant la synthèse finale de ces cinq journées. Notre formation a suivi un cycle complet de communication digitale institutionnelle. Analyser, planifier, concevoir, produire, diffuser, animer, mesurer, et améliorer. Retenez ce message final. Une communication digitale institutionnelle professionnelle est cohérente avec la mission de l'institution, utile à ses publics, fiable dans ses contenus, responsable dans ses interactions, et pilotée à partir de résultats mesurables. Merci pour votre engagement tout au long de cette formation.`,
// 41
`Pour construire votre dossier, vous disposez de plusieurs modèles. Le premier est le canevas du dossier intégrateur. Il comprend ensuite le diagnostic, avec la demande institutionnelle, vos trois objectifs, le public prioritaire, ses besoins et les canaux retenus. Puis la mini-stratégie, avec le message principal, les messages secondaires, les catégories de contenus, les plateformes, les appels à l'action et les KPI.`,
// 42
`La suite du canevas porte sur la ligne éditoriale et la production des contenus. Pour la ligne éditoriale, précisez les thématiques, le ton, le style, les formats, et les règles de vérification et de publication. Pour la production, présentez votre publication principale, votre concept de visuel ou votre storyboard vidéo, ainsi que la liste des informations qui doivent encore être validées avant diffusion.`,
// 43
`La partie suivante porte sur l'adaptation multicanale et le calendrier. Pour chacune de vos deux plateformes, présentez la version du contenu et la justification de l'adaptation, puis le message essentiel conservé. Pour le calendrier, indiquez la période, les publications prévues, les responsables, les échéances, le circuit de validation, et le KPI de chaque publication.`,
// 44
`Vient ensuite la partie modération et outils numériques. Pour la modération, précisez la nature du commentaire, la réponse publique proposée, l'information à vérifier, le responsable de l'escalade et le suivi prévu. Pour les outils, indiquez ceux que vous avez utilisés, l'usage éventuel de l'IA, les vérifications humaines réalisées, les droits à vérifier, et les mesures de confidentialité.`,
// 45
`La dernière partie du canevas porte sur la mesure et les recommandations. Indiquez l'objectif mesuré, le KPI principal, la cible, le résultat, l'écart, le taux de réalisation, vos constats et les limites des données. Puis présentez vos trois recommandations, chacune avec sa justification, sa priorité, son responsable et son KPI de suivi. Terminez par une déclaration indiquant que les informations non confirmées ont été signalées, et que vos contenus restent soumis aux validations institutionnelles.`,
// 46
`Le modèle B est la fiche individuelle d'observation des compétences, utilisée par le formateur. Pour chaque R A, de un à dix, elle précise la preuve recherchée, comme l'analyse des objectifs et des publics, la stratégie, la ligne éditoriale, le contenu, l'adaptation, le calendrier, la modération, le contrôle humain, les calculs, et les recommandations. Elle s'appuie sur l'ensemble de vos preuves, et pas seulement sur votre présentation orale.`,
// 47
`Enfin, le modèle C est une liste de contrôle à cocher avant de remettre votre dossier. Vos objectifs sont-ils distincts des activités ? Vos publics sont-ils caractérisés ? Votre stratégie relie-t-elle objectifs, publics, messages et canaux ? Vos contenus sont-ils exempts de toute information inventée ? Vos adaptations préservent-elles le message ? Votre calendrier précise-t-il les responsabilités ? Et chacun peut-il expliquer vos choix ? Bonne réussite à toutes et à tous, et merci pour cette belle formation.`,
];
