module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le Module douze, consacré à l'e-réputation et à la communication digitale responsable. Nous sommes toujours le jeudi premier octobre deux mille vingt-six, et ce module dure deux heures. Il est animé par votre formateur principal, Pawou Batana, pour les Institutions et Fonds membres du RAFPRO, avec l'appui de la FNAFPP. Après avoir appris à gérer les situations sensibles, nous allons maintenant nous intéresser à la prévention, c'est-à-dire à tout ce qui permet de protéger la confiance du public avant même qu'un problème n'apparaisse.`,
// 2
`Le Module onze a montré comment traiter une interaction sensible lorsqu'elle apparaît. Le Module douze pose une question complémentaire. Comment réduire les risques avant qu'ils ne se produisent, et détecter assez tôt les signaux qui exigent une action ? Une institution peut connaître des difficultés de réputation à cause d'une information inexacte, d'un message ambigu, d'une réponse tardive, d'une publication non autorisée, d'un usage inapproprié d'une image, d'une exposition de données, ou d'un contenu produit avec l'IA sans vérification. Protéger l'e-réputation commence donc par des pratiques fiables et responsables.`,
// 3
`À l'issue de ce module, vous saurez distinguer identité numérique, image et réputation, identifier les sources utiles à une veille, reconnaître les principaux risques réputationnels, et proposer des mesures de prévention. Vous saurez aussi vérifier les conditions d'utilisation d'un contenu tiers, appliquer les précautions liées au droit à l'image, protéger les données confidentielles, et contrôler les contenus assistés par IA. Enfin, vous saurez analyser un risque et élaborer un dispositif de réponse et de suivi. La compétence attendue est d'intégrer la prévention et la responsabilité éditoriale dans le fonctionnement quotidien de votre service.`,
// 4
`Distinguons trois notions. L'identité numérique, c'est l'ensemble des éléments qui représentent l'institution en ligne, comme son site, ses comptes officiels, son nom, son logo et ses publications. L'image institutionnelle, c'est la perception de l'institution par ses publics à un moment donné, par exemple une institution perçue comme accessible ou difficile à joindre. Et l'e-réputation, ce sont les perceptions et appréciations qui se construisent et circulent en ligne au fil du temps, à travers les avis, les commentaires ou les articles. Retenez-le bien. Maîtriser ses propres contenus ne signifie pas maîtriser l'ensemble de sa réputation.`,
// 5
`Où se construit l'e-réputation ? Sur le site institutionnel et les comptes officiels, bien sûr, mais aussi dans les commentaires sous les publications, les articles de presse en ligne, les publications des partenaires, les témoignages des bénéficiaires, les résultats des moteurs de recherche, les espaces de discussion accessibles, et dans les réponses apportées par l'institution elle-même. Par exemple, une notice difficile à trouver provoque des questions répétées. Si elles restent sans réponse, elles nourrissent une perception négative du service. Les expériences concrètes des publics comptent donc autant que les messages publiés.`,
// 6
`Qu'est-ce qui influence la confiance numérique ? La fiabilité, avec des informations exactes et actualisées. La cohérence, avec des messages concordants entre les canaux. La transparence appropriée, avec des explications sur les faits pouvant être communiqués. La réactivité organisée, avec un traitement et un suivi des demandes. Le respect, avec des échanges professionnels, même en cas de désaccord. Et la responsabilité, avec la correction des erreurs et la protection des personnes. Retenez ce message clé. Une communication visuellement soignée ne compense jamais durablement des informations erronées ou des démarches mal expliquées.`,
// 7
`Faisons un exercice d'ouverture. Une institution publie une annonce de formation, mais le visuel indique une date différente de celle du site. Plusieurs internautes demandent laquelle est correcte, et personne ne répond pendant plusieurs jours. Réfléchissez. Quels éléments de l'identité numérique sont concernés ? Quelle perception cette situation peut-elle produire ? À quel moment le problème aurait-il pu être évité ? Quelles actions relèvent de la prévention, et lesquelles de la correction ? Vous le constaterez, la réputation dépend aussi de la qualité des processus internes de production, de validation et de réponse.`,
// 8
`Qu'est-ce que la veille de l'image numérique ? C'est l'observation organisée des informations et interactions pertinentes concernant l'institution, dans les espaces auxquels elle peut légitimement accéder. Elle permet de repérer les questions récurrentes, d'identifier les informations erronées, de détecter des difficultés de compréhension, d'observer les réactions à une annonce, de suivre les mentions publiques de l'institution, et de signaler les situations qui demandent une vérification. Attention toutefois. La veille ne doit jamais devenir une surveillance indiscriminée des personnes, ni contourner les règles d'accès aux espaces privés.`,
// 9
`Il faut ensuite définir le périmètre de la veille. On peut suivre les mentions publiques du nom officiel de l'institution, les questions ou informations concernant un programme, les commentaires et messages reçus sur les comptes officiels, les réactions aux publications, les reprises des partenariats annoncés et leurs éventuelles erreurs, les questions récurrentes sur les démarches, et les incidents signalés, comme des difficultés de service ou des incohérences. La règle est de sélectionner les informations utiles à vos missions de communication, plutôt que de collecter systématiquement tout ce qui est disponible.`,
// 10
`Voici une méthode simple de veille, en six étapes. Un, définir les sujets, c'est-à-dire les programmes, activités ou questions à suivre. Deux, choisir les sources, les comptes et les espaces publics pertinents. Trois, organiser les observations, en précisant qui consulte les sources et à quelle fréquence. Quatre, qualifier les signaux, pour savoir s'il s'agit d'une question, d'une critique, d'une erreur ou d'un risque. Cinq, transmettre les informations utiles aux bonnes personnes. Et six, suivre les suites, pour savoir si une réponse ou une correction est nécessaire. Observer, qualifier, transmettre, agir, suivre.`,
// 11
`Distinguons maintenant signal, incident et risque. Un signal est une information qui attire l'attention sur une difficulté possible, par exemple plusieurs questions sur une même date. Un incident est un problème constaté, par exemple deux dates officielles contradictoires publiées. Et un risque réputationnel est la possibilité que la situation affecte la confiance ou l'image de l'institution, par exemple si des candidats prennent une mauvaise décision à cause de la contradiction. Un point important. Un signal ne prouve pas à lui seul qu'un incident existe. Il faut toujours vérifier avant de conclure.`,
// 12
`On peut regrouper les risques réputationnels en six familles. Les risques informationnels, avec des informations fausses, incomplètes, ambiguës ou périmées. Les risques relationnels, avec des réclamations non suivies ou des échanges irrespectueux. Les risques éditoriaux, avec des publications non validées ou des incohérences entre canaux. Les risques liés aux contenus, comme l'usage d'images ou de textes sans vérifier les droits. Les risques liés aux données, avec la diffusion inappropriée d'informations personnelles. Et les risques liés aux outils, comme un compte compromis ou un contenu généré par IA non vérifié.`,
// 13
`La prévention commence dès la production. Avant de publier, votre équipe doit pouvoir répondre à plusieurs questions. La source est-elle identifiée ? Les faits et les dates sont-ils vérifiés ? Le contenu correspond-il à la version validée ? Les visuels et textes peuvent-ils être utilisés ? Les personnes représentées ont-elles donné les autorisations nécessaires ? Le contenu révèle-t-il des données à protéger ? Les liens fonctionnent-ils, et les comptes de diffusion sont-ils les bons ? Et une personne habilitée a-t-elle autorisé la publication ? Comme au Module neuf, ces contrôles s'intègrent au workflow, et non après la diffusion.`,
// 14
`Construisons une routine de veille réaliste. En début de journée, examinez les interactions reçues sur les comptes officiels. Après une publication importante, vérifiez les questions et les réactions. Pendant une campagne, suivez les informations pratiques et les difficultés signalées. En fin de journée, actualisez les demandes en attente. Et lors d'une revue périodique, identifiez les questions récurrentes et les améliorations possibles. Adaptez cette fréquence à vos ressources, à vos horaires et à la sensibilité de vos activités. Et définissez toujours qui assure la veille, qui le remplace, et comment les alertes sont transmises.`,
// 15
`Le communicant contribue à la protection de l'institution en vérifiant ce qu'il produit et diffuse. Sa responsabilité professionnelle comprend l'exactitude des informations, la cohérence avec l'identité institutionnelle, le respect des validations, la vérification des droits sur les contenus, la protection des informations sensibles, la vigilance dans l'usage des outils, et le signalement des risques qui dépassent son périmètre. Retenez ce principe essentiel. Disposer d'un outil qui permet de publier un contenu ne signifie jamais être autorisé à le publier. La vigilance fait partie du métier.`,
// 16
`Parlons du droit d'auteur. Avant d'utiliser une photographie, une illustration, une vidéo, une musique ou un texte créé par un tiers, posez-vous six questions. Qui a créé ce contenu ? D'où provient-il ? Quelles utilisations sont autorisées ? L'autorisation couvre-t-elle le support et l'usage envisagés ? Des conditions d'attribution ou d'autres restrictions s'appliquent-elles ? Et l'institution peut-elle conserver la preuve de l'autorisation ou de la licence ? Une précaution importante. Un contenu accessible sur internet n'est pas forcément libre de droits. Les règles doivent être vérifiées selon le pays et les conditions d'utilisation.`,
// 17
`Passons au droit à l'image. Photographier et publier ne sont pas la même chose. Une photo peut être disponible sans que sa publication soit appropriée ou autorisée. Soyez particulièrement attentifs au portrait d'un bénéficiaire, à une photo de salle de formation, à une interview vidéo, à un témoignage illustré, à la photo d'un mineur, ou à la réutilisation d'une image dans une nouvelle campagne. Demandez-vous si les personnes ont été informées de l'usage prévu, si les autorisations ont été vérifiées, si l'usage reste conforme, et si la publication expose quelqu'un à un risque. En cas de doute, consultez la fonction compétente.`,
// 18
`Les activités de communication peuvent impliquer des données personnelles, comme des noms, des coordonnées, des photographies identifiables, des numéros de dossier, des listes de bénéficiaires, des informations sur les candidatures, ou des documents internes. Voici les bonnes pratiques. Ne collectez que le nécessaire. Utilisez les canaux et outils autorisés. Limitez l'accès aux personnes habilitées. Évitez les données personnelles en commentaire public. Ne transmettez jamais de documents confidentiels à un outil non approuvé. Et appliquez les procédures internes en cas d'exposition accidentelle. La facilité du partage numérique renforce l'importance des contrôles.`,
// 19
`Voici quelques exemples de publications à risque. Publier une liste nominative de bénéficiaires expose des données, il faut vérifier la nécessité et les autorisations. Utiliser une photo trouvée en ligne pose la question des droits, il faut vérifier la licence. Publier une interview engage l'image et les propos, il faut vérifier les conditions de diffusion. Copier une note interne dans un outil externe menace la confidentialité. Publier un chiffre non confirmé crée une désinformation involontaire. Et reprendre une réponse générée par IA peut introduire une erreur. Chaque risque doit être examiné avant la publication, et pas seulement après une plainte.`,
// 20
`L'IA générative est une assistance, pas une autorité éditoriale. Elle peut vous aider à proposer un brouillon, reformuler un texte, résumer un document autorisé, adapter un message à une plateforme, suggérer une structure, ou préparer une foire aux questions à partir de sources vérifiées. Mais elle peut aussi produire des faits inexacts, des références inexistantes, des formulations trompeuses, des contenus non conformes à votre ligne éditoriale, ou des réponses qui dépassent les informations disponibles. La règle est claire. La responsabilité de la publication demeure toujours humaine et institutionnelle.`,
// 21
`Avant d'utiliser une production assistée par IA, contrôlez six dimensions. L'exactitude, pour vérifier que les dates, les chiffres, les noms et les conditions correspondent aux sources officielles. La pertinence, pour s'assurer que le contenu répond à l'objectif et au public. L'identité institutionnelle, pour que le ton et les formulations respectent la ligne éditoriale. Les droits, pour savoir si des vérifications complémentaires sont nécessaires. La confidentialité, pour vérifier qu'aucune information protégée n'a été introduite dans l'outil ou reproduite dans le résultat. Et la validation, pour que la version finale ait bien suivi le circuit institutionnel.`,
// 22
`Faisons un exercice rapide de cinq minutes. Publier ou vérifier ? A, un outil d'IA propose une date de clôture absente de la notice officielle. B, un collègue transmet une photographie sans préciser son origine. C, une publication contient le numéro de téléphone personnel d'un bénéficiaire. D, une foire aux questions générée par IA reprend fidèlement une notice, mais n'a pas été relue. Et E, l'équipe veut réutiliser une image de formation déjà publiée dans une nouvelle campagne. La réponse est la même pour toutes ces situations. Aucune ne doit être publiée automatiquement, et chacune exige une vérification adaptée.`,
// 23
`Place maintenant à l'atelier. Votre mission est d'élaborer un dispositif de réponse à un risque réputationnel, à partir d'un cas fictif. Chaque groupe produira huit éléments. Un diagnostic de la situation, la liste des faits confirmés et des points à vérifier, l'identification des risques, les premières mesures à prendre, la répartition des responsabilités, une proposition de communication, un dispositif de veille et de suivi, et enfin deux mesures de prévention. Votre livrable est une fiche de réponse structurée, que vous pourrez directement adapter à votre environnement professionnel.`,
// 24
`Voici le cas pédagogique. Une institution publie les résultats d'un programme de formation, avec un visuel annonçant cinq cents bénéficiaires formés. Un partenaire commente publiquement que le rapport d'activités mentionne trois cent cinquante bénéficiaires, et demande d'où vient le chiffre de cinq cents. Plusieurs internautes partagent ce commentaire. L'équipe découvre alors que le chiffre de cinq cents vient d'un brouillon préparé avec un outil d'IA, et qu'il n'a pas été vérifié avant publication. Précision importante, rien ne permet encore de confirmer le nombre définitif de bénéficiaires.`,
// 25
`Première étape, établir les faits, en cinq minutes. Distinguez soigneusement le statut de chaque élément. Qu'un visuel officiel indique cinq cents bénéficiaires, c'est un fait du cas. Qu'un partenaire cite un rapport mentionnant trois cent cinquante, c'est une affirmation à vérifier dans le document. Que le chiffre de cinq cents provienne d'un brouillon assisté par IA, c'est un fait. Que le nombre définitif soit trois cent cinquante, ce n'est pas confirmé. Et que l'institution ait volontairement trompé le public, c'est une intention non établie. Ne déduisez jamais une intention d'une simple erreur de publication.`,
// 26
`Deuxième étape, identifier les risques, en cinq minutes. Examinez les risques possibles. La diffusion d'un chiffre inexact, la confusion entre versions de documents, la perte de confiance de certains publics, la reprise de l'erreur sur d'autres canaux, des réponses contradictoires, l'utilisation d'un contenu assisté par IA sans contrôle, et l'absence de traçabilité de la validation. Posez-vous ensuite une question. Quels risques sont déjà matérialisés dans le cas, et lesquels restent hypothétiques ? L'enjeu pédagogique est de bien distinguer le problème constaté de ses conséquences possibles.`,
// 27
`Troisième étape, décider des premières mesures, en cinq minutes. Voici une démarche possible. Alertez le responsable communication. Retrouvez le rapport et les données de référence. Consultez le service responsable des résultats. Identifiez tous les supports qui contiennent le chiffre contesté. Suspendez toute nouvelle diffusion de ce chiffre tant qu'il n'est pas confirmé. Préparez une correction ou une clarification, faites-la valider, puis suivez les réactions. Une règle essentielle. Ne remplacez pas immédiatement cinq cents par trois cent cinquante, sans avoir vérifié la définition, la période et le périmètre des chiffres.`,
// 28
`Quatrième étape, répartir les responsabilités, en cinq minutes. Le community manager signale les commentaires et prépare une réponse initiale. Le responsable communication coordonne le traitement éditorial. Le service chargé des résultats vérifie les données et leur périmètre. Le validateur habilité autorise la correction et la communication. Le responsable de publication met à jour les supports selon la décision. Et l'équipe de veille suit les reprises et les nouvelles questions. Comme toujours, adaptez ces fonctions à l'organigramme réel de votre institution.`,
// 29
`Cinquième étape, rédiger une réponse institutionnelle, en huit minutes. Voici une réponse initiale possible, à soumettre à validation. Merci d'avoir signalé cette différence. Nous vérifions actuellement les chiffres publiés avec le service responsable des données, afin de confirmer leur périmètre et la version de référence. Une clarification sera apportée sur nos canaux officiels dès la fin des vérifications. Après vérification, prévoyez une seconde communication, qui indique le chiffre confirmé, précise la période et le périmètre, corrige les supports inexacts, et renvoie à la source officielle. Et surtout, n'inventez pas la conclusion des vérifications.`,
// 30
`Sixième étape, définir le suivi et la prévention, en sept minutes. Pour le suivi, vérifiez les publications corrigées, identifiez les autres supports concernés, répondez aux nouvelles questions, conservez les versions et les validations, et signalez les informations encore inexactes. Pour la prévention, exigez une source de référence pour chaque chiffre publié, ajoutez un contrôle spécifique des données chiffrées, interdisez les chiffres proposés par IA sans vérification, clarifiez les responsabilités de validation, et conservez la version officielle des données. Et vous, quelle modification du workflow du Module neuf aurait le plus directement évité cette erreur ?`,
// 31
`Passons à la restitution, en cinq minutes par groupe. Présentez le problème constaté, les faits à vérifier, les risques identifiés, les mesures immédiates, les responsables mobilisés, la réponse initiale, la correction envisagée après vérification, et vos mesures de prévention. Je vous poserai quelques questions. Avez-vous confirmé un chiffre sans preuve ? Avez-vous bien distingué erreur et intention ? Votre réponse reconnaît-elle le signalement ? Les responsabilités sont-elles claires ? Les corrections couvrent-elles tous les supports ? Et votre dispositif réduit-il vraiment le risque de répétition ?`,
// 32
`Voici la grille d'évaluation de l'atelier, qui traduit les exigences des R A sept et huit. Elle porte sur dix critères. Le diagnostic, correctement décrit. L'analyse des faits, qui distingue les informations confirmées des hypothèses. L'identification des risques, sans dramatisation. La vérification auprès des bons services. Des responsabilités attribuées aux fonctions habilitées. Une réponse claire, prudente et professionnelle. La correction de tous les supports inexacts. Le suivi des interactions. Des mesures de prévention concrètes. Et un usage responsable de l'IA, avec un contrôle humain des données et des contenus.`,
// 33
`Vérifions notre compréhension avec cinq questions. Un, l'institution contrôle-t-elle entièrement son e-réputation ? Non, elle contrôle ses contenus et ses pratiques, mais pas les perceptions et publications de tiers. Deux, une information négative repérée en ligne est-elle forcément un incident confirmé ? Non, c'est un signal à vérifier. Trois, une photo accessible sur internet peut-elle être librement réutilisée ? Pas nécessairement, il faut vérifier les droits. Quatre, une réponse produite par IA peut-elle être publiée sans relecture ? Non. Et cinq, que faire d'abord face à un chiffre contesté ? Retrouver les sources, et vérifier la définition, la période et le périmètre.`,
// 34
`Pour conclure, voici les dix principes à retenir. L'identité numérique et l'e-réputation ne sont pas identiques. La réputation se construit aussi par l'expérience des publics. La veille doit être organisée et proportionnée. Un signal doit être vérifié avant d'être présenté comme un fait. La prévention commence dans le workflow éditorial. Les droits des contenus doivent être vérifiés, et les personnes représentées protégées. Les outils s'utilisent dans un cadre autorisé, et l'IA assiste sans remplacer votre contrôle. Enfin, chaque erreur doit mener à une correction et à une amélioration. Merci à toutes et à tous.`,
];
