module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le cours DSC trois cent vingt-quatre. Ce premier chapitre est une introduction à l'analyse avancée des données. Tout au long de ce cours, nous apprendrons à explorer, résumer et structurer des jeux de données comportant de nombreuses variables. Nous verrons la visualisation multidimensionnelle, la réduction dimensionnelle, le clustering et la classification. Mais avant d'entrer dans ces techniques, nous devons poser les bases, et comprendre ce qui rend les données multidimensionnelles si particulières.`,
// 2
`Voici les objectifs pédagogiques de ce chapitre. Premièrement, comprendre les fondements de l'analyse avancée des données. Deuxièmement, identifier les caractéristiques essentielles d'un ensemble de données, c'est-à-dire sa structure en observations et en variables. Troisièmement, distinguer les différents types de variables et leurs propriétés, car ce sont elles qui orientent le choix des méthodes. Et quatrièmement, comprendre les enjeux spécifiques des données multidimensionnelles. Ces notions reviendront dans chacun des chapitres suivants, prenez donc le temps de bien les assimiler. Allons-y. Bonne étude.`,
// 3
`Qu'est-ce que l'analyse avancée des données ? C'est l'ensemble des méthodes statistiques qui permettent d'explorer, de résumer et de structurer de grands ensembles de données, comportant de nombreuses variables, afin d'en tirer des informations utiles à la décision. Contrairement à la statistique descriptive univariée, elle s'intéresse aux relations entre plusieurs variables observées sur les mêmes individus. C'est le champ de la statistique multivariée. Ce cours s'appuie sur quatre familles de techniques, la visualisation, la réduction dimensionnelle, le clustering et la classification.`,
// 4
`Un ensemble de données multivariées se représente sous la forme d'une matrice X, de dimension n lignes sur p colonnes. N est le nombre d'observations, ou individus, et p le nombre de variables mesurées sur chacun. Chaque ligne correspond à un individu statistique, un client, un patient ou une entreprise, et chaque colonne à une caractéristique mesurée. Toutes les techniques du cours exploitent cette matrice. Soit on réduit le nombre de colonnes, c'est la réduction dimensionnelle. Soit on regroupe les lignes, c'est le clustering. Soit on prédit une catégorie pour chaque ligne, c'est la classification.`,
// 5
`Le choix d'une méthode dépend avant tout de la nature des variables. Les variables quantitatives peuvent être continues, prenant une infinité de valeurs dans un intervalle, comme la taille, le revenu ou la température. Ou discrètes, ne prenant que des valeurs isolées, souvent entières, comme le nombre d'enfants. Les variables qualitatives peuvent être nominales, des catégories sans ordre naturel, comme la couleur ou la région. Ou ordinales, des catégories ordonnées sans écart numérique constant, comme le niveau de satisfaction ou le niveau d'études.`,
// 6
`Pourquoi cette distinction est-elle essentielle ? Parce que la nature des variables détermine trois choses. D'abord, les représentations graphiques appropriées, que nous verrons au chapitre deux. Ensuite, les mesures de distance ou de similarité utilisables en clustering, aux chapitres sept et huit. Et enfin, les méthodes de réduction dimensionnelle possibles. L'analyse en composantes principales s'applique aux variables quantitatives, tandis que l'analyse des correspondances s'applique aux variables qualitatives. Se tromper sur le type d'une variable, c'est donc risquer de choisir une méthode inadaptée.`,
// 7
`Lorsque le nombre de variables devient élevé, cinq difficultés apparaissent. La visualisation, car l'oeil humain n'interprète que deux ou trois dimensions à la fois. La redondance, car de nombreuses variables mesurent en partie la même information. La malédiction de la dimensionnalité, les notions de distance et de proximité perdent leur pertinence quand p augmente fortement. Le risque de surinterprétation, plus il y a de variables, plus on détecte des corrélations fortuites. Et enfin le coût de calcul, qui explose pour certains algorithmes.`,
// 8
`Face à ces enjeux, l'analyse avancée propose une démarche méthodique en quatre temps. D'abord, explorer et visualiser les données, ce sera l'objet du chapitre deux. Ensuite, réduire leur dimensionnalité lorsque c'est pertinent, aux chapitres trois à cinq. Puis regrouper ou classer les observations, aux chapitres sept à dix. Et à chaque étape, sélectionner la méthode la plus adaptée à la structure des données et à l'objectif poursuivi. Explorer, réduire, regrouper, sélectionner, retenez ces quatre verbes, ils résument tout le cours.`,
// 9
`Soulignons enfin le rôle de l'analyse statistique dans la découverte d'information. L'analyse avancée des données n'est pas une fin en soi. C'est un support à la prise de décision. Chaque méthode doit donc être utilisée avec un objectif clair, décrire, réduire, regrouper ou prédire. Et ses résultats doivent toujours être interprétés en contexte, en tenant compte des limites de la méthode et de la qualité des données. Un résultat spectaculaire obtenu sur des données de mauvaise qualité ne vaut rien pour décider.`,
// 10
`Retenons les points clés. Un ensemble de données multivariées se représente comme une matrice n sur p, d'observations et de variables. Les variables sont quantitatives, continues ou discrètes, ou qualitatives, nominales ou ordinales, et ce type conditionne le choix des méthodes. Les données multidimensionnelles posent des défis de visualisation, de redondance, de dimensionnalité, de surinterprétation et de coût de calcul. Enfin, l'analyse avancée est un support à la décision, qui mobilise successivement visualisation, réduction dimensionnelle, clustering et classification. Au prochain chapitre, nous passerons à la visualisation.`,
// 11
`Passons aux exercices, avec leurs corrigés. Premier exercice, pour l'assureur, l'âge et le revenu sont quantitatifs continus, le sexe et la région sont qualitatifs nominaux, et la satisfaction est qualitative ordinale. Deuxième exercice, des variables très corrélées portent en partie la même information. On peut donc les résumer par quelques dimensions, sans perte importante. Troisième exercice, avec cinquante observations et huit cents variables, on subit la malédiction de la dimensionnalité, un fort risque de corrélations fortuites, et l'impossibilité d'estimer une régression classique. Merci, et à bientôt pour le chapitre deux.`,
];
