module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le Module quatorze, consacré à l'analyse des résultats et à l'amélioration de la stratégie. Nous sommes le vendredi deux octobre deux mille vingt-six, et ce module dure deux heures. Il est animé par votre formateur principal, Pawou Batana, pour les Institutions et Fonds membres du RAFPRO. Au module précédent, vous avez appris à mesurer. Nous allons maintenant apprendre à tirer de ces mesures des décisions d'amélioration utiles et justifiées.`,
// 2
`Le Module treize vous a permis de choisir des indicateurs, de calculer des taux, et de formuler des constats fondés sur les données. Le Module quatorze poursuit ce travail avec une question clé. Comment passer d'un résultat observé à une décision d'amélioration justifiée, réaliste et mesurable ? Nous comparerons objectifs et résultats, identifierons les contenus performants ou non, interpréterons les écarts, formulerons des hypothèses, et prioriserons des recommandations. Précisons que tous les chiffres et les cibles utilisés ici sont fictifs, et qu'une hypothèse reste une hypothèse tant qu'elle n'a pas été vérifiée.`,
// 3
`Voici l'organisation de nos cent vingt minutes. Vingt minutes pour passer de la mesure au diagnostic, vingt-cinq pour interpréter les écarts et formuler des hypothèses, et vingt-cinq pour concevoir et prioriser les améliorations. Puis un atelier de quarante minutes, et dix minutes d'évaluation et de synthèse. Munissez-vous d'une calculatrice ou d'un tableur, et du jeu de données du Module treize. Votre livrable sera une note d'amélioration. Ce module vise le R A dix, analyser les résultats et formuler des recommandations argumentées pour améliorer la communication.`,
// 4
`Commençons par la séquence un, pour vingt minutes. Il s'agit de passer de la mesure au diagnostic, c'est-à-dire de comprendre ce que les chiffres disent vraiment, avant de décider quoi que ce soit.`,
// 5
`Voici une situation fictive. Une campagne a généré cinq cent quatre-vingt-dix clics vers une page d'information, et le responsable demande ce qu'il faut changer pour la prochaine campagne. Le chiffre de cinq cent quatre-vingt-dix clics ne permet pas, à lui seul, de répondre. Il faut connaître l'objectif initial, la cible fixée si elle existe, les résultats par contenu, les conditions de diffusion, les données manquantes, et les contraintes opérationnelles. Retenez ce message clé. Une recommandation professionnelle doit découler d'un diagnostic, et non d'une simple impression.`,
// 6
`À l'issue de ce module, vous saurez comparer les résultats aux objectifs et aux cibles, identifier les forces et les insuffisances d'une action, et distinguer constat, hypothèse et cause vérifiée. Vous saurez interpréter les écarts sans extrapoler, et identifier les informations manquantes. Vous saurez aussi proposer des actions correctives, formuler des recommandations argumentées, les prioriser selon des critères explicites, leur associer un responsable et un indicateur de suivi, et organiser une démarche d'amélioration continue. La compétence attendue est de transformer vos résultats en décisions opérationnelles justifiées.`,
// 7
`Voici la chaîne complète de l'amélioration. Tout commence par l'objectif, c'est-à-dire le résultat recherché. Vient ensuite la mesure, avec les données fiables disponibles. Puis le diagnostic, qui identifie les écarts et les constats. Ensuite les hypothèses, c'est-à-dire les explications à vérifier. Et enfin les actions, ce que l'on peut réalistement modifier. Retenez ce principe. L'amélioration est un cycle continu, et non une décision ponctuelle prise une fois pour toutes.`,
// 8
`Distinguons cinq niveaux. Le résultat est la valeur observée, par exemple quatre cent vingt visites. Le constat est ce que montre la comparaison, ici une cible de cinq cents visites non atteinte. L'hypothèse est une explication possible, par exemple un lien peu visible. La vérification est la façon de tester cette hypothèse, en examinant le contenu et les clics. Et la recommandation est l'action proposée, comme tester un appel à l'action plus explicite. Attention, le constat est établi par les données, mais l'explication sur la visibilité du lien ne l'est pas encore.`,
// 9
`Comparons objectifs et résultats. L'objectif était de générer cinq cents visites attribuées vers une page officielle, et le résultat est de quatre cent vingt visites. L'écart absolu est de quatre cent vingt moins cinq cents, soit moins quatre-vingts visites. Le taux de réalisation est de quatre cent vingt divisé par cinq cents, fois cent, soit quatre-vingt-quatre pour cent. Le constat est donc que le résultat atteint quatre-vingt-quatre pour cent de la cible, et qu'il manque quatre-vingts visites. En revanche, on ne peut pas conclure sans preuve que le contenu est mauvais, ou que la plateforme n'est pas adaptée.`,
// 10
`Faisons un exercice de cinq minutes. Classez chaque phrase comme constat, hypothèse ou recommandation. A, le taux de clics du carrousel est de deux virgule soixante-sept pour cent. B, le format étape par étape a peut-être facilité le passage vers la page. C, tester un second carrousel sur les démarches. D, le témoignage a généré cinq cents interactions. E, le témoignage plaît davantage parce qu'il est plus authentique. Correction. A et D sont des constats, B et E des hypothèses, et C une recommandation. Une hypothèse plausible ne devient pas un fait parce qu'elle semble convaincante.`,
// 11
`Passons à la séquence deux, pour vingt-cinq minutes. Nous allons apprendre à interpréter les écarts, et à formuler des hypothèses explicatives, sans jamais confondre ce que l'on sait avec ce que l'on suppose.`,
// 12
`Qu'est-ce qu'un écart de performance ? C'est une différence entre une cible et un résultat, entre deux périodes comparables, entre deux contenus comparables, entre deux segments de publics, ou entre deux modalités de diffusion. Par exemple, une publication génère deux cent quarante clics, contre quatre-vingt-dix pour une autre, soit un écart de cent cinquante clics. Mais avant d'interpréter cette différence, il faut examiner les objectifs, les impressions, les formats, les périodes et les conditions de diffusion. Retenez qu'un écart décrit une différence, mais n'en fournit jamais automatiquement l'explication.`,
// 13
`Reprenons les données fictives du Module treize. La publication A, un visuel d'annonce, a une portée de douze mille et quatre-vingt-dix clics. La vidéo B a huit mille de portée et cent soixante clics. Le carrousel C a six mille de portée et deux cent quarante clics. Et le témoignage D a dix mille de portée et cinq cents interactions. Pour l'exposition, A est en tête. Pour le volume d'interactions, c'est D. Et pour les clics vers la page, c'est C. Conclusion, un contenu performant doit toujours être rapporté à un objectif et à un indicateur.`,
// 14
`Un contenu sous-performant n'est pas forcément inutile. Il peut obtenir un résultat inférieur à une cible tout en remplissant une fonction utile. Par exemple, une information réglementaire importante peut toucher un public restreint, mais réellement concerné. Une foire aux questions peut générer peu de réactions, mais aider à répondre aux questions. Et une publication destinée à des partenaires spécialisés peut avoir une faible portée, tout en atteignant son public prioritaire. Ne supprimez donc jamais un type de contenu uniquement parce qu'il génère moins de réactions. Examinez d'abord son rôle dans la stratégie.`,
// 15
`Lorsqu'un résultat s'écarte des attentes, quatre familles d'hypothèses peuvent être explorées. Le message, d'abord. Le contenu est-il clair, et l'appel à l'action compréhensible ? Le public, ensuite. Le contenu correspond-il à ses besoins ? Le format et le canal. Le format est-il adapté à la plateforme et à l'usage recherché ? Et la diffusion et le parcours. Le lien fonctionne-t-il, la page est-elle accessible, et la période de diffusion appropriée ? Une précaution importante. Ces familles orientent votre enquête, mais elles ne prouvent aucune cause particulière.`,
// 16
`Une hypothèse utile doit pouvoir être confrontée à des observations. Comparez deux formulations. Une formulation vague, le public n'aime pas nos contenus. Et une formulation vérifiable, le taux de clics pourrait être affecté par un appel à l'action peu visible, ce que nous pouvons tester en comparant deux formulations sur des contenus similaires, pendant des périodes comparables. Voici une structure recommandée. Nous observons tel constat. Une explication possible est telle hypothèse. Pour la vérifier, nous examinerons telle donnée ou tel test. Une hypothèse doit ouvrir une vérification, et non fermer la discussion.`,
// 17
`Il faut aussi chercher les informations manquantes. Par exemple, une publication obtient deux cents clics, mais le nombre de visites du site n'est pas disponible. Posez-vous plusieurs questions. Le lien renvoie-t-il vers la bonne page ? Le suivi du trafic est-il bien configuré ? L'outil d'analyse du site est-il accessible ? La période est-elle identique ? Ou les données sont-elles simplement absentes du dossier ? La conclusion appropriée est que les clics sont connus, mais pas les visites. Retenez ce principe. Signaler une donnée manquante vaut mieux que la remplacer par une estimation non justifiée.`,
// 18
`La triangulation consiste à confronter plusieurs sources pour mieux comprendre une situation. Les statistiques de la plateforme donnent les impressions, les interactions et les clics. L'outil d'analyse du site donne les visites et les parcours. Les questions reçues révèlent les difficultés des publics. Le service métier informe sur les démarches ou demandes traitées. Et une vérification technique contrôle le fonctionnement du lien et de la page. Mais attention, croiser les sources peut renforcer un diagnostic, sans jamais garantir qu'une cause est définitivement démontrée.`,
// 19
`Faisons un exercice. Une publication génère de nombreux clics, mais le service signale peu de demandes finalisées. Voici quatre hypothèses. A, le formulaire est difficile à utiliser. B, les internautes cherchent seulement de l'information. C, le lien mène à une mauvaise page. D, les données de finalisation sont incomplètes. Associez à chacune une vérification. Pour A, testez le parcours du formulaire et examinez les retours. Pour B, analysez les besoins exprimés. Pour C, contrôlez le lien. Et pour D, vérifiez la méthode de collecte. Plusieurs explications peuvent coexister, et les données disponibles déterminent ce qui peut être affirmé.`,
// 20
`Voici la séquence trois, pour vingt-cinq minutes. Après le diagnostic, nous allons concevoir des améliorations concrètes, puis apprendre à les prioriser selon des critères clairs et explicites.`,
// 21
`Une recommandation argumentée relie un constat, une justification, une action, et un résultat à suivre. Prenons un exemple. Le constat est que le carrousel C génère deux cent quarante clics, le volume le plus élevé du jeu de données. La justification est que son format explique les étapes de candidature, ce qui correspond à l'objectif d'orientation. La recommandation est de tester un nouveau carrousel sur les pièces à fournir. Et le suivi consiste à comparer les clics et le taux de clics sur une période définie. Précision importante, c'est une proposition de test, et non la garantie d'un même résultat.`,
// 22
`Une recommandation peut porter sur plusieurs leviers. Le message, par sa clarification, sa hiérarchie et son appel à l'action. Le contenu, par le choix du thème, des informations pratiques, des exemples ou des témoignages. Le format, qu'il soit texte, visuel, carrousel ou vidéo. La plateforme, selon le public et l'objectif. La diffusion, avec le calendrier, la fréquence et la coordination des canaux. Le parcours, avec le lien, la page d'arrivée et l'accessibilité. La relation, avec la réponse aux questions. Et le processus, avec la vérification et la validation. Choisissez toujours le levier selon votre diagnostic.`,
// 23
`Passons d'une recommandation vague à une action exploitable. Améliorer les publications devient, tester deux formulations d'appel à l'action sur des publications comparables. Faire plus de vidéos devient, produire une vidéo courte répondant aux trois questions les plus fréquentes. Publier davantage devient, vérifier d'abord si la fréquence actuelle répond aux besoins et aux capacités. Augmenter l'engagement devient, tester une publication de questions-réponses. Et mieux communiquer devient, mettre à jour la notice et harmoniser les informations. Une action doit être assez précise pour être confiée, réalisée et évaluée.`,
// 24
`Une action corrective doit préciser sept éléments. Le problème auquel elle répond, le changement proposé, le responsable, les ressources nécessaires, l'échéance, l'indicateur de suivi, et les conditions de validation. Par exemple, le responsable éditorial préparera, pour la prochaine campagne, deux variantes de l'appel à l'action d'une publication informative. Ces variantes seront validées avant diffusion, et leurs clics et taux de clics seront comparés sur des périodes équivalentes. Une règle importante. Ne promettez jamais une hausse chiffrée sans base suffisante pour la justifier.`,
// 25
`Toutes les actions ne peuvent pas être menées en même temps. Il faut donc les prioriser, en tenant compte de la contribution attendue à l'objectif, de l'urgence, des risques à traiter, des ressources nécessaires, de la faisabilité, des dépendances entre actions, et des responsabilités disponibles. Par exemple, corriger un lien défectueux peut passer avant la création d'un nouveau format, car ce lien empêche immédiatement les publics d'accéder à l'information. Attention, la priorisation doit toujours être expliquée. Elle ne repose pas sur la seule préférence personnelle du communicant.`,
// 26
`Voici une matrice simple de priorisation. Corriger un lien erroné a une contribution directe à l'objectif pour un effort faible, c'est donc à traiter rapidement. Clarifier une notice ambiguë a une contribution directe pour un effort modéré, à planifier avec le service métier. Tester une variante d'appel à l'action a une contribution potentielle pour un effort faible à modéré, c'est à expérimenter. Et produire une nouvelle série vidéo a une contribution encore à établir pour un effort élevé, à examiner après diagnostic. Cette matrice illustre une méthode, à adapter à chaque institution.`,
// 27
`Comment tester une amélioration sans conclure trop vite ? Définissez ce qui est modifié, choisissez un indicateur principal, et fixez une période d'observation. Documentez les conditions de diffusion, comparez les résultats avec prudence, et examinez les éventuels facteurs externes. Puis décidez de poursuivre, d'ajuster ou d'abandonner le test. Par exemple, testez deux appels à l'action sur des contenus aussi comparables que possible. Mais gardez à l'esprit une limite. Si les publics, les périodes ou les conditions diffèrent fortement, vous ne pourrez pas attribuer l'écart avec certitude à la seule formulation.`,
// 28
`L'amélioration continue fonctionne comme une boucle de pilotage. Planifier, en définissant l'objectif, la cible, les actions et les indicateurs. Mettre en œuvre, en produisant, validant et diffusant les contenus. Vérifier, en mesurant, comparant et analysant les résultats. Ajuster, en corrigeant les erreurs et en testant des améliorations. Et recommencer, en intégrant les enseignements dans la campagne suivante. Planifier, agir, mesurer, apprendre, ajuster. Retenez que l'amélioration continue suppose des décisions suivies d'une nouvelle mesure.`,
// 29
`Voici la séquence quatre, l'atelier, pour quarante minutes. Vous allez produire des recommandations argumentées, à partir des données de la campagne fictive que vous avez analysée au Module treize.`,
// 30
`Votre mission est de produire une note d'amélioration pour cette campagne institutionnelle fictive. Chaque groupe reprend le jeu de données du Module treize, et doit rappeler les objectifs, comparer les résultats aux cibles pédagogiques, identifier trois constats, formuler deux hypothèses à vérifier, proposer trois recommandations argumentées, les prioriser, et définir les responsables et les indicateurs de suivi. Vous disposez de quarante minutes au total. Votre livrable est une note d'amélioration synthétique, que vous présenterez à l'oral en fin d'atelier.`,
// 31
`Rappelons les données de départ. La campagne vise à faire connaître un programme et à orienter vers sa page officielle. Le visuel A a une portée de douze mille, quatre cent cinquante interactions et quatre-vingt-dix clics. La vidéo B a huit mille de portée, quatre cents interactions et cent soixante clics. Le carrousel C a six mille de portée, deux cent quarante interactions et deux cent quarante clics. Et le témoignage D a dix mille de portée, cinq cents interactions et cent clics. Attention, les clics ne sont pas assimilés à des visites réellement enregistrées sur le site.`,
// 32
`Pour ce module, nous ajoutons des cibles pédagogiques fictives, qui n'existaient pas au Module treize. La cible de clics vers la page officielle est de sept cents clics. La cible d'interactions est de mille cinq cents interactions. En revanche, aucune cible de portée globale n'est fournie. Réfléchissez à trois questions. Quels objectifs peuvent être comparés à une cible ? Pourquoi ne peut-on pas calculer un taux de réalisation pour la portée globale ? Et que peut-on conclure à partir des clics, sans disposer des visites du site ?`,
// 33
`Premier travail, comparer les résultats aux cibles, en sept minutes. Utilisez les clics, quatre-vingt-dix plus cent soixante plus deux cent quarante plus cent, et les interactions, quatre cent cinquante plus quatre cents plus deux cent quarante plus cinq cents. Calculez les totaux, les écarts absolus et les taux de réalisation, puis formulez deux constats sans inventer de causes. Rappelons les formules. L'écart est égal au résultat moins la cible. Et le taux de réalisation est égal au résultat divisé par la cible, multiplié par cent.`,
// 34
`Voici la correction. Pour les clics, le total est de cinq cent quatre-vingt-dix. L'écart est de moins cent dix clics par rapport à la cible de sept cents, et le taux de réalisation est d'environ quatre-vingt-quatre virgule vingt-neuf pour cent. Pour les interactions, le total est de mille cinq cent quatre-vingt-dix. L'écart est de plus quatre-vingt-dix, et le taux de réalisation de cent six pour cent. La cible de clics n'est donc pas atteinte, alors que celle des interactions est dépassée. Et rappelez-vous, additionner les portées ne donnerait pas une portée globale dédupliquée.`,
// 35
`Deuxième travail, diagnostiquer les différences entre contenus, en six minutes. Quel contenu a généré le plus de clics ? Lequel a généré le plus d'interactions ? Lequel a atteint le plus de comptes ? Quelle différence observe-t-on entre C et D ? Et quelles données manquent pour évaluer les visites et les candidatures ? Voici les constats attendus. C génère deux cent quarante clics, D cinq cents interactions, et A atteint une portée de douze mille. C et D répondent donc différemment aux objectifs mesurés. Enfin, les visites attribuées et les candidatures finalisées ne sont pas disponibles.`,
// 36
`Troisième travail, formuler deux hypothèses vérifiables, en six minutes. Premier exemple. Le carrousel C pourrait faciliter le passage vers la page officielle, parce qu'il présente les démarches étape par étape. Pour le vérifier, testez un autre carrousel pratique, et comparez les clics et le taux de clics dans des conditions comparables. Deuxième exemple. Le témoignage D pourrait susciter des réactions sans inciter autant au clic. Pour le vérifier, examinez son appel à l'action et la nature des commentaires, et testez éventuellement une variante plus orientée vers la page. Ces hypothèses ne sont pas des causes démontrées.`,
// 37
`Quatrième travail, formuler trois recommandations argumentées, en dix minutes. Recommandation A, tester un contenu pratique supplémentaire. C génère le plus de clics, on produit donc un second carrousel sur une question pratique, suivi par les clics et le taux de clics. Recommandation B, vérifier le parcours vers la page. La campagne totalise cinq cent quatre-vingt-dix clics, mais les visites sont inconnues, on vérifie donc les liens et les données de trafic. Recommandation C, tester l'appel à l'action du témoignage, qui génère cinq cents interactions mais seulement cent clics.`,
// 38
`Cinquième travail, prioriser et planifier, en six minutes. Complétez la matrice pour chaque recommandation, avec sa justification, sa priorité, son responsable, son échéance et son indicateur. Par exemple, vérifier les liens et les données de trafic, parce que les visites ne sont pas connues, sous la responsabilité de la fonction compétente, avec les visites attribuées comme indicateur. Ou tester un second carrousel, puisque C génère deux cent quarante clics, confié à l'équipe éditoriale, avec les clics et le taux de clics comme indicateurs. Justifiez l'ordre retenu par la contribution, la faisabilité et les dépendances.`,
// 39
`Passons à la restitution, en cinq minutes par groupe. Présentez les deux écarts calculés, trois constats étayés, deux hypothèses à vérifier, trois recommandations argumentées, l'ordre de priorité, et les indicateurs de suivi. Je vous poserai quelques questions. Les calculs sont-ils exacts ? Les recommandations découlent-elles vraiment des données ? Les hypothèses sont-elles présentées comme telles ? Les actions sont-elles réalisables, et les priorités justifiées ? Votre note doit permettre à un responsable de comprendre les constats, d'arbitrer les actions et d'organiser leur suivi.`,
// 40
`Nous arrivons à la séquence cinq, pour dix minutes. Place à l'évaluation et à la synthèse de ce module, pour consolider tout ce que vous avez appris sur l'analyse et l'amélioration.`,
// 41
`Voici la grille d'évaluation, qui reprend les cinq critères du R A dix. C E dix point un, le diagnostic, avec les forces et insuffisances identifiées à partir des résultats. C E dix point deux, l'argumentation, chaque recommandation découlant d'un constat étayé. C E dix point trois, la pertinence des actions au regard des objectifs, des publics et des plateformes. C E dix point quatre, la faisabilité des recommandations. Et C E dix point cinq, leur priorisation selon des critères explicites. Le standard attendu est de passer de l'analyse des performances à des décisions concrètes d'amélioration.`,
// 42
`Vérifions notre compréhension avec cinq questions. Un, quelle différence entre constat et hypothèse ? Le constat décrit ce que les données établissent, l'hypothèse propose une explication à vérifier. Deux, une cible de clics non atteinte prouve-t-elle que le format est inadapté ? Non, plusieurs facteurs peuvent expliquer l'écart. Trois, que contient une recommandation argumentée ? Un constat, une justification, une action précise et un suivi. Quatre, pourquoi prioriser ? Pour organiser les décisions selon leur contribution, leur urgence et leur faisabilité. Et cinq, comment mesurer l'effet d'une amélioration ? En définissant un indicateur et en mesurant de nouveau.`,
// 43
`Pour conclure, voici les dix principes à retenir. Commencer par les objectifs et les résultats observés, et comparer les résultats à des cibles pertinentes. Distinguer les constats des hypothèses, et ne jamais inventer les causes d'un écart. Rechercher les informations manquantes, et évaluer chaque contenu selon sa fonction. Relier chaque recommandation à un constat, avec des actions précises et réalisables. Prioriser selon des critères explicites. Et mesurer de nouveau pour apprendre. Mesurer, comparer, diagnostiquer, vérifier, recommander, prioriser, ajuster. Merci à toutes et à tous.`,
];
