module.exports = [
// 1
`Bonjour à toutes et à tous, et bienvenue dans le chapitre onze du cours DSC trois cent quarante-cinq, consacré aux applications récentes du Machine Learning, à l'éthique et à l'interprétabilité. Après avoir étudié de nombreux algorithmes, nous allons les voir à l'oeuvre dans des domaines très concrets, de la voiture autonome au diagnostic médical. Mais nous allons aussi aborder une question essentielle. Un modèle performant est-il forcément juste ? Et comment expliquer ses décisions aux personnes qu'elles concernent ? Commençons.`,
// 2
`Voici les objectifs pédagogiques de ce chapitre. Premièrement, analyser des applications récentes du Machine Learning, dans des domaines variés. Deuxièmement, discuter des enjeux éthiques, des biais et de l'interprétabilité des modèles. Troisièmement, proposer des approches concrètes pour atténuer les biais, et améliorer la transparence des modèles. Et quatrièmement, synthétiser les tendances émergentes du Machine Learning. Ce chapitre vous rappelle qu'un data scientist n'est pas seulement un technicien, mais aussi un professionnel responsable. Commençons par les applications, avant d'aborder les questions éthiques.`,
// 3
`Le Machine Learning s'applique aujourd'hui dans de nombreux domaines variés et stratégiques. Nous allons en examiner quatre, qui mobilisent les algorithmes vus dans ce cours. La navigation autonome, avec les véhicules sans conducteur. L'informatique biomédicale, au service de la santé. La biométrie, avec la reconnaissance du visage, de la voix ou des empreintes. Et l'analyse de textes et du web, qui alimente les moteurs de recherche et de recommandation. Dans chacun de ces domaines, vous reconnaîtrez des notions familières. Allons-y.`,
// 4
`Première application, la navigation autonome. Les véhicules autonomes combinent plusieurs familles d'algorithmes. La classification, pour détecter les piétons, les autres véhicules et les panneaux. La régression, pour estimer les trajectoires. Et l'apprentissage par renforcement, pour prendre des décisions en temps réel, comme freiner ou changer de voie. Tout cela à partir de capteurs multiples, caméras, LiDAR, qui mesure les distances par laser, et radar. C'est l'un des domaines les plus exigeants, car une erreur peut coûter des vies. La fiabilité y est vitale.`,
// 5
`Deuxième application, l'informatique biomédicale. Le Machine Learning assiste le diagnostic médical, par exemple en analysant des images radiologiques, ou en détectant des tumeurs. Il contribue aussi à la découverte de médicaments, et à la médecine personnalisée, qui adapte le traitement à chaque patient. On y utilise notamment des algorithmes de classification, et des méthodes d'ensemble, très performantes sur les données tabulaires complexes. Dans ce domaine, le modèle aide le médecin, mais ne le remplace pas. La décision reste humaine. Gardons-le en tête.`,
// 6
`Troisième application, la biométrie. La reconnaissance faciale, la reconnaissance des empreintes digitales ou de la voix reposent sur des techniques de classification et de réduction de dimensionnalité. Elles extraient, à partir de signaux bruts, comme une image ou un enregistrement, des représentations compactes et discriminantes. Les enjeux sont forts. La robustesse, face à un éclairage différent ou un bruit de fond. Et l'équité entre populations, car un système moins fiable pour certains groupes peut créer de graves injustices. L'équité est essentielle.`,
// 7
`Quatrième application, l'analyse de textes et du web. Le traitement du langage naturel utilise le Machine Learning pour l'analyse de sentiments, par exemple savoir si un avis client est positif ou négatif. Il sert aussi à la détection de spam, aux moteurs de recommandation, et à la recherche d'information. Ces applications combinent souvent la classification supervisée avec des techniques de réduction de dimensionnalité, qui permettent de représenter un texte de façon compacte, sous forme de vecteurs de nombres. Les usages sont innombrables.`,
// 8
`Abordons maintenant les biais. Un modèle de Machine Learning reproduit, et parfois amplifie, les biais présents dans ses données d'entraînement. Ces biais ont trois sources principales. Un échantillon non représentatif de la population cible, par exemple des données collectées surtout en ville. Des choix de mesure ou d'étiquetage influencés par des préjugés humains. Et des déséquilibres historiques, déjà présents dans les décisions passées, que le modèle apprend fidèlement à reproduire. Le modèle n'est donc jamais plus juste que ses données.`,
// 9
`Voici un exemple type. Un algorithme de recrutement est entraîné sur les décisions d'embauche passées d'une entreprise. Si ces décisions historiques étaient elles-mêmes biaisées, par exemple en défavorisant certains groupes, le modèle apprend à les défavoriser à son tour. Il perpétue ainsi une discrimination, sous une apparence de neutralité algorithmique. C'est ce qui rend ces biais particulièrement dangereux. Ils semblent objectifs, puisqu'ils viennent d'une machine, alors qu'ils reproduisent des injustices humaines. Restons vigilants face à cette fausse neutralité. Restons lucides.`,
// 10
`L'interprétabilité désigne la capacité à comprendre pourquoi un modèle produit une prédiction donnée. Elle est particulièrement critique dans les domaines sensibles, comme la santé, la finance ou la justice. Dans ces domaines, une décision automatisée, comme un refus de crédit ou un diagnostic, doit pouvoir être expliquée, et contestée par la personne concernée. Or, les modèles les plus performants, comme les forêts aléatoires ou le boosting, sont souvent des boîtes noires. D'où le besoin d'outils d'explication. Voyons les deux principaux outils.`,
// 11
`Premier outil, SHAP, pour SHapley Additive exPlanations. Il s'appuie sur la théorie des jeux coopératifs. Pour une observation donnée, il attribue à chaque variable une contribution précise à l'écart entre la prédiction de cette observation et la prédiction moyenne du modèle. Cette contribution s'appelle la valeur de Shapley. Elle possède des propriétés mathématiques qui garantissent une répartition équitable de l'importance entre les variables. On peut ainsi dire, par exemple, que le revenu a fait baisser le risque prédit de tant de points.`,
// 12
`Deuxième outil, LIME, pour Local Interpretable Model-agnostic Explanations. LIME explique une prédiction individuelle en approchant localement le comportement du modèle complexe par un modèle simple et interprétable, comme une régression linéaire. Pour cela, il crée de petites perturbations autour de l'observation à expliquer, observe comment les prédictions du modèle complexe changent, et entraîne le modèle simple sur ces exemples. Le modèle simple n'est valable que localement, autour de cette observation, mais il est facile à lire. Il est très intuitif.`,
// 13
`SHAP et LIME ont un point commun important. Ce sont des méthodes dites agnostiques au modèle. Elles s'appliquent aussi bien à un arbre de décision qu'à une forêt aléatoire, à un modèle de boosting, ou à un réseau de neurones. Elles n'ont pas besoin de connaître le fonctionnement interne du modèle, seulement ses prédictions. C'est ce qui en fait des outils précieux pour auditer des modèles complexes, autrement opaques, que l'on appelle des boîtes noires. Ils sont devenus indispensables. Utilisez-les.`,
// 14
`Comment atténuer les biais et améliorer l'équité ? Plusieurs leviers se complètent. Diversifier et auditer les données d'entraînement. Mesurer la performance du modèle séparément pour différents sous-groupes de population, pour repérer les écarts. Intégrer des contraintes d'équité directement dans l'entraînement. Documenter les choix de modélisation, par exemple dans des fiches modèle. Et maintenir une supervision humaine sur les décisions à fort impact. Aucun de ces leviers ne suffit seul, c'est leur combinaison qui rend un modèle digne de confiance. Restez exigeants.`,
// 15
`Retenons les points clés. Le Machine Learning trouve des applications majeures en navigation autonome, en informatique biomédicale, en biométrie et en analyse de textes. Les biais peuvent provenir des données, avec un échantillon non représentatif ou un étiquetage biaisé, ou être amplifiés par l'algorithme lui-même. SHAP et LIME sont deux techniques agnostiques au modèle, pour expliquer les prédictions individuelles d'un modèle complexe. Enfin, l'équité et la transparence exigent un audit des données, une évaluation par sous-groupe, et une supervision humaine continue.`,
// 16
`Voici des pistes de corrigé. Premier exercice, choisissez un domaine, et cherchez un article récent dans une base de publications scientifiques. Deuxième exercice, le modèle de crédit défavorise un groupe sans utiliser directement la variable correspondante, car d'autres variables, comme le lieu de résidence, lui sont corrélées. On parle de variables proxy. SHAP aide à le diagnostiquer, combiné à une évaluation par sous-groupe. Troisième exercice, SHAP repose sur la théorie des jeux, et il est plus rigoureux mais plus coûteux. LIME est plus rapide, mais ses explications sont seulement locales et moins stables.`,
];
